; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
tR:             equ     0
tE4:            equ     3
tF4:            equ     4
tFs4:           equ     5
tG4:            equ     6
tA4:            equ     7
tBb4:           equ     8
tC5:            equ     9
tCs5:           equ     10
tD5:            equ     11
songRows:       equ     140
charlstn__pitMode: equ     67
charlstn__pitCh2: equ     66
charlstn__spkGate: equ     97
charlstn__pitSquare: equ     182
charlstn__spkOn: equ     3
charlstn__vgaStatus: equ     986
charlstn__vgaVRetrace: equ     8
charlstn__paceFast: equ     3
charlstn__paceSlow: equ     8

; =========================================================== entry ====

__entry:
; ---- putStr( addr( sTitle ) )
        mov     ax, sTitle                  ; link-time constant
        mov     [putStr__at], ax
        call    putStr
; ---- newline()
        call    newline
; ---- putStr( addr( sCredit ) )
        mov     ax, sCredit                 ; link-time constant
        mov     [putStr__at], ax
        call    putStr
; ---- newline()
        call    newline
; ---- putStr( addr( sKeys ) )
        mov     ax, sKeys                   ; link-time constant
        mov     [putStr__at], ax
        call    putStr
; ---- newline()
        call    newline
; ---- newline()
        call    newline
; ---- while ( !wantOut ) {
.L1:
        mov     al, [charlstn__wantOut]
        test    al, al
        jnz     .L3
; ---- for ( u16 row = 0; row < songRows && !wantOut; row++ ) playRow( row )
        mov     word [row], 0
.L5:
        mov     ax, [row]
        cmp     ax, 140
        jae     .L7                         ; unsigned <
        mov     al, [charlstn__wantOut]
        test    al, al
        jnz     .L7
        mov     ax, [row]
        mov     [charlstn__playRow__row], ax
        call    charlstn__playRow
.L6:
        inc     word [row]
        jmp     .L5
.L7:
; ---- newline()
        call    newline
.L2:
        jmp     .L1
.L3:
; ---- soundOff()
        call    charlstn__soundOff

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub putChar ====

putChar:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _dl = c
        mov     al, [putChar__c]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x21
        call    int21
        ret

; ============================================== sub putStr ====

putStr:
; ---- _ah = 0x09
        mov     byte [_ah], 9
; ---- _dx = at
        mov     ax, [putStr__at]
        mov     [_dx], ax
; ---- int 0x21
        call    int21
        ret

; ============================================== sub newline ====

newline:
; ---- putChar(13)
        mov     byte [putChar__c], 13
        call    putChar
; ---- putChar(10)
        mov     byte [putChar__c], 10
        call    putChar
        ret

; ============================================== u16 readKey ====

readKey:
; ---- _ah = 0x00
        mov     byte [_ah], 0
; ---- int 0x16
        call    int16
; ---- return _ax
        mov     ax, [_ax]
        mov     [readKey__ret], ax
        ret

; ============================================== bool keyPending ====

keyPending:
; ---- bool keyPending() => bdaKeyHead[0] != bdaKeyTail[0]
        mov     dx, 0x40                    ; segment of key__bdaKeyHead
        mov     es, dx
        mov     ax, [es:26]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     dx, 0x40                    ; segment of key__bdaKeyTail
        mov     es, dx
        mov     ax, [es:28]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        je      .L10                        ; unsigned !=
        mov     ax, 1
        jmp     .L11
.L10:
        xor     ax, ax
.L11:
        mov     [keyPending__ret], al       ; narrowed to bool
        ret

; ============================================== sub charlstn__line ====

charlstn__line:
; ---- putStr( at )
        mov     ax, [charlstn__line__at]
        mov     [putStr__at], ax
        call    putStr
; ---- newline()
        call    newline
        ret

; ============================================== sub charlstn__sayPhrase ====

charlstn__sayPhrase:
; ---- if ( row == 0 )   line( addr( p0 ) )
        mov     ax, [charlstn__sayPhrase__row]
        test    ax, ax
        jne     .L13                        ; unsigned ==
        mov     ax, p0                      ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L13:
; ---- if ( row == 6 )   line( addr( p1 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 6
        jne     .L16                        ; unsigned ==
        mov     ax, p1                      ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L16:
; ---- if ( row == 15 )  line( addr( p2 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 15
        jne     .L19                        ; unsigned ==
        mov     ax, p2                      ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L19:
; ---- if ( row == 24 )  line( addr( p3 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 24
        jne     .L22                        ; unsigned ==
        mov     ax, p3                      ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L22:
; ---- if ( row == 32 )  line( addr( p4 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 32
        jne     .L25                        ; unsigned ==
        mov     ax, p4                      ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L25:
; ---- if ( row == 38 )  line( addr( p5 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 38
        jne     .L28                        ; unsigned ==
        mov     ax, p5                      ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L28:
; ---- if ( row == 47 )  line( addr( p6 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 47
        jne     .L31                        ; unsigned ==
        mov     ax, p6                      ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L31:
; ---- if ( row == 61 )  line( addr( p7 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 61
        jne     .L34                        ; unsigned ==
        mov     ax, p7                      ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L34:
; ---- if ( row == 75 )  line( addr( p8 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 75
        jne     .L37                        ; unsigned ==
        mov     ax, p8                      ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L37:
; ---- if ( row == 81 )  line( addr( p9 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 81
        jne     .L40                        ; unsigned ==
        mov     ax, p9                      ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L40:
; ---- if ( row == 92 )  line( addr( p10 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 92
        jne     .L43                        ; unsigned ==
        mov     ax, p10                     ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L43:
; ---- if ( row == 103 ) line( addr( p11 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 103
        jne     .L46                        ; unsigned ==
        mov     ax, p11                     ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L46:
; ---- if ( row == 115 ) line( addr( p12 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 115
        jne     .L49                        ; unsigned ==
        mov     ax, p12                     ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L49:
; ---- if ( row == 123 ) line( addr( p13 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 123
        jne     .L52                        ; unsigned ==
        mov     ax, p13                     ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L52:
; ---- if ( row == 131 ) line( addr( p14 ) )
        mov     ax, [charlstn__sayPhrase__row]
        cmp     ax, 131
        jne     .L55                        ; unsigned ==
        mov     ax, p14                     ; link-time constant
        mov     [charlstn__line__at], ax
        call    charlstn__line
.L55:
        ret

; ============================================== sub charlstn__soundAt ====

charlstn__soundAt:
; ---- out8( pitMode, pitSquare )
        mov     ax, 182
        mov     dx, 67
        out     dx, al
; ---- out8( pitCh2, lo( divisor ) )
        mov     ax, [charlstn__soundAt__divisor]
        xor     ah, ah                      ; cast to u8
        mov     dx, 66
        out     dx, al
; ---- out8( pitCh2, hi( divisor ) )
        mov     ax, [charlstn__soundAt__divisor]
        mov     cl, 8                       ; 8086 has no shift-by-immediate
        shr     ax, cl                      ; unsigned >>
        xor     ah, ah                      ; cast to u8
        mov     dx, 66
        out     dx, al
; ---- out8( spkGate, in8( spkGate ) | spkOn )
        mov     dx, 97
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        or      ax, 3
        mov     dx, 97
        out     dx, al
        ret

; ============================================== sub charlstn__soundOff ====

charlstn__soundOff:
; ---- local sub soundOff => out8( spkGate, in8( spkGate ) & 0xFC )
        mov     dx, 97
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        and     ax, 252
        mov     dx, 97
        out     dx, al
        ret

; ============================================== bool charlstn__inRetrace ====

charlstn__inRetrace:
; ---- local bool inRetrace() => ( in8( vgaStatus ) & vgaVRetrace ) != 0
        mov     dx, 986
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        and     ax, 8
        test    ax, ax
        je      .L58                        ; unsigned !=
        mov     ax, 1
        jmp     .L59
.L58:
        xor     ax, ax
.L59:
        mov     [charlstn__inRetrace__ret], al; narrowed to bool
        ret

; ============================================== sub charlstn__waitFrame ====

charlstn__waitFrame:
; ---- while ( inRetrace() ) {}
.L61:
        call    charlstn__inRetrace
        mov     al, [charlstn__inRetrace__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jz      .L63
.L62:
        jmp     .L61
.L63:
; ---- while ( !inRetrace() ) {}
.L65:
        call    charlstn__inRetrace
        mov     al, [charlstn__inRetrace__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L67
.L66:
        jmp     .L65
.L67:
        ret

; ============================================== sub charlstn__keys ====

charlstn__keys:
; ---- while ( keyPending() ) {
.L69:
        call    keyPending
        mov     al, [keyPending__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L72
        jmp     .L71
.L72:
; ---- k = readKey()
        call    readKey
        mov     ax, [readKey__ret]
        mov     [charlstn__keys__k], ax
; ---- c = lo( k )
        xor     ah, ah                      ; cast to u8
        mov     [charlstn__keys__c], al     ; narrowed to u8
; ---- if ( c == 27 ) wantOut = true
        cmp     al, 27                      ; byte operands, no widening
        jne     .L73                        ; unsigned ==
        mov     byte [charlstn__wantOut], 1
.L73:
; ---- if ( ( c == '+' || c == '=' ) && pace > paceFast ) pace = pace - 1
        mov     al, [charlstn__keys__c]
        cmp     al, 43                      ; byte operands, no widening
        je      .L78                        ; unsigned ==
        mov     al, [charlstn__keys__c]
        cmp     al, 61                      ; byte operands, no widening
        jne     .L76                        ; unsigned ==
.L78:
        mov     al, [charlstn__pace]
        cmp     al, 3                       ; byte operands, no widening
        jbe     .L76                        ; unsigned >
        mov     al, [charlstn__pace]
        xor     ah, ah                      ; u8 -> u16
        dec     ax
        mov     [charlstn__pace], al        ; narrowed to u8
.L76:
; ---- if ( ( c == '-' || c == '_' ) && pace < paceSlow ) pace = pace + 1
        mov     al, [charlstn__keys__c]
        cmp     al, 45                      ; byte operands, no widening
        je      .L84                        ; unsigned ==
        mov     al, [charlstn__keys__c]
        cmp     al, 95                      ; byte operands, no widening
        jne     .L82                        ; unsigned ==
.L84:
        mov     al, [charlstn__pace]
        cmp     al, 8                       ; byte operands, no widening
        jae     .L82                        ; unsigned <
        mov     al, [charlstn__pace]
        xor     ah, ah                      ; u8 -> u16
        inc     ax
        mov     [charlstn__pace], al        ; narrowed to u8
.L82:
; ---- if ( c == ' ' ) {
        mov     al, [charlstn__keys__c]
        cmp     al, 32                      ; byte operands, no widening
        jne     .L88                        ; unsigned ==
; ---- soundOff()
        call    charlstn__soundOff
; ---- readKey()
        call    readKey
; ---- if ( sounding != 0 ) soundAt( sounding )
        mov     ax, [charlstn__sounding]
        test    ax, ax
        je      .L91                        ; unsigned !=
        mov     ax, [charlstn__sounding]
        mov     [charlstn__soundAt__divisor], ax
        call    charlstn__soundAt
.L91:
.L88:
.L70:
        jmp     .L69
.L71:
        ret

; ============================================== sub charlstn__playRow ====

charlstn__playRow:
; ---- sayPhrase( row )
        mov     ax, [charlstn__playRow__row]
        mov     [charlstn__sayPhrase__row], ax
        call    charlstn__sayPhrase
; ---- t = songTone[row]
        mov     ax, [charlstn__playRow__row]
        mov     bx, ax
        mov     al, [songTone + bx]
        mov     [charlstn__playRow__t], al  ; u8 -> u8, no widening
; ---- if ( t != tR ) {
        test    al, al
        je      .L94                        ; unsigned !=
; ---- sounding = toneDiv[t]
        mov     al, [charlstn__playRow__t]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [toneDiv + bx]
        mov     [charlstn__sounding], ax
; ---- soundAt( sounding )
        mov     [charlstn__soundAt__divisor], ax
        call    charlstn__soundAt
        jmp     .L95
.L94:
; ---- sounding = 0
        mov     word [charlstn__sounding], 0
; ---- soundOff()
        call    charlstn__soundOff
.L95:
; ---- frames = u8( songSpan[row] ) * pace
        mov     ax, [charlstn__playRow__row]
        mov     bx, ax
        mov     al, [songSpan + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bl, [charlstn__pace]
        xor     bh, bh                      ; u8 -> u16
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     [charlstn__playRow__frames], al; narrowed to u8
; ---- for ( u8 f = 0; f < frames && !wantOut; f++ ) {
        mov     byte [charlstn__playRow__f], 0
.L97:
        mov     al, [charlstn__playRow__f]
        cmp     al, [charlstn__playRow__frames]; byte operands, no widening
        jae     .L99                        ; unsigned <
        mov     al, [charlstn__wantOut]
        test    al, al
        jnz     .L99
; ---- if ( f == frames - 1 ) soundOff()
        mov     al, [charlstn__playRow__f]
        xor     ah, ah                      ; u8 -> u16
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [charlstn__playRow__frames]
        xor     ah, ah                      ; u8 -> u16
        dec     ax
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        jne     .L102                       ; unsigned ==
        call    charlstn__soundOff
.L102:
; ---- waitFrame()
        call    charlstn__waitFrame
; ---- keys()
        call    charlstn__keys
.L98:
        inc     byte [charlstn__playRow__f]
        jmp     .L97
.L99:
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int16:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x16
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

int21:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
row:            dw      0        ; u16
putChar__c:     db      0        ; u8
putStr__at:     dw      0        ; u16
readKey__ret:   dw      0        ; u16
keyPending__ret: db      0        ; bool
charlstn__line__at: dw      0        ; u16
charlstn__sayPhrase__row: dw      0        ; u16
charlstn__sounding: dw      0        ; u16
charlstn__soundAt__divisor: dw      0        ; u16
charlstn__inRetrace__ret: db      0        ; bool
charlstn__pace: db      5        ; u8 = 5
charlstn__wantOut: db      0        ; bool
charlstn__playRow__row: dw      0        ; u16
charlstn__keys__k: dw      0        ; u16
charlstn__keys__c: db      0        ; u8
charlstn__playRow__f: db      0        ; u8
charlstn__playRow__frames: db      0        ; u8
charlstn__playRow__t: db      0        ; u8

; ---- arrays ----
toneDiv:        dw      0, 4063, 3835, 3620, 3417, 3225, 3044, 2712, 2560, 2280, 2152, 2032        ; u16[12] const
songTone:       db      4, 0, 4, 5, 0, 5, 6, 0, 6, 6, 5, 6, 11, 0, 6, 6, 0, 11, 6, 0, 11, 6, 0,        ; u8[140] const
                db      8, 7, 9, 7, 6, 6, 7, 6, 5, 4, 0, 4, 5, 0, 5, 6, 0, 6, 6, 5, 6, 11, 0,
                db      11, 0, 7, 7, 7, 7, 6, 4, 0, 6, 6, 6, 6, 4, 3, 0, 7, 7, 7, 7, 6, 5, 0, 7,
                db      7, 7, 7, 6, 4, 4, 0, 4, 5, 0, 5, 6, 0, 6, 6, 5, 6, 11, 0, 6, 6, 0, 6, 6,
                db      6, 0, 11, 11, 10, 11, 6, 0, 11, 6, 0, 8, 8, 7, 9, 7, 6, 4, 8, 0, 8, 0,
                db      9, 9, 8, 9, 8, 0, 8, 0, 8, 9, 8, 9, 6, 0, 6, 0, 4, 6, 7, 7, 6, 4, 8, 0
songSpan:       db      4, 2, 10, 4, 2, 10, 4, 2, 2, 3, 1, 4, 4, 2, 10, 4, 2, 10, 4, 2, 10, 4,        ; u8[140] const
                db      2, 10, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 10, 4, 2, 10, 4, 2, 2, 3, 1, 4, 4,
                db      2, 10, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2,
                db      2, 2, 2, 2, 2, 4, 4, 2, 10, 4, 2, 10, 4, 2, 2, 3, 1, 4, 4, 2, 2, 2, 2,
                db      3, 1, 4, 2, 2, 3, 1, 4, 4, 2, 10, 4, 2, 6, 4, 2, 2, 2, 6, 4, 4, 2, 10,
                db      4, 4, 3, 1, 4, 4, 2, 10, 4, 2, 4, 2, 4, 4, 2, 10, 2, 2, 2, 2, 2, 2, 4,
                db      18, 14
sTitle:         db      'charlstn - The Original Charleston$'        ; u8[35] const
sCredit:        db      'words and music by Cecil Mack and Jimmy Johnson, 1923 - public domain$'        ; u8[70] const
sKeys:          db      '+ and - for tempo, space pauses, Esc quits$'        ; u8[43] const
p0:             db      'Charleston! Charleston!$'        ; u8[24] const
p1:             db      'Made in Carolina,$'        ; u8[18] const
p2:             db      'Some dance, some prance, I', 39, 'll say,$'        ; u8[35] const
p3:             db      'There', 39, 's nothing finer than the$'        ; u8[31] const
p4:             db      'Charleston, Charleston,$'        ; u8[24] const
p5:             db      'Lord, how you can shuffle,$'        ; u8[27] const
p6:             db      'Ev', 39, 'ry step you do leads to something new,$'        ; u8[42] const
p7:             db      'Man, I', 39, 'm telling you, it', 39, 's a lapazoo,$'        ; u8[38] const
p8:             db      'Buck dance, wing dance,$'        ; u8[24] const
p9:             db      'Will be a back number,$'        ; u8[23] const
p10:            db      'But the Charleston, the new Charleston,$'        ; u8[40] const
p11:            db      'That dance is surely a comer sometime,$'        ; u8[39] const
p12:            db      'You', 39, 'll dance it one time,$'        ; u8[26] const
p13:            db      'The dance called the Charleston,$'        ; u8[33] const
p14:            db      'Made in South Caroline!$'        ; u8[24] const

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     268        ; 12 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
