; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
modeGfx256:     equ     2
modeCount:      equ     3

; =========================================================== entry ====

__entry:
; ---- saveMode()
        call    saveMode
; ---- setMode( modeGfx256 )
        mov     byte [setMode__id], 2
        call    setMode
; ---- for( u16 i = 0; i < len( pixels ); i++ ){
        mov     word [i], 0
.L1:
        mov     ax, [i]
        cmp     ax, 64000
        jae     .L3                         ; unsigned <
; ---- pixels[i] = u8( nextRandom() )
        call    nextRandom
        mov     ax, [nextRandom__ret]
        xor     ah, ah                      ; cast to u8
        push    ax                          ; save value while computing the index
        mov     ax, [i]
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pixels
        mov     es, dx
        pop     ax
        mov     [es:bx], al
.L2:
        inc     word [i]
        jmp     .L1
.L3:
; ---- readKey()
        call    readKey
; ---- restoreMode()
        call    restoreMode

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== u16 readKey ====

readKey:
; ---- _ah = 0x00
        mov     byte [_ah], 0
; ---- int 0x16
        call    int16
; ---- return _ax
        mov     ax, [_ax]
        mov     [readKey__ret], ax
        ret

; ============================================== sub saveMode ====

saveMode:
; ---- _ah = 0x0F
        mov     byte [_ah], 15
; ---- int 0x10
        call    int10
; ---- savedMode = _al & 0x7F
        mov     al, [_al]
        xor     ah, ah                      ; u8 -> u16
        and     ax, 127
        mov     [mode__savedMode], al       ; narrowed to u8
        ret

; ============================================== sub restoreMode ====

restoreMode:
; ---- _ah = 0x00
        mov     byte [_ah], 0
; ---- _al = savedMode
        mov     al, [mode__savedMode]
        mov     [_al], al                   ; u8 -> u8, no widening
; ---- int 0x10
        call    int10
; ---- curW = 0
        mov     word [mode__curW], 0
; ---- curH = 0
        mov     word [mode__curH], 0
; ---- curElems = 0
        mov     word [mode__curElems], 0
; ---- curSeg = 0
        mov     word [mode__curSeg], 0
; ---- curElemBytes = 0
        mov     byte [mode__curElemBytes], 0
        ret

; ============================================== sub setMode ====

setMode:
; ---- _ah = 0x00
        mov     byte [_ah], 0
; ---- _al = screenMode[id].bios
        mov     al, [setMode__id]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [screenMode__bios + bx]
        mov     [_al], al                   ; u8 -> u8, no widening
; ---- int 0x10
        call    int10
; ---- if ( screenMode[id].smallFont != 0 ) {
        mov     al, [setMode__id]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [screenMode__smallFont + bx]
        test    al, al
        je      .L5                         ; unsigned !=
; ---- _ax = 0x1112
        mov     word [_ax], 4370
; ---- _bl = 0
        mov     byte [_bl], 0
; ---- int 0x10
        call    int10
.L5:
; ---- curSeg = screenMode[id].seg
        mov     al, [setMode__id]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [screenMode__seg + bx]
        mov     [mode__curSeg], ax
; ---- curElemBytes = screenMode[id].elemBytes
        mov     al, [setMode__id]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [screenMode__elemBytes + bx]
        mov     [mode__curElemBytes], al    ; u8 -> u8, no widening
; ---- if ( screenMode[id].elemBytes == 2 ) {
        mov     al, [setMode__id]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [screenMode__elemBytes + bx]
        cmp     al, 2                       ; byte operands, no widening
        jne     .L8                         ; unsigned ==
; ---- curW = bdaCols[0]
        mov     dx, 0x40                    ; segment of mode__bdaCols
        mov     es, dx
        mov     ax, [es:74]
        mov     [mode__curW], ax
; ---- curH = u16( bdaRows[0] ) + 1
        mov     dx, 0x40                    ; segment of mode__bdaRows
        mov     es, dx
        mov     al, [es:132]
        xor     ah, ah                      ; u8 -> u16
        inc     ax
        mov     [mode__curH], ax
        jmp     .L9
.L8:
; ---- curW = screenMode[id].nomW
        mov     al, [setMode__id]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [screenMode__nomW + bx]
        mov     [mode__curW], ax
; ---- curH = screenMode[id].nomH
        mov     al, [setMode__id]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [screenMode__nomH + bx]
        mov     [mode__curH], ax
.L9:
; ---- curElems = curW
        mov     ax, [mode__curW]
        mov     [mode__curElems], ax
        ret

; ============================================== u16 nextRandom ====

nextRandom:
; ---- randomSeed = randomSeed ^ (randomSeed << 7)
        mov     ax, [rand__randomSeed]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [rand__randomSeed]
        mov     cl, 7                       ; 8086 has no shift-by-immediate
        shl     ax, cl
        mov     bx, ax
        pop     ax
        xor     ax, bx
        mov     [rand__randomSeed], ax
; ---- randomSeed = randomSeed ^ (randomSeed >> 9)
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [rand__randomSeed]
        mov     cl, 9                       ; 8086 has no shift-by-immediate
        shr     ax, cl                      ; unsigned >>
        mov     bx, ax
        pop     ax
        xor     ax, bx
        mov     [rand__randomSeed], ax
; ---- randomSeed = randomSeed ^ (randomSeed << 8)
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [rand__randomSeed]
        mov     cl, 8                       ; 8086 has no shift-by-immediate
        shl     ax, cl
        mov     bx, ax
        pop     ax
        xor     ax, bx
        mov     [rand__randomSeed], ax
; ---- return randomSeed
        mov     [nextRandom__ret], ax
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int10:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x10
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

int16:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x16
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

int21:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
i:              dw      0        ; u16
readKey__ret:   dw      0        ; u16
mode__curW:     dw      0        ; u16
mode__curH:     dw      0        ; u16
mode__curElems: dw      0        ; u16
mode__curSeg:   dw      0        ; u16
mode__curElemBytes: db      0        ; u8
mode__savedMode: db      0        ; u8
setMode__id:    db      0        ; u8
rand__randomSeed: dw      42        ; u16 = 42
nextRandom__ret: dw      0        ; u16

; ---- arrays ----
screenMode__bios: db      3, 3, 19        ; u8[3]
screenMode__smallFont: db      0, 1, 0        ; u8[3]
screenMode__nomW: dw      0, 0, 320        ; u16[3]
screenMode__nomH: dw      0, 0, 200        ; u16[3]
screenMode__seg: dw      47104, 47104, 40960        ; u16[3]
screenMode__elemBytes: db      2, 2, 1        ; u8[3]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     262        ; 6 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
