; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
ioBase:         equ     10
ioZeroChar:     equ     48

; =========================================================== entry ====

__entry:
; ---- putNumber( add3( 1, 2, 3 ) )
        mov     byte [add3__a], 1
        mov     byte [add3__b], 2
        mov     byte [add3__c], 3
        call    add3
        mov     ax, [add3__ret]
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
; ---- putNumber( add3( a: 1, b: 2, c: 3 ) )
        mov     byte [add3__a], 1
        mov     byte [add3__b], 2
        mov     byte [add3__c], 3
        call    add3
        mov     ax, [add3__ret]
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
; ---- putNumber( add3( c: 3, a: 1, b: 2 ) )
        mov     byte [add3__a], 1
        mov     byte [add3__b], 2
        mov     byte [add3__c], 3
        call    add3
        mov     ax, [add3__ret]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- putNumber( add3( c: first(), a: second(), b: 0 ) )
        call    first
        mov     ax, [first__ret]
        push    ax                          ; argument evaluated before any is stored
        call    second
        mov     ax, [second__ret]
        push    ax                          ; argument evaluated before any is stored
        mov     byte [add3__b], 0
        pop     ax
        mov     [add3__a], al               ; narrowed to u8
        pop     ax
        mov     [add3__c], al               ; narrowed to u8
        call    add3
        mov     ax, [add3__ret]
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
; ---- putNumber( seq )
        mov     ax, [seq]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- box()
        call    box
; ---- putNumber( boxGap )
        mov     ax, [boxGap]
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
; ---- putNumber( boxCol )
        mov     ax, [boxCol]
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
; ---- box( col: 2 )
        mov     byte [box__col], 2
        call    box
; ---- putNumber( boxGap )
        mov     ax, [boxGap]
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
; ---- putNumber( boxCol )
        mov     ax, [boxCol]
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
; ---- box( 5 )
        mov     byte [box__gap], 5
        call    box
; ---- putNumber( boxGap )
        mov     ax, [boxGap]
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
; ---- putNumber( boxCol )
        mov     ax, [boxCol]
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
; ---- box()
        call    box
; ---- putNumber( boxGap )
        mov     ax, [boxGap]
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
; ---- putNumber( boxCol )
        mov     ax, [boxCol]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- boxed( gap: 4 ) {
        mov     byte [openBox__gap], 4
        call    openBox
; ---- putNumber( boxGap )
        mov     ax, [boxGap]
        mov     [putNumber__n], ax
        call    putNumber
; ---- }
        call    closeBox
; ---- space()
        call    space
; ---- putNumber( boxGap )
        mov     ax, [boxGap]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- putNumber( pad( 4 ) )
        mov     word [putNumber__n], 7
        call    putNumber
; ---- space()
        call    space
; ---- putNumber( pad( 4, by: 10 ) )
        mov     word [putNumber__n], 14
        call    putNumber
; ---- newline()
        call    newline
; ---- setTone()
        call    setTone
; ---- putNumber( u16( toneNow ) )
        mov     al, [toneNow]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
; ---- putNumber( u16( bits ) )
        mov     ax, [bits_]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub putChar ====

putChar:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _dl = c
        mov     al, [putChar__c]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x21
        call    int21
        ret

; ============================================== sub newline ====

newline:
; ---- putChar(13)
        mov     byte [putChar__c], 13
        call    putChar
; ---- putChar(10)
        mov     byte [putChar__c], 10
        call    putChar
        ret

; ============================================== sub space ====

space:
; ---- sub space => putChar(32)
        mov     byte [putChar__c], 32
        call    putChar
        ret

; ============================================== sub putNumber ====

putNumber:
; ---- if (n == 0) {
        mov     ax, [putNumber__n]
        test    ax, ax
        jne     .L1                         ; unsigned ==
; ---- putChar(ioZeroChar)
        mov     byte [putChar__c], 48
        call    putChar
; ---- return
        ret
.L1:
; ---- for (i = 0; n > 0; i++) {
        mov     byte [putNumber__i], 0
.L4:
        mov     ax, [putNumber__n]
        test    ax, ax
        jbe     .L6                         ; unsigned >
; ---- digits[i] = u8(n % ioBase) + ioZeroChar
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        add     ax, 48
        mov     bl, [putNumber__i]
        xor     bh, bh                      ; u8 -> u16
        mov     [putNumber__digits + bx], al
; ---- n /= ioBase
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     [putNumber__n], ax
.L5:
        inc     byte [putNumber__i]
        jmp     .L4
.L6:
; ---- for (; i > 0; i--) {
.L8:
        mov     al, [putNumber__i]
        test    al, al
        jbe     .L10                        ; unsigned >
; ---- putChar(digits[i - 1])
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        dec     ax
        mov     bx, ax
        mov     al, [putNumber__digits + bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
.L9:
        dec     byte [putNumber__i]
        jmp     .L8
.L10:
        ret

; ============================================== u16 add3 ====

add3:
; ---- return u16( a ) * 100 + u16( b ) * 10 + u16( c )
        mov     al, [add3__a]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 100
        mul     bx                          ; low 16 bits are sign-agnostic
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [add3__b]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 10
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     bx, ax
        pop     ax
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [add3__c]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [add3__ret], ax
        ret

; ============================================== u16 first ====

first:
; ---- seq = seq * 10 + 1
        mov     ax, [seq]
        mov     bx, 10
        mul     bx                          ; low 16 bits are sign-agnostic
        inc     ax
        mov     [seq], ax
; ---- return 1
        mov     word [first__ret], 1
        ret

; ============================================== u16 second ====

second:
; ---- seq = seq * 10 + 2
        mov     ax, [seq]
        mov     bx, 10
        mul     bx                          ; low 16 bits are sign-agnostic
        add     ax, 2
        mov     [seq], ax
; ---- return 2
        mov     word [second__ret], 2
        ret

; ============================================== sub box ====

box:
; ---- boxGap = gap
        mov     al, [box__gap]
        xor     ah, ah                      ; u8 -> u16
        mov     [boxGap], ax
; ---- boxCol = col
        mov     al, [box__col]
        xor     ah, ah                      ; u8 -> u16
        mov     [boxCol], ax
        mov     byte [box__gap], 1          ; defaults restored on the way out
        mov     byte [box__col], 7          ; col = 7
        ret

; ============================================== sub openBox ====

openBox:
; ---- boxGap = gap
        mov     al, [openBox__gap]
        xor     ah, ah                      ; u8 -> u16
        mov     [boxGap], ax
        mov     byte [openBox__gap], 1      ; defaults restored on the way out
        ret

; ============================================== sub closeBox ====

closeBox:
; ---- boxGap = 9
        mov     word [boxGap], 9
        ret

; ============================================== sub setTone ====

setTone:
; ---- sub setTone( tone level = 21 ) => toneNow = level
        mov     al, [setTone__level]
        mov     [toneNow], al               ; u8 -> u8, no widening
        mov     byte [setTone__level], 21   ; defaults restored on the way out
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
putChar__c:     db      0        ; u8
putNumber__n:   dw      0        ; u16
add3__a:        db      0        ; u8
add3__b:        db      0        ; u8
add3__c:        db      0        ; u8
add3__ret:      dw      0        ; u16
seq:            dw      0        ; u16
first__ret:     dw      0        ; u16
second__ret:    dw      0        ; u16
boxGap:         dw      0        ; u16
boxCol:         dw      0        ; u16
box__gap:       db      1        ; u8 = 1
box__col:       db      7        ; u8 = 7
openBox__gap:   db      1        ; u8 = 1
toneNow:        db      0        ; u8
setTone__level: db      21        ; u8 = 21
bits_:          dw      384        ; i16 = 384
putNumber__i:   db      0        ; u8

; ---- arrays ----
putNumber__digits: times 5 db 0        ; u8[5]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     264        ; 8 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
