; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
ioBase:         equ     10
ioZeroChar:     equ     48

; =========================================================== entry ====

__entry:
; ---- libRun()
        call    libRun
; ---- putNumber( ticks )
        mov     ax, [ticks]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub putChar ====

putChar:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _dl = c
        mov     al, [putChar__c]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x21
        call    int21
        ret

; ============================================== sub newline ====

newline:
; ---- putChar(13)
        mov     byte [putChar__c], 13
        call    putChar
; ---- putChar(10)
        mov     byte [putChar__c], 10
        call    putChar
        ret

; ============================================== sub putNumber ====

putNumber:
; ---- if (n == 0) {
        mov     ax, [putNumber__n]
        test    ax, ax
        jne     .L1                         ; unsigned ==
; ---- putChar(ioZeroChar)
        mov     byte [putChar__c], 48
        call    putChar
; ---- return
        ret
.L1:
; ---- for (i = 0; n > 0; i++) {
        mov     byte [putNumber__i], 0
.L4:
        mov     ax, [putNumber__n]
        test    ax, ax
        jbe     .L6                         ; unsigned >
; ---- digits[i] = u8(n % ioBase) + ioZeroChar
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        add     ax, 48
        mov     bl, [putNumber__i]
        xor     bh, bh                      ; u8 -> u16
        mov     [putNumber__digits + bx], al
; ---- n /= ioBase
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     [putNumber__n], ax
.L5:
        inc     byte [putNumber__i]
        jmp     .L4
.L6:
; ---- for (; i > 0; i--) {
.L8:
        mov     al, [putNumber__i]
        test    al, al
        jbe     .L10                        ; unsigned >
; ---- putChar(digits[i - 1])
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        dec     ax
        mov     bx, ax
        mov     al, [putNumber__digits + bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
.L9:
        dec     byte [putNumber__i]
        jmp     .L8
.L10:
        ret

; ============================================== u16 weigh ====

weigh:
; ---- u16 weigh( u16 v, a16 at ) => v * 3 + peek8( at )
        mov     ax, [weigh__v]
        mov     bx, 3
        mul     bx                          ; low 16 bits are sign-agnostic
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [weigh__at]
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [weigh__ret], ax
        ret

; ============================================== sub libRun ====

libRun:
; ---- for ( u16 i = 0; i < len( steps ); i++ ) {
        mov     word [libRun__i], 0
.L12:
        mov     ax, [libRun__i]
        cmp     ax, 4
        jae     .L14                        ; unsigned <
; ---- report( weigh( i, addr( steps ) + i ) )
        mov     ax, [libRun__i]
        mov     [weigh__v], ax
        mov     ax, e_lib__steps            ; link-time constant
        mov     bx, [libRun__i]
        add     ax, bx
        mov     [weigh__at], ax
        call    weigh
        mov     ax, [weigh__ret]
        mov     [report__value], ax
        call    report
; ---- tick()
        call    tick
.L13:
        inc     word [libRun__i]
        jmp     .L12
.L14:
        ret

; ============================================== sub report ====

report:
; ---- putNumber( value )
        mov     ax, [report__value]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
        ret

; ============================================== sub tick ====

tick:
; ---- ticks++
        inc     word [ticks]
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
putChar__c:     db      0        ; u8
putNumber__n:   dw      0        ; u16
weigh__v:       dw      0        ; u16
weigh__at:      dw      0        ; u16
weigh__ret:     dw      0        ; u16
ticks:          dw      0        ; u16
report__value:  dw      0        ; u16
putNumber__i:   db      0        ; u8
libRun__i:      dw      0        ; u16

; ---- arrays ----
e_lib__steps:   db      1, 2, 3, 4        ; u8[4] const
putNumber__digits: times 5 db 0        ; u8[5]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     264        ; 8 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
