; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
ioBase:         equ     10
ioZeroChar:     equ     48

; =========================================================== entry ====

__entry:
; ---- for ( i = 0; i < 3; i++ ) {
        mov     word [i], 0
.L1:
        mov     ax, [i]
        cmp     ax, 3
        jae     .L3                         ; unsigned <
; ---- putNumber( mob[i].x )
        mov     ax, [i]
        mov     bx, ax
        mov     al, [mob__x + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( mob[i].hp )
        mov     ax, [i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [mob__hp + bx]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
.L2:
        inc     word [i]
        jmp     .L1
.L3:
; ---- putNumber( u16( mob[0].drift == -1 ) )
        mov     al, [mob__drift]
        cmp     al, -1                      ; byte operands, no widening
        jne     .L5                         ; signed ==
        mov     ax, 1
        jmp     .L6
.L5:
        xor     ax, ax
.L6:
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( u16( mob[1].drift == 0 ) )
        mov     al, [mob__drift + 1]
        test    al, al
        jne     .L8                         ; signed ==
        mov     ax, 1
        jmp     .L9
.L8:
        xor     ax, ax
.L9:
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( u16( mob[2].drift == 1 ) )
        mov     al, [mob__drift + 2]
        cmp     al, 1                       ; byte operands, no widening
        jne     .L11                        ; signed ==
        mov     ax, 1
        jmp     .L12
.L11:
        xor     ax, ax
.L12:
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- putNumber( u16( mob[0].alive ) )
        mov     al, [mob__alive]
        xor     ah, ah                      ; bool -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( u16( mob[1].alive ) )
        mov     al, [mob__alive + 1]
        xor     ah, ah                      ; bool -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( u16( mob[2].alive ) )
        mov     al, [mob__alive + 2]
        xor     ah, ah                      ; bool -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- for ( i = 0; i < 3; i++ ) {
        mov     word [i], 0
.L14:
        mov     ax, [i]
        cmp     ax, 3
        jae     .L16                        ; unsigned <
; ---- putNumber( pal[i].r )
        mov     ax, [i]
        mov     bx, ax
        mov     al, [pal__r + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( pal[i].g )
        mov     ax, [i]
        mov     bx, ax
        mov     al, [pal__g + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
.L15:
        inc     word [i]
        jmp     .L14
.L16:
; ---- putNumber( part[0].live )
        mov     al, [part__live]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( part[1].age )
        mov     al, [part__age + 1]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- putNumber( player.x )
        mov     al, [player__x]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( player.hp )
        mov     ax, [player__hp]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- putNumber( u16( ball.x == -5 ) )
        mov     ax, [ball__x]
        cmp     ax, -5
        jne     .L18                        ; signed ==
        mov     ax, 1
        jmp     .L19
.L18:
        xor     ax, ax
.L19:
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( ball.y )
        mov     ax, [ball__y]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub putChar ====

putChar:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _dl = c
        mov     al, [putChar__c]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x21
        call    int21
        ret

; ============================================== sub newline ====

newline:
; ---- putChar(13)
        mov     byte [putChar__c], 13
        call    putChar
; ---- putChar(10)
        mov     byte [putChar__c], 10
        call    putChar
        ret

; ============================================== sub putNumber ====

putNumber:
; ---- if (n == 0) {
        mov     ax, [putNumber__n]
        test    ax, ax
        jne     .L21                        ; unsigned ==
; ---- putChar(ioZeroChar)
        mov     byte [putChar__c], 48
        call    putChar
; ---- return
        ret
.L21:
; ---- for (i = 0; n > 0; i++) {
        mov     byte [putNumber__i], 0
.L24:
        mov     ax, [putNumber__n]
        test    ax, ax
        jbe     .L26                        ; unsigned >
; ---- digits[i] = u8(n % ioBase) + ioZeroChar
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        add     ax, 48
        mov     bl, [putNumber__i]
        xor     bh, bh                      ; u8 -> u16
        mov     [putNumber__digits + bx], al
; ---- n /= ioBase
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     [putNumber__n], ax
.L25:
        inc     byte [putNumber__i]
        jmp     .L24
.L26:
; ---- for (; i > 0; i--) {
.L28:
        mov     al, [putNumber__i]
        test    al, al
        jbe     .L30                        ; unsigned >
; ---- putChar(digits[i - 1])
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        dec     ax
        mov     bx, ax
        mov     al, [putNumber__digits + bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
.L29:
        dec     byte [putNumber__i]
        jmp     .L28
.L30:
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
putChar__c:     db      0        ; u8
putNumber__n:   dw      0        ; u16
player__x:      db      7        ; u8 = 7
player__hp:     dw      250        ; u16 = 250
ball__x:        dw      65531        ; i16 = -5
ball__y:        dw      12        ; u16 = 12
i:              dw      0        ; u16
putNumber__i:   db      0        ; u8

; ---- arrays ----
mob__x:         db      10, 30, 50        ; u8[3]
mob__drift:     db      -1, 0, 1        ; i8[3]
mob__hp:        dw      300, 400, 500        ; u16[3]
mob__alive:     db      1, 0, 0        ; bool[3]
pal__r:         db      0, 128, 255        ; u8[3]
pal__g:         db      1, 64, 254        ; u8[3]
part__live:     db      1, 1        ; u8[2]
part__age:      times 2 db 0        ; u8[2]
putNumber__digits: times 5 db 0        ; u8[5]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     260        ; 4 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
