; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; =========================================================== entry ====

__entry:
; ---- _ah = 0x3D
        mov     byte [_ah], 61
; ---- _al = 0
        mov     byte [_al], 0
; ---- _dx = 0
        mov     word [_dx], 0
; ---- int 0x21
        call    int21
; ---- failed = _cf
        mov     al, [_cf]
        mov     [failed], al                ; bool -> bool, no widening
; ---- if( _cf ){
        mov     al, [_cf]
        test    al, al
        jz      .L1
; ---- out = 1
        mov     byte [out], 1
.L1:
; ---- if( !_cf && failed ){
        mov     al, [_cf]
        test    al, al
        jnz     .L4
        mov     al, [failed]
        test    al, al
        jz      .L4
; ---- out = 2
        mov     byte [out], 2
.L4:
; ---- out = u8( failed ) + u8( _cf )
        mov     al, [failed]
        xor     ah, ah                      ; bool -> u16
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [_cf]
        xor     ah, ah                      ; bool -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [out], al                   ; narrowed to u8

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pushf
        pop     ax
        and     al, 1                       ; carry is bit 0
        mov     [_cf], al
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0
_cf:            db      0

; ---- variables ----
failed:         db      0        ; bool
out:            db      0        ; u8

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     258        ; 2 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
