; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; =========================================================== entry ====

__entry:
; ---- paint()
        call    paint

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub put ====

put:
; ---- total = total + y + peek8( at )
        mov     ax, [total]
        mov     bx, [put__y]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [put__at]
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [total], ax
        ret

; ============================================== sub paint ====

paint:
; ---- for ( u16 i = 0; i < 4; i++ ) {
        mov     word [paint__i], 0
.L1:
        mov     ax, [paint__i]
        cmp     ax, 4
        jae     .L3                         ; unsigned <
; ---- put( cell( i ), addr( line ) + i )
        mov     ax, [paint__i]
        mov     [cell__i], ax
        call    cell
        mov     al, [cell__ret]
        xor     ah, ah                      ; u8 -> u16
        push    ax                          ; argument evaluated before any is stored
        mov     ax, line                    ; link-time constant
        mov     bx, [paint__i]
        add     ax, bx
        mov     [put__at], ax
        pop     ax
        mov     [put__y], ax
        call    put
.L2:
        inc     word [paint__i]
        jmp     .L1
.L3:
; ---- flush()
        call    flush
        ret

; ============================================== u8 cell ====

cell:
; ---- u8 cell( u16 i ) => line[ i ] * 2
        mov     ax, [cell__i]
        mov     bx, ax
        mov     al, [line + bx]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; * 2 is << 1
        mov     [cell__ret], al             ; narrowed to u8
        ret

; ============================================== sub flush ====

flush:
; ---- total = total * 2
        mov     ax, [total]
        shl     ax, 1                       ; * 2 is << 1
        mov     [total], ax
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
total:          dw      0        ; u16
put__y:         dw      0        ; u16
put__at:        dw      0        ; u16
cell__i:        dw      0        ; u16
cell__ret:      db      0        ; u8
paint__i:       dw      0        ; u16

; ---- arrays ----
line:           db      3, 1, 4, 1        ; u8[4]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     264        ; 8 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
