; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
pitHz:          equ     1193182

; =========================================================== entry ====

__entry:
; ---- for ( k = 0; k < len( gamma ); k++ ) total = total + gamma[ k ]
        mov     word [k], 0
.L1:
        mov     ax, [k]
        cmp     ax, 32
        jae     .L3                         ; unsigned <
        mov     ax, [total]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [k]
        mov     bx, ax
        mov     al, [gamma + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [total], ax
.L2:
        inc     word [k]
        jmp     .L1
.L3:
; ---- for ( k = 0; k < len( harmonic ); k++ ) total = total + harmonic[ k ]
        mov     word [k], 0
.L5:
        mov     ax, [k]
        cmp     ax, 4
        jae     .L7                         ; unsigned <
        mov     ax, [total]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [k]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [harmonic + bx]
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [total], ax
.L6:
        inc     word [k]
        jmp     .L5
.L7:
; ---- for ( k = 0; k < len( evens ); k++ ) total = total + evens[ k ]
        mov     word [k], 0
.L9:
        mov     ax, [k]
        cmp     ax, 6
        jae     .L11                        ; unsigned <
        mov     ax, [total]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [k]
        mov     bx, ax
        mov     al, [evens + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [total], ax
.L10:
        inc     word [k]
        jmp     .L9
.L11:
; ---- for ( k = 0; k < 3; k++ ) total = total + mob[ k ].x
        mov     word [k], 0
.L13:
        mov     ax, [k]
        cmp     ax, 3
        jae     .L15                        ; unsigned <
        mov     ax, [total]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [k]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [mob__x + bx]
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [total], ax
.L14:
        inc     word [k]
        jmp     .L13
.L15:
; ---- total = total + u16( raw i16( wave[ 4 ] ) ) + u16( ramp[ 3 ] ) + buffer[ 0 ]
        mov     ax, [total]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [wave + 8]
        mov     bx, ax
        pop     ax
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [ramp + 3]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [buffer]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [total], ax

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
total:          dw      0        ; u16
k:              dw      0        ; u16

; ---- arrays ----
gamma:          db      0, 0, 0, 2, 3, 5, 8, 11, 15, 19, 23, 28, 33, 39, 46, 52, 60, 68, 76, 84,        ; u8[32] const
                db      94, 103, 113, 124, 135, 147, 159, 171, 184, 197, 211, 226
wave:           dw      -256, -128, 0, 128, 256        ; i16[5] const
harmonic:       dw      5423, 2711, 1807, 1355        ; u16[4] const
ramp:           db      0, 21, 42, 63        ; u8[4] const
evens:          db      0, 2, 4, 6, 8, 10        ; u8[6] const
buffer:         db      3, 2, 1, 0        ; u8[4]
mob__x:         dw      0, 100, 200        ; u16[3]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     258        ; 2 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
