; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; =========================================================== entry ====

__entry:
; ---- out8( 0x3C4, 2 )                  // constant port, constant value
        mov     ax, 2
        mov     dx, 964
        out     dx, al
; ---- out8( 0x3C4, b )                  // byte value: the no-widening path
        mov     al, [b]
        mov     dx, 964
        out     dx, al
; ---- out8( port, b )                   // computed port
        mov     ax, [port]
        push    ax                          ; save the port while the value is computed
        mov     al, [b]
        pop     dx
        out     dx, al
; ---- out8( port + 1, b )
        mov     ax, [port]
        inc     ax
        push    ax                          ; save the port while the value is computed
        mov     al, [b]
        pop     dx
        out     dx, al
; ---- out8( portOf(), 3 )               // a fn call in the port
        call    portOf
        mov     ax, [portOf__ret]
        push    ax                          ; save the port while the value is computed
        mov     ax, 3
        pop     dx
        out     dx, al
; ---- out8( port, u8( n * 3 ) )         // a multiply in the value, which clobbers DX
        mov     ax, [port]
        push    ax                          ; save the port while the value is computed
        mov     ax, [n]
        mov     bx, 3
        mul     bx                          ; low 16 bits are sign-agnostic
        xor     ah, ah                      ; cast to u8
        pop     dx
        out     dx, al
; ---- out16( 0x3C4, 0x0F02 )            // index and data in one instruction
        mov     ax, 3842
        mov     dx, 964
        out     dx, ax
; ---- out16( port, w )
        mov     ax, [port]
        push    ax                          ; save the port while the value is computed
        mov     ax, [w]
        pop     dx
        out     dx, ax
; ---- out16( port, n + 1 )
        mov     ax, [port]
        push    ax                          ; save the port while the value is computed
        mov     ax, [n]
        inc     ax
        pop     dx
        out     dx, ax
; ---- b = in8( 0x3DA )                  // byte to byte, no widening
        mov     dx, 986
        in      al, dx
        mov     [b], al                     ; u8 -> u8, no widening
; ---- w = in16( 0x3CC )
        mov     dx, 972
        in      ax, dx
        mov     [w], ax
; ---- w = in8( 0x3DA )                  // widens, since the target is a word
        mov     dx, 986
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        mov     [w], ax
; ---- b = in8( port )                   // computed port
        mov     ax, [port]
        mov     dx, ax
        in      al, dx
        mov     [b], al                     ; u8 -> u8, no widening
; ---- w = in8( 0x3DA ) + in8( 0x3C4 )   // arithmetic over reads widens as usual
        mov     dx, 986
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        push    ax                          ; save lhs: rhs is not a leaf
        mov     dx, 964
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [w], ax
; ---- b = u8( in16( 0x3CC ) )
        mov     dx, 972
        in      ax, dx
        mov     [b], al                     ; u16 -> u8, no widening
; ---- flag = in8( 0x3DA ) != 0          // a comparison, so the bool rule is satisfied
        mov     dx, 986
        in      al, dx
        test    al, al
        je      .L1                         ; unsigned !=
        mov     ax, 1
        jmp     .L2
.L1:
        xor     ax, ax
.L2:
        mov     [flag], al                  ; narrowed to bool
; ---- if ( in8( 0x3DA ) ) n = 1
        mov     dx, 986
        in      al, dx
        test    al, al
        jz      .L4
        mov     word [n], 1
.L4:
; ---- while ( in8( 0x3DA ) == 9 ) n++
.L7:
        mov     dx, 986
        in      al, dx
        cmp     al, 9                       ; byte operands, no widening
        jne     .L9                         ; unsigned ==
        inc     word [n]
.L8:
        jmp     .L7
.L9:
; ---- if ( in8( 0x3DA ) == 8 ) n = 2
        mov     dx, 986
        in      al, dx
        cmp     al, 8                       ; byte operands, no widening
        jne     .L11                        ; unsigned ==
        mov     word [n], 2
.L11:
; ---- out8( 0x3C5, in8( 0x3C5 ) )
        mov     dx, 965
        in      al, dx
        mov     dx, 965
        out     dx, al
; ---- poke8( addr( b ), in8( 0x3DA ) )
        mov     ax, b                       ; link-time constant
        push    ax                          ; save the address while the value is computed
        mov     dx, 986
        in      al, dx
        pop     bx
        mov     [bx], al

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== u16 portOf ====

portOf:
; ---- u16 portOf() => 0x3C4
        mov     word [portOf__ret], 964
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
b:              db      0        ; u8
w:              dw      0        ; u16
port:           dw      0        ; u16
n:              dw      0        ; u16
flag:           db      0        ; bool
portOf__ret:    dw      0        ; u16

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     260        ; 4 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
