; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
privates__hiddenLimit: equ     99
ok_local__hiddenLimit: equ     2

; =========================================================== entry ====

__entry:
; ---- total = visible() + hiddenHelper() + shared + alsoShared + hiddenLimit + frozen[0] + tag[0]
        call    visible
        mov     ax, [visible__ret]
        push    ax                          ; save lhs: rhs is not a leaf
        call    ok_local__hiddenHelper
        mov     ax, [ok_local__hiddenHelper__ret]
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     bx, [shared]
        add     ax, bx
        mov     bx, [ok_local__alsoShared]
        add     ax, bx
        add     ax, 2
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [ok_local__frozen]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [ok_local__tag]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [total], ax
; ---- touch()
        call    ok_local__touch

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== u16 privates__hiddenHelper ====

privates__hiddenHelper:
; ---- local u16 hiddenHelper() => hidden + hiddenLimit
        mov     ax, [privates__hidden]
        add     ax, 99
        mov     [privates__hiddenHelper__ret], ax
        ret

; ============================================== u16 visible ====

visible:
; ---- u16 visible() => hiddenHelper()
        call    privates__hiddenHelper
        mov     ax, [privates__hiddenHelper__ret]
        mov     [visible__ret], ax
        ret

; ============================================== u16 ok_local__hiddenHelper ====

ok_local__hiddenHelper:
; ---- local u16 hiddenHelper() => hidden
        mov     ax, [ok_local__hidden]
        mov     [ok_local__hiddenHelper__ret], ax
        ret

; ============================================== sub ok_local__touch ====

ok_local__touch:
; ---- buf[0] = 1
        mov     byte [ok_local__buf], 1
; ---- pool[0].x = 2
        mov     byte [ok_local__pool__x], 2
; ---- screen[0] = 3
        mov     dx, 0xB800                  ; segment of ok_local__screen
        mov     es, dx
        mov     byte [es:0], 3
; ---- half[1] = 4
        mov     byte [ok_local__half + 1], 4
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
privates__hidden: dw      7        ; u16 = 7
privates__hiddenHelper__ret: dw      0        ; u16
visible__ret:   dw      0        ; u16
ok_local__hidden: dw      1        ; u16 = 1
ok_local__hiddenHelper__ret: dw      0        ; u16
shared:         dw      5        ; u16 = 5
ok_local__alsoShared: dw      6        ; u16 = 6
total:          dw      0        ; u16

; ---- arrays ----
ok_local__buf:  times 4 db 0        ; u8[4]
ok_local__tag:  db      'hi$'        ; u8[3] const
ok_local__pool__x: times 4 db 0        ; u8[4]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     262        ; 6 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view

; =========================================================== views ====
; No storage: each is a name for an offset into something else.

ok_local__half: equ     ok_local__buf        ; u8[2]
ok_local__frozen: equ     ok_local__buf + 2        ; u8[2] const
