; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; =========================================================== entry ====

__entry:
; ---- at = addr( names[1] )
        mov     ax, ok_nested_local__names__1; link-time constant
        mov     [at_], ax
; ---- at = addr( names[i] )
        mov     ax, [i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [ok_nested_local__names + bx]
        mov     [at_], ax
; ---- b = names[0][1]
        mov     al, [ok_nested_local__names__0 + 1]
        mov     [b], al                     ; u8 -> u8, no widening
; ---- b = names[i][1]
        mov     ax, [i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [ok_nested_local__names + bx]
        mov     bx, ax                      ; the child
        mov     al, [bx + 1]
        mov     [b], al                     ; u8 -> u8, no widening
; ---- i = len( names[i] )
        mov     ax, [i]
        mov     bx, ax
        mov     al, [ok_nested_local__names__len + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [i], ax
; ---- i = len( names[0] )
        mov     word [i], 4

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
i:              dw      0        ; u16
at_:            dw      0        ; u16
b:              db      0        ; u8

; ---- arrays ----
ok_nested_local__names__0: db      'one$'        ; u8[4] const
ok_nested_local__names__1: db      'two$'        ; u8[4] const
ok_nested_local__names__len: db      4, 4        ; u8[2] const
ok_nested_local__names: dw      ok_nested_local__names__0, ok_nested_local__names__1        ; u16[2] const

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     256        ; 0 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
