; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; =========================================================== entry ====

__entry:
; ---- at = addr( bytes )
        mov     ax, bytes                   ; link-time constant
        mov     [at_], ax
; ---- poke8( at, 1 )                    // constant value: an immediate in the store
        mov     bx, ax
        mov     byte [bx], 1
; ---- poke8( at + i, b )                // both sides computed
        mov     ax, [at_]
        mov     bx, [i]
        add     ax, bx
        push    ax                          ; save the address while the value is computed
        mov     al, [b]
        pop     bx
        mov     [bx], al
; ---- poke8( addressOf(), 2 )           // a fn call in the address
        call    addressOf
        mov     ax, [addressOf__ret]
        mov     bx, ax
        mov     byte [bx], 2
; ---- poke8( at, u8( w ) )
        mov     ax, [at_]
        push    ax                          ; save the address while the value is computed
        mov     ax, [w]
        xor     ah, ah                      ; cast to u8
        pop     bx
        mov     [bx], al
; ---- poke16( at, 1000 )
        mov     ax, [at_]
        mov     bx, ax
        mov     word [bx], 1000
; ---- poke16( at + i * 2, w )
        mov     ax, [at_]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [i]
        shl     ax, 1                       ; * 2 is << 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        push    ax                          ; save the address while the value is computed
        mov     ax, [w]
        pop     bx
        mov     [bx], ax
; ---- poke8( at, peek8( at + 1 ) )      // the memcpy shape: byte in, byte out
        mov     ax, [at_]
        push    ax                          ; save the address while the value is computed
        mov     ax, [at_]
        inc     ax
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        pop     bx
        mov     [bx], al
; ---- poke16( at, peek16( at + 2 ) )
        mov     ax, [at_]
        push    ax                          ; save the address while the value is computed
        mov     ax, [at_]
        add     ax, 2
        mov     bx, ax
        mov     ax, [bx]                    ; peek16 - unchecked, by design
        pop     bx
        mov     [bx], ax
; ---- b = peek8( at )
        mov     ax, [at_]
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        mov     [b], al                     ; u8 -> u8, no widening
; ---- w = peek16( at + i )
        mov     ax, [at_]
        mov     bx, [i]
        add     ax, bx
        mov     bx, ax
        mov     ax, [bx]                    ; peek16 - unchecked, by design
        mov     [w], ax
; ---- w = peek8( at ) + peek8( at + 1 ) // arithmetic over peeks widens as usual
        mov     ax, [at_]
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        xor     ah, ah                      ; u8 -> u16
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [at_]
        inc     ax
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [w], ax
; ---- b = u8( peek16( at ) )
        mov     ax, [at_]
        mov     bx, ax
        mov     ax, [bx]                    ; peek16 - unchecked, by design
        mov     [b], al                     ; u16 -> u8, no widening
; ---- flag = peek8( at ) != 0           // a comparison, so the bool rule is satisfied
        mov     ax, [at_]
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        test    al, al
        je      .L1                         ; unsigned !=
        mov     ax, 1
        jmp     .L2
.L1:
        xor     ax, ax
.L2:
        mov     [flag], al                  ; narrowed to bool
; ---- if ( peek8( at ) ) one = 1
        mov     ax, [at_]
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        test    al, al
        jz      .L4
        mov     byte [one], 1
.L4:
; ---- while ( peek8( at ) == '$' ) i++
.L7:
        mov     ax, [at_]
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        cmp     al, 36                      ; byte operands, no widening
        jne     .L9                         ; unsigned ==
        inc     word [i]
.L8:
        jmp     .L7
.L9:
; ---- if ( peek8( at ) == 65 ) one = 2
        mov     ax, [at_]
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        cmp     al, 65                      ; byte operands, no widening
        jne     .L11                        ; unsigned ==
        mov     byte [one], 2
.L11:
; ---- poke8( addr( one ), 3 )
        mov     ax, one                     ; link-time constant
        mov     bx, ax
        mov     byte [bx], 3
; ---- poke16( addr( words ) + 2, 4 )
        mov     ax, words                   ; link-time constant
        add     ax, 2
        mov     bx, ax
        mov     word [bx], 4
; ---- poke8( addr( _heap ), 5 )
        mov     ax, _heap                   ; link-time constant
        mov     bx, ax
        mov     byte [bx], 5

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== u16 addressOf ====

addressOf:
; ---- a16 addressOf() => addr( bytes )
        mov     ax, bytes                   ; link-time constant
        mov     [addressOf__ret], ax
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
one:            db      0        ; u8
at_:            dw      0        ; u16
i:              dw      0        ; u16
b:              db      0        ; u8
w:              dw      0        ; u16
flag:           db      0        ; bool
addressOf__ret: dw      0        ; u16

; ---- arrays ----
bytes:          times 8 db 0        ; u8[8]
words:          times 4 dw 0        ; u16[4]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     260        ; 4 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
