; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
one:            equ     256

; =========================================================== entry ====

__entry:
; ---- sameScale()
        call    sameScale
; ---- counts()
        call    counts
; ---- constants()
        call    constants
; ---- throughARoutine()
        call    throughARoutine
; ---- eightBit()
        call    eightBit
; ---- throughStorage()
        call    throughStorage

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub sameScale ====

sameScale:
; ---- scale = scale + height
        mov     ax, [scale]
        mov     bx, [height]
        add     ax, bx
        mov     [scale], ax
; ---- scale = scale - height
        mov     bx, [height]
        sub     ax, bx
        mov     [scale], ax
; ---- over = scale < height
        mov     bx, [height]
        cmp     ax, bx
        jge     .L1                         ; signed <
        mov     ax, 1
        jmp     .L2
.L1:
        xor     ax, ax
.L2:
        mov     [over], al                  ; narrowed to bool
        ret

; ============================================== sub counts ====

counts:
; ---- scale = scale * 3
        mov     ax, [scale]
        mov     bx, 3
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     [scale], ax
; ---- scale = scale / 2
        mov     bx, 2
        cwd                                 ; sign-extend AX into DX:AX
        idiv    bx
        mov     [scale], ax
; ---- scale = scale >> 1
        sar     ax, 1                       ; signed >>
        mov     [scale], ax
; ---- scale = -scale
        neg     ax
        mov     [scale], ax
        ret

; ============================================== sub constants ====

constants:
; ---- scale = i8.8( 3 )
        mov     word [scale], 768
; ---- whole = i16( i8.8( 3 ) )
        mov     word [whole], 3
        ret

; ============================================== i16 doubled ====

doubled:
; ---- i8.8 doubled( i8.8 v ) => v * 2
        mov     ax, [doubled__v]
        shl     ax, 1                       ; * 2 is << 1
        mov     [doubled__ret], ax
        ret

; ============================================== sub throughARoutine ====

throughARoutine:
; ---- sub throughARoutine => scale = doubled( height )
        mov     ax, [height]
        mov     [doubled__v], ax
        call    doubled
        mov     ax, [doubled__ret]
        mov     [scale], ax
        ret

; ============================================== sub eightBit ====

eightBit:
; ---- small = small + small
        mov     al, [small]
        cbw                                 ; i8 -> i16
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [small]
        cbw                                 ; i8 -> i16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [small], al                 ; narrowed to i8
; ---- small = small * 2
        cbw                                 ; i8 -> i16
        shl     ax, 1                       ; * 2 is << 1
        mov     [small], al                 ; narrowed to i8
        ret

; ============================================== sub throughStorage ====

throughStorage:
; ---- table[0] = scale
        mov     ax, [scale]
        mov     [table], ax
; ---- scale = table[1]
        mov     ax, [table + 2]
        mov     [scale], ax
; ---- blob[0].weight = scale
        mov     [blob__weight], ax
; ---- scale = blob[1].weight
        mov     ax, [blob__weight + 2]
        mov     [scale], ax
; ---- scale = one
        mov     word [scale], 256
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
scale:          dw      0        ; i16
height:         dw      0        ; i16
whole:          dw      0        ; i16
over:           db      0        ; bool
doubled__v:     dw      0        ; i16
doubled__ret:   dw      0        ; i16
small:          db      0        ; i8

; ---- arrays ----
table:          times 3 dw 0        ; i16[3]
blob__weight:   times 2 dw 0        ; i16[2]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     260        ; 4 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
