; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
limit           equ     20
base            equ     10
maxDigits       equ     5
zeroChar        equ     48
mask            equ     127
stripe          equ     170

; =========================================================== entry ====

__entry:
; ---- strAddr = addr(banner)
        mov     ax, banner                  ; link-time constant
        mov     [strAddr], ax
; ---- putStr()
        call    putStr
; ---- run()
        call    run
; ---- putBar()
        call    putBar
; ---- newline()
        call    newline
; ---- peekKey()
        call    peekKey

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub putChar ====

putChar:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _dl = char
        mov     al, [char]
        xor     ah, ah                      ; u8 -> u16
        mov     [_dl], al                   ; narrowed to u8
; ---- int 0x21
        call    int21
        ret

; ============================================== sub putStr ====

putStr:
; ---- _ah = 0x09
        mov     byte [_ah], 9
; ---- _dx = strAddr
        mov     ax, [strAddr]
        mov     [_dx], ax
; ---- int 0x21
        call    int21
        ret

; ============================================== sub newline ====

newline:
; ---- char = 13
        mov     byte [char], 13
; ---- putChar()
        call    putChar
; ---- char = 10
        mov     byte [char], 10
; ---- putChar()
        call    putChar
        ret

; ============================================== sub peekKey ====

peekKey:
; ---- _ah = 0x01                        // non-blocking: check, do not wait
        mov     byte [_ah], 1
; ---- int 0x16                          // second INT number -> second helper
        call    int16
; ---- char = _al
        mov     al, [_al]
        xor     ah, ah                      ; u8 -> u16
        mov     [char], al                  ; narrowed to u8
        ret

; ============================================== sub putSpaces ====

putSpaces:
; ---- while (spaceCount > 0) {
.L1:
        mov     al, [spaceCount]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 0
        ja      .L4                         ; unsigned >
        jmp     .L3
.L4:
; ---- char = ' '
        mov     byte [char], 32
; ---- putChar()
        call    putChar
; ---- spaceCount--
        dec     byte [spaceCount]
.L2:
        jmp     .L1
.L3:
        ret

; ============================================== sub putBar ====

putBar:
; ---- do {
.L5:
; ---- char = '-'
        mov     byte [char], 45
; ---- putChar()
        call    putChar
; ---- n++
        inc     byte [putBar__n]
.L6:
        mov     al, [putBar__n]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 3
        jae     .L8                         ; unsigned <
        jmp     .L5
.L8:
.L7:
        ret

; ============================================== sub putNumber ====

putNumber:
; ---- u16 n = value
        mov     ax, [value]
        mov     [putNumber__n], ax
; ---- if (n == 0) {
        mov     ax, [putNumber__n]
        cmp     ax, 0
        je      .L11                        ; unsigned ==
        jmp     .L9
.L11:
; ---- char = zeroChar
        mov     byte [char], 48
; ---- putChar()
        call    putChar
; ---- return                          // bare early exit
        ret
.L9:
; ---- for (i = 0; n > 0; i++) {
        mov     byte [putNumber__i], 0
.L12:
        mov     ax, [putNumber__n]
        cmp     ax, 0
        ja      .L15                        ; unsigned >
        jmp     .L14
.L15:
; ---- digits[i] = u8(n % base) + zeroChar
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        add     ax, 48
        push    ax                          ; save value while computing the index
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        mov     [digits + bx], al
; ---- n /= base
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     [putNumber__n], ax
.L13:
        inc     byte [putNumber__i]
        jmp     .L12
.L14:
; ---- for (; i > 0; i--) {              // empty init clause
.L16:
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 0
        ja      .L19                        ; unsigned >
        jmp     .L18
.L19:
; ---- char = digits[i - 1]
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        sub     ax, 1
        mov     bx, ax
        mov     al, [digits + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [char], al                  ; narrowed to u8
; ---- putChar()
        call    putChar
.L17:
        dec     byte [putNumber__i]
        jmp     .L16
.L18:
        ret

; ============================================== sub isDivisible ====

isDivisible:
; ---- divResult = divN % divD == 0      // subs return nothing: results come back
        mov     ax, [divN]
        mov     bx, [divD]
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        cmp     ax, 0
        je      .L22                        ; unsigned ==
        jmp     .L20
.L22:
        mov     ax, 1
        jmp     .L21
.L20:
        xor     ax, ax
.L21:
        mov     [divResult], al             ; narrowed to bool
        ret

; ============================================== sub run ====

run:
; ---- for (value = 1; value <= limit; value++) {
        mov     word [value], 1
.L23:
        mov     ax, [value]
        cmp     ax, 20
        jbe     .L26                        ; unsigned <=
        jmp     .L25
.L26:
; ---- if (value == 13) continue
        mov     ax, [value]
        cmp     ax, 13
        je      .L29                        ; unsigned ==
        jmp     .L27
.L29:
        jmp     .L24
.L27:
; ---- if (value > 17) break
        mov     ax, [value]
        cmp     ax, 17
        ja      .L32                        ; unsigned >
        jmp     .L30
.L32:
        jmp     .L25
.L30:
; ---- putNumber()
        call    putNumber
; ---- char = ' '
        mov     byte [char], 32
; ---- putChar()
        call    putChar
; ---- divN = value
        mov     ax, [value]
        mov     [divN], ax
; ---- divD = 3
        mov     word [divD], 3
; ---- isDivisible()
        call    isDivisible
; ---- done = divResult
        mov     al, [divResult]
        xor     ah, ah                      ; bool -> u16
        mov     [done], al                  ; narrowed to bool
; ---- if (done) {
        mov     al, [done]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L35
        jmp     .L33
.L35:
; ---- strAddr = addr(fizz)
        mov     ax, fizz                    ; link-time constant
        mov     [strAddr], ax
; ---- putStr()
        call    putStr
.L33:
; ---- divD = 5
        mov     word [divD], 5
; ---- isDivisible()
        call    isDivisible
; ---- if (divResult) {
        mov     al, [divResult]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L38
        jmp     .L36
.L38:
; ---- strAddr = addr(buzz)
        mov     ax, buzz                    ; link-time constant
        mov     [strAddr], ax
; ---- putStr()
        call    putStr
.L36:
; ---- if (
; ---- value > 3 &&                  // multi-line condition: newline is not a
; ---- value < 9                     // terminator while bracket depth > 0
        mov     ax, [value]
        cmp     ax, 3
        ja      .L41                        ; unsigned >
        jmp     .L39
.L41:
        mov     ax, [value]
        cmp     ax, 9
        jb      .L42                        ; unsigned <
        jmp     .L39
.L42:
; ---- char = squares[value - 3] + zeroChar
        mov     ax, [value]
        sub     ax, 3
        mov     bx, ax
        mov     al, [squares + bx]
        xor     ah, ah                      ; u8 -> u16
        add     ax, 48
        mov     [char], al                  ; narrowed to u8
; ---- putChar()
        call    putChar
.L39:
; ---- if (value < 5) {
        mov     ax, [value]
        cmp     ax, 5
        jb      .L45                        ; unsigned <
        jmp     .L43
.L45:
; ---- char = 'a'
        mov     byte [char], 97
        jmp     .L44
.L43:
; ---- } else if (value < 10) {
        mov     ax, [value]
        cmp     ax, 10
        jb      .L48                        ; unsigned <
        jmp     .L46
.L48:
; ---- char = 'b'
        mov     byte [char], 98
        jmp     .L47
.L46:
; ---- char = 'c'
        mov     byte [char], 99
.L47:
.L44:
; ---- putChar()
        call    putChar
; ---- if (!done || value == limit) {
        mov     al, [done]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L52
        jmp     .L51
.L52:
        mov     ax, [value]
        cmp     ax, 20
        je      .L53                        ; unsigned ==
        jmp     .L49
.L53:
.L51:
; ---- char = done ? '*' : value > 10 ? '#' : '.'   // nested, right-assoc
        mov     al, [done]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L56
        jmp     .L54
.L56:
        mov     ax, 42
        jmp     .L55
.L54:
        mov     ax, [value]
        cmp     ax, 10
        ja      .L59                        ; unsigned >
        jmp     .L57
.L59:
        mov     ax, 35
        jmp     .L58
.L57:
        mov     ax, 46
.L58:
.L55:
        mov     [char], al                  ; narrowed to u8
; ---- putChar()
        call    putChar
.L49:
; ---- spaceCount = 2
        mov     byte [spaceCount], 2
; ---- putSpaces()
        call    putSpaces
; ---- if (partial[value % 6]) {       // truthiness on an array element
        mov     ax, [value]
        mov     bx, 6
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        mov     bx, ax
        mov     al, [partial + bx]
        xor     ah, ah                      ; u8 -> u16
        test    ax, ax
        jnz     .L62
        jmp     .L60
.L62:
; ---- char = '+'
        mov     byte [char], 43
; ---- putChar()
        call    putChar
.L60:
; ---- newline()
        call    newline
.L24:
        inc     word [value]
        jmp     .L23
.L25:
; ---- checksum()                        // forward reference: defined below
        call    checksum
        ret

; ============================================== sub checksum ====

checksum:
; ---- hash = 0
        mov     byte [hash], 0
; ---- for (i = 0; ; i++) {              // empty condition + break
        mov     byte [checksum__i], 0
.L63:
; ---- hash = u8((hash << 1) ^ digits[i])
        mov     al, [hash]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [checksum__i]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [digits + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        xor     ax, bx
        xor     ah, ah                      ; cast to u8
        mov     [hash], al                  ; narrowed to u8
; ---- if (i == maxDigits - 1) break
        mov     al, [checksum__i]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 4
        je      .L68                        ; unsigned ==
        jmp     .L66
.L68:
        jmp     .L65
.L66:
.L64:
        inc     byte [checksum__i]
        jmp     .L63
.L65:
; ---- hash &= mask
        mov     al, [hash]
        xor     ah, ah                      ; u8 -> u16
        and     ax, 127
        mov     [hash], al                  ; narrowed to u8
; ---- hash |= 0x20
        mov     al, [hash]
        xor     ah, ah                      ; u8 -> u16
        or      ax, 32
        mov     [hash], al                  ; narrowed to u8
; ---- hash ^= 0x01
        mov     al, [hash]
        xor     ah, ah                      ; u8 -> u16
        xor     ax, 1
        mov     [hash], al                  ; narrowed to u8
; ---- hash >>= 1                        // u8 -> shr
        mov     al, [hash]
        xor     ah, ah                      ; u8 -> u16
        shr     ax, 1                       ; unsigned >>
        mov     [hash], al                  ; narrowed to u8
; ---- hash = u8(~hash)
        mov     al, [hash]
        xor     ah, ah                      ; u8 -> u16
        not     ax
        xor     ah, ah                      ; cast to u8
        mov     [hash], al                  ; narrowed to u8
; ---- hash = u8(hash + table[1])
        mov     al, [hash]
        xor     ah, ah                      ; u8 -> u16
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [table + 1]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        xor     ah, ah                      ; cast to u8
        mov     [hash], al                  ; narrowed to u8
; ---- hash = u8((hash & mask) | (i * 2))  // bare & | * (compound forms above)
        mov     al, [hash]
        xor     ah, ah                      ; u8 -> u16
        and     ax, 127
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [checksum__i]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 2
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     bx, ax
        pop     ax
        or      ax, bx
        xor     ah, ah                      ; cast to u8
        mov     [hash], al                  ; narrowed to u8
; ---- hash = u8(hash ^ stripe)
        mov     al, [hash]
        xor     ah, ah                      ; u8 -> u16
        xor     ax, 170
        xor     ah, ah                      ; cast to u8
        mov     [hash], al                  ; narrowed to u8
; ---- signedAcc = i16(value) - 1        // u16 x signed needs an explicit cast
        mov     ax, [value]
        sub     ax, 1
        mov     [signedAcc], ax
; ---- signedAcc >>= 2                   // i16 -> sar, not shr
        mov     ax, [signedAcc]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     [signedAcc], ax
; ---- signedAcc += delta                // i16 += i8
        mov     ax, [signedAcc]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [delta]
        cbw                                 ; i8 -> i16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [signedAcc], ax
; ---- signedAcc -= 2
        mov     ax, [signedAcc]
        sub     ax, 2
        mov     [signedAcc], ax
; ---- signedAcc *= 3
        mov     ax, [signedAcc]
        mov     bx, 3
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     [signedAcc], ax
; ---- if (signedAcc < 0) signedAcc = -signedAcc
        mov     ax, [signedAcc]
        cmp     ax, 0
        jl      .L71                        ; signed <
        jmp     .L69
.L71:
        mov     ax, [signedAcc]
        neg     ax
        mov     [signedAcc], ax
.L69:
; ---- value = u16(signedAcc)
        mov     ax, [signedAcc]
        mov     [value], ax
; ---- value %= 100
        mov     ax, [value]
        mov     bx, 100
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        mov     [value], ax
; ---- value <<= 1
        mov     ax, [value]
        shl     ax, 1
        mov     [value], ax
; ---- value = value / 2 + 1               // bare /
        mov     ax, [value]
        mov     bx, 2
        xor     dx, dx                      ; clear high half for div
        div     bx
        add     ax, 1
        mov     [value], ax
; ---- if (delta != 0 && signedAcc >= 0) {
        mov     al, [delta]
        cbw                                 ; i8 -> i16
        cmp     ax, 0
        jne     .L74                        ; signed !=
        jmp     .L72
.L74:
        mov     ax, [signedAcc]
        cmp     ax, 0
        jge     .L75                        ; signed >=
        jmp     .L72
.L75:
; ---- putNumber()
        call    putNumber
; ---- newline()
        call    newline
.L72:
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int16:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x16
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax             dw      0
_al             equ     _ax
_ah             equ     _ax + 1
_bx             dw      0
_bl             equ     _bx
_bh             equ     _bx + 1
_cx             dw      0
_cl             equ     _cx
_ch             equ     _cx + 1
_dx             dw      0
_dl             equ     _dx
_dh             equ     _dx + 1
_si             dw      0
_di             dw      0

; ---- variables ----
value           dw      0        ; u16
strAddr         dw      0        ; u16
char            db      0        ; u8
hash            db      0        ; u8
signedAcc       dw      65535        ; i16 = -1
delta           db      253        ; i8 = -3
done            db      0        ; bool
divN            dw      0        ; u16
divD            dw      0        ; u16
divResult       db      0        ; bool
spaceCount      db      0        ; u8
putBar__n       db      0        ; u8
putNumber__i    db      0        ; u8
putNumber__n    dw      0        ; u16
checksum__i     db      0        ; u8

; ---- arrays ----
banner          db      'smoke', 13, 10, '$'        ; u8[8] const
fizz            db      'fizz $'        ; u8[6] const
buzz            db      'buzz $'        ; u8[6] const
squares         db      0, 1, 4, 9, 16, 25        ; u8[6] const
digits          times 5 db 0        ; u8[5]
partial         db      1, 2, 3, 0, 0, 0        ; u8[6]
table           db      2, 4, 6, 8        ; u8[4]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack         equ     268        ; 12 worst-case + 256 interrupt reserve
_htop           equ     0FFFEh - _hstack

_hsize          dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw          equ     _heap        ; same bytes, u16 view
