; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
ioBase:         equ     10
ioZeroChar:     equ     48

; =========================================================== entry ====

__entry:
; ---- for ( i = 0; i < len( menu ); i++ ) {
        mov     word [i], 0
.L1:
        mov     ax, [i]
        cmp     ax, 4
        jae     .L3                         ; unsigned <
; ---- putStr( addr( menu[i] ) )           // File, Edit, Search, View
        mov     ax, [i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [menu + bx]
        mov     [putStr__at], ax
        call    putStr
; ---- newline()
        call    newline
.L2:
        inc     word [i]
        jmp     .L1
.L3:
; ---- i = 2
        mov     word [i], 2
; ---- c = 1
        mov     word [c], 1
; ---- putChar( menu[i][c] )                 // e, from Search
        mov     ax, [i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [menu + bx]
        mov     bx, [c]
        add     bx, ax                      ; into the child
        mov     al, [bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
; ---- putChar( menu[i][c + 2] )             // r
        mov     ax, [i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [menu + bx]
        push    ax                          ; save the child while its index is computed
        mov     ax, [c]
        add     ax, 2
        pop     bx
        add     bx, ax                      ; into the child
        mov     al, [bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
; ---- putChar( menu[i][0] )                 // S
        mov     ax, [i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [menu + bx]
        mov     bx, ax                      ; the child
        mov     al, [bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
; ---- newline()
        call    newline
; ---- for ( i = 0; i < len( menu ); i++ ) {
        mov     word [i], 0
.L5:
        mov     ax, [i]
        cmp     ax, 4
        jae     .L7                         ; unsigned <
; ---- putNumber( len( menu[i] ) )         // 5575 - each counts its $
        mov     ax, [i]
        mov     bx, ax
        mov     al, [menu__len + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
.L6:
        inc     word [i]
        jmp     .L5
.L7:
; ---- newline()
        call    newline
; ---- putStr( addr( menu[1] ) )             // Edit
        mov     ax, menu__1                 ; link-time constant
        mov     [putStr__at], ax
        call    putStr
; ---- newline()
        call    newline
; ---- putChar( menu[3][0] )                 // V
        mov     al, [menu__3]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
; ---- newline()
        call    newline
; ---- putNumber( len( digits ) )            // 3
        mov     word [putNumber__n], 3
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( len( digits[2] ) )         // 4
        mov     word [putNumber__n], 4
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( digits[0][2] )             // 4
        mov     al, [digits__0 + 2]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- c = 1
        mov     word [c], 1
; ---- putNumber( digits[1][c] )             // 5
        mov     ax, [c]
        mov     bx, ax
        mov     al, [digits__1 + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- for ( c = 0; c < len( digits[2] ); c++ ) {
        mov     word [c], 0
.L9:
        mov     ax, [c]
        cmp     ax, 4
        jae     .L11                        ; unsigned <
; ---- putNumber( digits[2][c] )           // 9265
        mov     ax, [c]
        mov     bx, ax
        mov     al, [digits__2 + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
.L10:
        inc     word [c]
        jmp     .L9
.L11:
; ---- newline()
        call    newline

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub putChar ====

putChar:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _dl = c
        mov     al, [putChar__c]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x21
        call    int21
        ret

; ============================================== sub putStr ====

putStr:
; ---- _ah = 0x09
        mov     byte [_ah], 9
; ---- _dx = at
        mov     ax, [putStr__at]
        mov     [_dx], ax
; ---- int 0x21
        call    int21
        ret

; ============================================== sub newline ====

newline:
; ---- putChar(13)
        mov     byte [putChar__c], 13
        call    putChar
; ---- putChar(10)
        mov     byte [putChar__c], 10
        call    putChar
        ret

; ============================================== sub putNumber ====

putNumber:
; ---- if (n == 0) {
        mov     ax, [putNumber__n]
        test    ax, ax
        jne     .L13                        ; unsigned ==
; ---- putChar(ioZeroChar)
        mov     byte [putChar__c], 48
        call    putChar
; ---- return
        ret
.L13:
; ---- for (i = 0; n > 0; i++) {
        mov     byte [putNumber__i], 0
.L16:
        mov     ax, [putNumber__n]
        test    ax, ax
        jbe     .L18                        ; unsigned >
; ---- digits[i] = u8(n % ioBase) + ioZeroChar
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        add     ax, 48
        mov     bl, [putNumber__i]
        xor     bh, bh                      ; u8 -> u16
        mov     [putNumber__digits + bx], al
; ---- n /= ioBase
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     [putNumber__n], ax
.L17:
        inc     byte [putNumber__i]
        jmp     .L16
.L18:
; ---- for (; i > 0; i--) {
.L20:
        mov     al, [putNumber__i]
        test    al, al
        jbe     .L22                        ; unsigned >
; ---- putChar(digits[i - 1])
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        dec     ax
        mov     bx, ax
        mov     al, [putNumber__digits + bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
.L21:
        dec     byte [putNumber__i]
        jmp     .L20
.L22:
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0

; ---- variables ----
putChar__c:     db      0        ; u8
putStr__at:     dw      0        ; u16
putNumber__n:   dw      0        ; u16
i:              dw      0        ; u16
c:              dw      0        ; u16
putNumber__i:   db      0        ; u8

; ---- arrays ----
menu__0:        db      'File$'        ; u8[5] const
menu__1:        db      'Edit$'        ; u8[5] const
menu__2:        db      'Search$'        ; u8[7] const
menu__3:        db      'View$'        ; u8[5] const
menu__len:      db      5, 5, 7, 5        ; u8[4] const
menu:           dw      menu__0, menu__1, menu__2, menu__3        ; u16[4] const
digits__0:      db      3, 1, 4        ; u8[3] const
digits__1:      db      1, 5        ; u8[2] const
digits__2:      db      9, 2, 6, 5        ; u8[4] const
putNumber__digits: times 5 db 0        ; u8[5]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     262        ; 6 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
