; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
ioBase:         equ     10
ioZeroChar:     equ     48

; =========================================================== entry ====

__entry:
; ---- openFile( addr( present ) )
        mov     ax, present                 ; link-time constant
        mov     [openFile__at], ax
        call    openFile
; ---- openFailed = _cf
        mov     al, [_cf]
        mov     [openFailed], al            ; bool -> bool, no widening
; ---- handle = _ax
        mov     ax, [_ax]
        mov     [handle], ax
; ---- closeFile( handle )
        mov     ax, [handle]
        mov     [closeFile__handle], ax
        call    closeFile
; ---- openFile( addr( missing ) )
        mov     ax, missing                 ; link-time constant
        mov     [openFile__at], ax
        call    openFile
; ---- missingFailed = _cf
        mov     al, [_cf]
        mov     [missingFailed], al         ; bool -> bool, no widening
; ---- putNumber( u16( openFailed ) )
        mov     al, [openFailed]
        xor     ah, ah                      ; bool -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar( ' ' )
        mov     byte [putChar__c], 32
        call    putChar
; ---- putNumber( u16( missingFailed ) )
        mov     al, [missingFailed]
        xor     ah, ah                      ; bool -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub putChar ====

putChar:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _dl = c
        mov     al, [putChar__c]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x21
        call    int21
        ret

; ============================================== sub newline ====

newline:
; ---- putChar(13)
        mov     byte [putChar__c], 13
        call    putChar
; ---- putChar(10)
        mov     byte [putChar__c], 10
        call    putChar
        ret

; ============================================== sub putNumber ====

putNumber:
; ---- if (n == 0) {
        mov     ax, [putNumber__n]
        test    ax, ax
        je      .L3                         ; unsigned ==
        jmp     .L1
.L3:
; ---- putChar(ioZeroChar)
        mov     byte [putChar__c], 48
        call    putChar
; ---- return
        ret
.L1:
; ---- for (i = 0; n > 0; i++) {
        mov     byte [putNumber__i], 0
.L4:
        mov     ax, [putNumber__n]
        test    ax, ax
        ja      .L7                         ; unsigned >
        jmp     .L6
.L7:
; ---- digits[i] = u8(n % ioBase) + ioZeroChar
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        add     ax, 48
        push    ax                          ; save value while computing the index
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        mov     [putNumber__digits + bx], al
; ---- n /= ioBase
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     [putNumber__n], ax
.L5:
        inc     byte [putNumber__i]
        jmp     .L4
.L6:
; ---- for (; i > 0; i--) {
.L8:
        mov     al, [putNumber__i]
        test    al, al
        ja      .L11                        ; unsigned >
        jmp     .L10
.L11:
; ---- putChar(digits[i - 1])
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        dec     ax
        mov     bx, ax
        mov     al, [putNumber__digits + bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
.L9:
        dec     byte [putNumber__i]
        jmp     .L8
.L10:
        ret

; ============================================== sub openFile ====

openFile:
; ---- _ah = 0x3D
        mov     byte [_ah], 61
; ---- _al = 0
        mov     byte [_al], 0
; ---- _dx = at
        mov     ax, [openFile__at]
        mov     [_dx], ax
; ---- int 0x21
        call    int21
        ret

; ============================================== sub closeFile ====

closeFile:
; ---- _ah = 0x3E
        mov     byte [_ah], 62
; ---- _bx = handle
        mov     ax, [closeFile__handle]
        mov     [_bx], ax
; ---- int 0x21
        call    int21
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pushf
        pop     ax
        and     al, 1                       ; carry is bit 0
        mov     [_cf], al
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0
_cf:            db      0

; ---- variables ----
putChar__c:     db      0        ; u8
putNumber__n:   dw      0        ; u16
openFile__at:   dw      0        ; u16
closeFile__handle: dw      0        ; u16
openFailed:     db      0        ; bool
missingFailed:  db      0        ; bool
handle:         dw      0        ; u16
putNumber__i:   db      0        ; u8

; ---- arrays ----
present:        db      'CFTEST.ASM', 0        ; u8[11] const
missing:        db      'NOSUCH.XYZ', 0        ; u8[11] const
putNumber__digits: times 5 db 0        ; u8[5]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     262        ; 6 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view
