; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
screenW         equ     320
screenH         equ     200
playLeft        equ     40
playRight       equ     118
playTop         equ     9
playBottom      equ     80
playW           equ     79
playH           equ     72
centerX         equ     79
scoreTop        equ     84
scoreY          equ     85
scoreX0         equ     44
scoreX1         equ     51
scoreX2         equ     101
scoreX3         equ     108
paddleH         equ     9
ballW           equ     3
ballH           equ     3
subgridScale    equ     4
paddleSpeedStep equ     2
paddleSpeedMax  equ     16
paddleYMax      equ     244
ballXMax        equ     296
paddleYHome     equ     122
ballServeOffset equ     12
scoreTopWord    equ     26880
screenWord      equ     32000
tkbd__picMask   equ     33
tkbd__kbData    equ     96
tkbd__kbStatus  equ     100
tkbd__kbFull    equ     1
tkbd__kbAux     equ     32
tkbd__irqKbd    equ     2
tkbd__scEsc     equ     1
tkbd__scW       equ     17
tkbd__scA       equ     30
tkbd__scS       equ     31
tkbd__scD       equ     32
tkbd__scUp      equ     72
tkbd__scLeft    equ     75
tkbd__scRight   equ     77
tkbd__scDown    equ     80
tpal__palSize   equ     8
lightGrey       equ     0
lightGreen      equ     1
lightBlue       equ     2
black           equ     3
red             equ     4
green           equ     5
blue            equ     6
white           equ     7
lightGreenW     equ     257
blackW          equ     771
playerCount     equ     2
frameMicros     equ     33333

; =========================================================== entry ====

__entry:
; ---- saveMode()
        call    saveMode
; ---- mode13()
        call    mode13
; ---- initPal()
        call    initPal
; ---- keyboardBegin()
        call    keyboardBegin
; ---- start()
        call    start
; ---- while( isRunning ) tick()
.L1:
        mov     al, [isRunning]
        test    al, al
        jnz     .L4
        jmp     .L3
.L4:
        call    tick
.L2:
        jmp     .L1
.L3:
; ---- keyboardEnd()
        call    keyboardEnd
; ---- restoreMode()
        call    restoreMode

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub seedRandom ====

seedRandom:
; ---- sub seedRandom(u16 s) => randomSeed = s == 0 ? 1 : s
        mov     ax, [seedRandom__s]
        test    ax, ax
        je      .L7                         ; unsigned ==
        jmp     .L5
.L7:
        mov     ax, 1
        jmp     .L6
.L5:
        mov     ax, [seedRandom__s]
.L6:
        mov     [rand__randomSeed], ax
        ret

; ============================================== u16 nextRandom ====

nextRandom:
; ---- randomSeed = randomSeed ^ (randomSeed << 7)
        mov     ax, [rand__randomSeed]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [rand__randomSeed]
        mov     cl, 7                       ; 8086 has no shift-by-immediate
        shl     ax, cl
        mov     bx, ax
        pop     ax
        xor     ax, bx
        mov     [rand__randomSeed], ax
; ---- randomSeed = randomSeed ^ (randomSeed >> 9)
        mov     ax, [rand__randomSeed]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [rand__randomSeed]
        mov     cl, 9                       ; 8086 has no shift-by-immediate
        shr     ax, cl                      ; unsigned >>
        mov     bx, ax
        pop     ax
        xor     ax, bx
        mov     [rand__randomSeed], ax
; ---- randomSeed = randomSeed ^ (randomSeed << 8)
        mov     ax, [rand__randomSeed]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [rand__randomSeed]
        mov     cl, 8                       ; 8086 has no shift-by-immediate
        shl     ax, cl
        mov     bx, ax
        pop     ax
        xor     ax, bx
        mov     [rand__randomSeed], ax
; ---- return randomSeed
        mov     ax, [rand__randomSeed]
        mov     [nextRandom__ret], ax
        ret

; ============================================== u16 randomBelow ====

randomBelow:
; ---- u16 randomBelow(u16 n) => nextRandom() % n
        call    nextRandom
        mov     ax, [nextRandom__ret]
        mov     bx, [randomBelow__n]
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        mov     [randomBelow__ret], ax
        ret

; ============================================== u16 ticks ====

ticks:
; ---- u16 ticks() => tickLow[0]
        mov     dx, 0x40                    ; segment of tickLow
        mov     es, dx
        mov     ax, [es:108]
        mov     [ticks__ret], ax
        ret

; ============================================== sub keyboardBegin ====

keyboardBegin:
; ---- out8( picMask, in8( picMask ) | irqKbd )
        mov     dx, 33
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        or      ax, 2
        mov     dx, 33
        out     dx, al
; ---- while ( in8( kbStatus ) & kbFull ) {
.L8:
        mov     dx, 100
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        and     ax, 1
        test    ax, ax
        jnz     .L11
        jmp     .L10
.L11:
; ---- code = in8( kbData )
        mov     dx, 96
        in      al, dx
        mov     [tkbd__code], al            ; u8 -> u8, no widening
.L9:
        jmp     .L8
.L10:
        ret

; ============================================== bool anyKeyDown ====

tkbd__anyKeyDown:
; ---- local bool anyKeyDown() => (
; ---- isUp1 || isDown1 || isLeft1 || isRight1 ||
; ---- isUp2 || isDown2 || isLeft2 || isRight2 || isEsc
; ---- )
        mov     al, [isUp1]
        test    al, al
        jz      .L15
        jmp     .L14
.L15:
        mov     al, [isDown1]
        test    al, al
        jz      .L16
        jmp     .L14
.L16:
        mov     al, [isLeft1]
        test    al, al
        jz      .L17
        jmp     .L14
.L17:
        mov     al, [isRight1]
        test    al, al
        jz      .L18
        jmp     .L14
.L18:
        mov     al, [isUp2]
        test    al, al
        jz      .L19
        jmp     .L14
.L19:
        mov     al, [isDown2]
        test    al, al
        jz      .L20
        jmp     .L14
.L20:
        mov     al, [isLeft2]
        test    al, al
        jz      .L21
        jmp     .L14
.L21:
        mov     al, [isRight2]
        test    al, al
        jz      .L22
        jmp     .L14
.L22:
        mov     al, [isEsc]
        test    al, al
        jnz     .L23
        jmp     .L12
.L23:
.L14:
        mov     ax, 1
        jmp     .L13
.L12:
        xor     ax, ax
.L13:
        mov     [tkbd__anyKeyDown__ret], al ; narrowed to bool
        ret

; ============================================== sub keyboardEnd ====

keyboardEnd:
; ---- while ( anyKeyDown() ) {
.L24:
        call    tkbd__anyKeyDown
        mov     al, [tkbd__anyKeyDown__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L27
        jmp     .L26
.L27:
; ---- pollKeyboard()
        call    pollKeyboard
.L25:
        jmp     .L24
.L26:
; ---- while ( in8( kbStatus ) & kbFull ) {
.L28:
        mov     dx, 100
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        and     ax, 1
        test    ax, ax
        jnz     .L31
        jmp     .L30
.L31:
; ---- code = in8( kbData )
        mov     dx, 96
        in      al, dx
        mov     [tkbd__code], al            ; u8 -> u8, no widening
.L29:
        jmp     .L28
.L30:
; ---- out8( picMask, in8( picMask ) & ~irqKbd )
        mov     dx, 33
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        and     ax, -3
        mov     dx, 33
        out     dx, al
        ret

; ============================================== sub applyKey ====

tkbd__applyKey:
; ---- if ( key == scW ) isUp1 = pressed
        mov     al, [tkbd__applyKey__key]
        cmp     al, 17                      ; byte operands, no widening
        je      .L34                        ; unsigned ==
        jmp     .L32
.L34:
        mov     al, [tkbd__applyKey__pressed]
        mov     [isUp1], al                 ; bool -> bool, no widening
        jmp     .L33
.L32:
; ---- else if ( key == scS ) isDown1 = pressed
        mov     al, [tkbd__applyKey__key]
        cmp     al, 31                      ; byte operands, no widening
        je      .L37                        ; unsigned ==
        jmp     .L35
.L37:
        mov     al, [tkbd__applyKey__pressed]
        mov     [isDown1], al               ; bool -> bool, no widening
        jmp     .L36
.L35:
; ---- else if ( key == scA ) isLeft1 = pressed
        mov     al, [tkbd__applyKey__key]
        cmp     al, 30                      ; byte operands, no widening
        je      .L40                        ; unsigned ==
        jmp     .L38
.L40:
        mov     al, [tkbd__applyKey__pressed]
        mov     [isLeft1], al               ; bool -> bool, no widening
        jmp     .L39
.L38:
; ---- else if ( key == scD ) isRight1 = pressed
        mov     al, [tkbd__applyKey__key]
        cmp     al, 32                      ; byte operands, no widening
        je      .L43                        ; unsigned ==
        jmp     .L41
.L43:
        mov     al, [tkbd__applyKey__pressed]
        mov     [isRight1], al              ; bool -> bool, no widening
        jmp     .L42
.L41:
; ---- else if ( key == scUp ) isUp2 = pressed
        mov     al, [tkbd__applyKey__key]
        cmp     al, 72                      ; byte operands, no widening
        je      .L46                        ; unsigned ==
        jmp     .L44
.L46:
        mov     al, [tkbd__applyKey__pressed]
        mov     [isUp2], al                 ; bool -> bool, no widening
        jmp     .L45
.L44:
; ---- else if ( key == scDown ) isDown2 = pressed
        mov     al, [tkbd__applyKey__key]
        cmp     al, 80                      ; byte operands, no widening
        je      .L49                        ; unsigned ==
        jmp     .L47
.L49:
        mov     al, [tkbd__applyKey__pressed]
        mov     [isDown2], al               ; bool -> bool, no widening
        jmp     .L48
.L47:
; ---- else if ( key == scLeft ) isLeft2 = pressed
        mov     al, [tkbd__applyKey__key]
        cmp     al, 75                      ; byte operands, no widening
        je      .L52                        ; unsigned ==
        jmp     .L50
.L52:
        mov     al, [tkbd__applyKey__pressed]
        mov     [isLeft2], al               ; bool -> bool, no widening
        jmp     .L51
.L50:
; ---- else if ( key == scRight ) isRight2 = pressed
        mov     al, [tkbd__applyKey__key]
        cmp     al, 77                      ; byte operands, no widening
        je      .L55                        ; unsigned ==
        jmp     .L53
.L55:
        mov     al, [tkbd__applyKey__pressed]
        mov     [isRight2], al              ; bool -> bool, no widening
        jmp     .L54
.L53:
; ---- else if ( key == scEsc ){
        mov     al, [tkbd__applyKey__key]
        cmp     al, 1                       ; byte operands, no widening
        je      .L58                        ; unsigned ==
        jmp     .L56
.L58:
; ---- isEsc = pressed
        mov     al, [tkbd__applyKey__pressed]
        mov     [isEsc], al                 ; bool -> bool, no widening
; ---- if( pressed ) wasEsc = true
        mov     al, [tkbd__applyKey__pressed]
        test    al, al
        jnz     .L61
        jmp     .L59
.L61:
        mov     byte [wasEsc], 1
.L59:
.L56:
.L54:
.L51:
.L48:
.L45:
.L42:
.L39:
.L36:
.L33:
        ret

; ============================================== sub pollKeyboard ====

pollKeyboard:
; ---- while ( true ) {
.L62:
; ---- status = in8( kbStatus )
        mov     dx, 100
        in      al, dx
        mov     [tkbd__status], al          ; u8 -> u8, no widening
; ---- if ( ( status & kbFull ) == 0 ) break
        mov     al, [tkbd__status]
        xor     ah, ah                      ; u8 -> u16
        and     ax, 1
        test    ax, ax
        je      .L67                        ; unsigned ==
        jmp     .L65
.L67:
        jmp     .L64
.L65:
; ---- code = in8( kbData )
        mov     dx, 96
        in      al, dx
        mov     [tkbd__code], al            ; u8 -> u8, no widening
; ---- if ( ( status & kbAux ) == 0 ) {
        mov     al, [tkbd__status]
        xor     ah, ah                      ; u8 -> u16
        and     ax, 32
        test    ax, ax
        je      .L70                        ; unsigned ==
        jmp     .L68
.L70:
; ---- down = code < 0x80
        mov     al, [tkbd__code]
        cmp     al, 128                     ; byte operands, no widening
        jb      .L73                        ; unsigned <
        jmp     .L71
.L73:
        mov     ax, 1
        jmp     .L72
.L71:
        xor     ax, ax
.L72:
        mov     [tkbd__down], al            ; narrowed to bool
; ---- applyKey( code & 0x7F, down )
        mov     al, [tkbd__code]
        xor     ah, ah                      ; u8 -> u16
        and     ax, 127
        mov     [tkbd__applyKey__key], al   ; narrowed to u8
        mov     al, [tkbd__down]
        mov     [tkbd__applyKey__pressed], al; bool -> bool, no widening
        call    tkbd__applyKey
.L68:
.L63:
        jmp     .L62
.L64:
        ret

; ============================================== sub setPaletteColor ====

tpal__setPaletteColor:
; ---- _ax = 0x1010
        mov     word [_ax], 4112
; ---- _bx = index
        mov     al, [tpal__setPaletteColor__index]
        xor     ah, ah                      ; u8 -> u16
        mov     [_bx], ax
; ---- _dh = dac( r )
        mov     al, [tpal__setPaletteColor__r]
        xor     ah, ah                      ; u8 -> u16
        shr     ax, 1                       ; unsigned >>
        shr     ax, 1
        xor     ah, ah                      ; cast to u8
        mov     [_dh], al                   ; narrowed to u8
; ---- _ch = dac( g )
        mov     al, [tpal__setPaletteColor__g]
        xor     ah, ah                      ; u8 -> u16
        shr     ax, 1                       ; unsigned >>
        shr     ax, 1
        xor     ah, ah                      ; cast to u8
        mov     [_ch], al                   ; narrowed to u8
; ---- _cl = dac( b )
        mov     al, [tpal__setPaletteColor__b]
        xor     ah, ah                      ; u8 -> u16
        shr     ax, 1                       ; unsigned >>
        shr     ax, 1
        xor     ah, ah                      ; cast to u8
        mov     [_cl], al                   ; narrowed to u8
; ---- int 0x10
        call    int10
        ret

; ============================================== sub initPal ====

initPal:
; ---- for( i = 0; i < palSize; i++ ){
        mov     byte [tpal__i], 0
.L74:
        mov     al, [tpal__i]
        cmp     al, 8                       ; byte operands, no widening
        jb      .L77                        ; unsigned <
        jmp     .L76
.L77:
; ---- pIndex = i * 3
        mov     al, [tpal__i]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 3
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     [tpal__pIndex], al          ; narrowed to u8
; ---- setPaletteColor(
; ---- i, palette[ pIndex ], palette[ pIndex + 1 ], palette[ pIndex + 2 ]
; ---- )
        mov     al, [tpal__i]
        mov     [tpal__setPaletteColor__index], al; u8 -> u8, no widening
        mov     al, [tpal__pIndex]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [tpal__palette + bx]
        mov     [tpal__setPaletteColor__r], al; u8 -> u8, no widening
        mov     al, [tpal__pIndex]
        xor     ah, ah                      ; u8 -> u16
        inc     ax
        mov     bx, ax
        mov     al, [tpal__palette + bx]
        mov     [tpal__setPaletteColor__g], al; u8 -> u8, no widening
        mov     al, [tpal__pIndex]
        xor     ah, ah                      ; u8 -> u16
        add     ax, 2
        mov     bx, ax
        mov     al, [tpal__palette + bx]
        mov     [tpal__setPaletteColor__b], al; u8 -> u8, no widening
        call    tpal__setPaletteColor
.L75:
        inc     byte [tpal__i]
        jmp     .L74
.L76:
        ret

; ============================================== sub saveMode ====

saveMode:
; ---- _ah = 0x0F
        mov     byte [_ah], 15
; ---- int 0x10
        call    int10
; ---- savedMode = _al & 0x7F
        mov     al, [_al]
        xor     ah, ah                      ; u8 -> u16
        and     ax, 127
        mov     [tscr__savedMode], al       ; narrowed to u8
        ret

; ============================================== sub restoreMode ====

restoreMode:
; ---- _ah = 0x00
        mov     byte [_ah], 0
; ---- _al = savedMode
        mov     al, [tscr__savedMode]
        mov     [_al], al                   ; u8 -> u8, no widening
; ---- int 0x10
        call    int10
        ret

; ============================================== sub mode13 ====

mode13:
; ---- _ax = 0x0013
        mov     word [_ax], 19
; ---- int 0x10
        call    int10
        ret

; ============================================== sub setPixel ====

setPixel:
; ---- at = pxIndex( x << 1, y << 1 )
        mov     ax, [setPixel__y]
        shl     ax, 1
        mov     bx, 320
        mul     bx                          ; low 16 bits are sign-agnostic
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [setPixel__x]
        shl     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [tscr__at], ax
; ---- pixels[ at ] = color
        mov     al, [setPixel__color]
        push    ax                          ; save value while computing the index
        mov     ax, [tscr__at]
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pixels
        mov     es, dx
        pop     ax
        mov     [es:bx], al
; ---- pixels[ at + 1 ] = color
        mov     al, [setPixel__color]
        push    ax                          ; save value while computing the index
        mov     ax, [tscr__at]
        inc     ax
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pixels
        mov     es, dx
        pop     ax
        mov     [es:bx], al
; ---- pixels[ at + 320 ] = color
        mov     al, [setPixel__color]
        push    ax                          ; save value while computing the index
        mov     ax, [tscr__at]
        add     ax, 320
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pixels
        mov     es, dx
        pop     ax
        mov     [es:bx], al
; ---- pixels[ at + 321 ] = color
        mov     al, [setPixel__color]
        push    ax                          ; save value while computing the index
        mov     ax, [tscr__at]
        add     ax, 321
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pixels
        mov     es, dx
        pop     ax
        mov     [es:bx], al
        ret

; ============================================== sub drawLineHorizontal ====

drawLineHorizontal:
; ---- for( x = x1; x <= x2; x++ ){
        mov     al, [drawLineHorizontal__x1]
        xor     ah, ah                      ; u8 -> u16
        mov     [tscr__x], ax
.L78:
        mov     ax, [tscr__x]
        mov     bl, [drawLineHorizontal__x2]
        xor     bh, bh                      ; u8 -> u16
        cmp     ax, bx
        jbe     .L81                        ; unsigned <=
        jmp     .L80
.L81:
; ---- setPixel( x, y, color )
        mov     ax, [tscr__x]
        mov     [setPixel__x], ax
        mov     al, [drawLineHorizontal__y]
        xor     ah, ah                      ; u8 -> u16
        mov     [setPixel__y], ax
        mov     al, [drawLineHorizontal__color]
        mov     [setPixel__color], al       ; u8 -> u8, no widening
        call    setPixel
.L79:
        inc     word [tscr__x]
        jmp     .L78
.L80:
        ret

; ============================================== sub drawLineVertical ====

drawLineVertical:
; ---- for( y = y1; y <= y2; y++ ){
        mov     al, [drawLineVertical__y1]
        xor     ah, ah                      ; u8 -> u16
        mov     [tscr__y], ax
.L82:
        mov     ax, [tscr__y]
        mov     bl, [drawLineVertical__y2]
        xor     bh, bh                      ; u8 -> u16
        cmp     ax, bx
        jbe     .L85                        ; unsigned <=
        jmp     .L84
.L85:
; ---- setPixel( x, y, color )
        mov     al, [drawLineVertical__x]
        xor     ah, ah                      ; u8 -> u16
        mov     [setPixel__x], ax
        mov     ax, [tscr__y]
        mov     [setPixel__y], ax
        mov     al, [drawLineVertical__color]
        mov     [setPixel__color], al       ; u8 -> u8, no widening
        call    setPixel
.L83:
        inc     word [tscr__y]
        jmp     .L82
.L84:
        ret

; ============================================== sub drawBackground ====

drawBackground:
; ---- for( dy = 0; dy < scoreTopWord; dy++ ){
        mov     word [dy_], 0
.L86:
        mov     ax, [dy_]
        cmp     ax, 26880
        jb      .L89                        ; unsigned <
        jmp     .L88
.L89:
; ---- pxwords[ dy ] = lightGreenW
        mov     ax, [dy_]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pxwords
        mov     es, dx
        mov     word [es:bx], 257
.L87:
        inc     word [dy_]
        jmp     .L86
.L88:
; ---- for( dy = scoreTopWord; dy < screenWord; dy++ ){
        mov     word [dy_], 26880
.L90:
        mov     ax, [dy_]
        cmp     ax, 32000
        jb      .L93                        ; unsigned <
        jmp     .L92
.L93:
; ---- pxwords[ dy ] = blackW
        mov     ax, [dy_]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pxwords
        mov     es, dx
        mov     word [es:bx], 771
.L91:
        inc     word [dy_]
        jmp     .L90
.L92:
        ret

; ============================================== sub drawPlayfield ====

drawPlayfield:
; ---- drawLineHorizontal( playTop, playLeft, playRight, green )
        mov     byte [drawLineHorizontal__y], 9
        mov     byte [drawLineHorizontal__x1], 40
        mov     byte [drawLineHorizontal__x2], 118
        mov     byte [drawLineHorizontal__color], 5
        call    drawLineHorizontal
; ---- drawLineHorizontal( playBottom, playLeft, playRight, green )
        mov     byte [drawLineHorizontal__y], 80
        mov     byte [drawLineHorizontal__x1], 40
        mov     byte [drawLineHorizontal__x2], 118
        mov     byte [drawLineHorizontal__color], 5
        call    drawLineHorizontal
; ---- drawNet()
        call    drawNet
        ret

; ============================================== sub drawNet ====

drawNet:
; ---- for( net = 0; net < 5; net++ ){
        mov     byte [net], 0
.L94:
        mov     al, [net]
        cmp     al, 5                       ; byte operands, no widening
        jb      .L97                        ; unsigned <
        jmp     .L96
.L97:
; ---- netY = playTop + 3 + net * 14
        mov     ax, 12
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [net]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 14
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [netY], al                  ; narrowed to u8
; ---- drawLineVertical( centerX, netY, netY + 8, green )
        mov     byte [drawLineVertical__x], 79
        mov     al, [netY]
        mov     [drawLineVertical__y1], al  ; u8 -> u8, no widening
        mov     al, [netY]
        xor     ah, ah                      ; u8 -> u16
        add     ax, 8
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     byte [drawLineVertical__color], 5
        call    drawLineVertical
.L95:
        inc     byte [net]
        jmp     .L94
.L96:
        ret

; ============================================== sub drawPaddle ====

drawPaddle:
; ---- subPxY = subgridToPx( playTop, player[ pi ].y )
        mov     ax, 10
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [drawPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxY], ax
; ---- subPxY2 = subPxY + paddleH - 1
        mov     ax, [subPxY]
        add     ax, 9
        dec     ax
        mov     [subPxY2], ax
; ---- drawLineVertical( paddleX[ pi ], subPxY, subPxY2, paddleColor[ pi ] )
        mov     al, [drawPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [paddleX + bx]
        mov     [drawLineVertical__x], al   ; u8 -> u8, no widening
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     al, [drawPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [paddleColor + bx]
        mov     [drawLineVertical__color], al; u8 -> u8, no widening
        call    drawLineVertical
        ret

; ============================================== sub clearPaddle ====

clearPaddle:
; ---- subPxY = subgridToPx( playTop, player[ pi ].oldY )
        mov     ax, 10
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [clearPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__oldY + bx]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxY], ax
; ---- subPxY2 = subPxY + paddleH - 1
        mov     ax, [subPxY]
        add     ax, 9
        dec     ax
        mov     [subPxY2], ax
; ---- drawLineVertical( paddleX[ pi ], subPxY, subPxY2, lightGreen )
        mov     al, [clearPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [paddleX + bx]
        mov     [drawLineVertical__x], al   ; u8 -> u8, no widening
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     byte [drawLineVertical__color], 1
        call    drawLineVertical
        ret

; ============================================== sub drawBall ====

drawBall:
; ---- subPxX = subgridToPx( playLeft, ballX )
        mov     ax, 41
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [ballX]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxX], ax
; ---- subPxY = subgridToPx( playTop, ballY )
        mov     ax, 10
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [ballY]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxY], ax
; ---- subPxY2 = subPxY + ballH - 1
        mov     ax, [subPxY]
        add     ax, 3
        dec     ax
        mov     [subPxY2], ax
; ---- drawLineVertical( subPxX, subPxY, subPxY2, ballColor )
        mov     ax, [subPxX]
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     al, [ballColor]
        mov     [drawLineVertical__color], al; u8 -> u8, no widening
        call    drawLineVertical
; ---- drawLineVertical( subPxX + 1, subPxY, subPxY2, ballColor )
        mov     ax, [subPxX]
        inc     ax
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     al, [ballColor]
        mov     [drawLineVertical__color], al; u8 -> u8, no widening
        call    drawLineVertical
; ---- drawLineVertical( subPxX + 2, subPxY, subPxY2, ballColor )
        mov     ax, [subPxX]
        add     ax, 2
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     al, [ballColor]
        mov     [drawLineVertical__color], al; u8 -> u8, no widening
        call    drawLineVertical
        ret

; ============================================== sub clearBall ====

clearBall:
; ---- subPxX = subgridToPx( playLeft, oBallX )
        mov     ax, 41
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [oBallX]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxX], ax
; ---- subPxY = subgridToPx( playTop, oBallY )
        mov     ax, 10
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [oBallY]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxY], ax
; ---- subPxY2 = subPxY + ballH - 1
        mov     ax, [subPxY]
        add     ax, 3
        dec     ax
        mov     [subPxY2], ax
; ---- drawLineVertical( subPxX, subPxY, subPxY2, lightGreen )
        mov     ax, [subPxX]
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     byte [drawLineVertical__color], 1
        call    drawLineVertical
; ---- drawLineVertical( subPxX + 1, subPxY, subPxY2, lightGreen )
        mov     ax, [subPxX]
        inc     ax
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     byte [drawLineVertical__color], 1
        call    drawLineVertical
; ---- drawLineVertical( subPxX + 2, subPxY, subPxY2, lightGreen )
        mov     ax, [subPxX]
        add     ax, 2
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     byte [drawLineVertical__color], 1
        call    drawLineVertical
        ret

; ============================================== sub drawSprite ====

drawSprite:
; ---- tile = index * 25
        mov     al, [drawSprite__index]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 25
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     [tile], ax
; ---- for( j = 0; j < 5; j++ ){
        mov     byte [j], 0
.L98:
        mov     al, [j]
        cmp     al, 5                       ; byte operands, no widening
        jb      .L101                       ; unsigned <
        jmp     .L100
.L101:
; ---- for( i = 0; i < 5; i++ ){
        mov     byte [i], 0
.L102:
        mov     al, [i]
        cmp     al, 5                       ; byte operands, no widening
        jb      .L105                       ; unsigned <
        jmp     .L104
.L105:
; ---- setPixel( i + dx, j + dy, textSprites[ tile ] )
        mov     al, [i]
        xor     ah, ah                      ; u8 -> u16
        mov     bl, [drawSprite__dx]
        xor     bh, bh                      ; u8 -> u16
        add     ax, bx
        mov     [setPixel__x], ax
        mov     al, [j]
        xor     ah, ah                      ; u8 -> u16
        mov     bl, [drawSprite__dy]
        xor     bh, bh                      ; u8 -> u16
        add     ax, bx
        mov     [setPixel__y], ax
        mov     ax, [tile]
        mov     bx, ax
        mov     al, [textSprites + bx]
        mov     [setPixel__color], al       ; u8 -> u8, no widening
        call    setPixel
; ---- tile++
        inc     word [tile]
.L103:
        inc     byte [i]
        jmp     .L102
.L104:
.L99:
        inc     byte [j]
        jmp     .L98
.L100:
        ret

; ============================================== sub drawScore ====

drawScore:
; ---- if( score1 < 10 ){
        mov     al, [score1]
        cmp     al, 10                      ; byte operands, no widening
        jb      .L108                       ; unsigned <
        jmp     .L106
.L108:
; ---- digit0 = 0
        mov     byte [digit0], 0
; ---- digit1 = score1
        mov     al, [score1]
        mov     [digit1], al                ; u8 -> u8, no widening
        jmp     .L107
.L106:
; ---- digit0 = 1
        mov     byte [digit0], 1
; ---- digit1 = score1 - 10
        mov     al, [score1]
        xor     ah, ah                      ; u8 -> u16
        sub     ax, 10
        mov     [digit1], al                ; narrowed to u8
.L107:
; ---- if( score2 < 10 ){
        mov     al, [score2]
        cmp     al, 10                      ; byte operands, no widening
        jb      .L111                       ; unsigned <
        jmp     .L109
.L111:
; ---- digit2 = 0
        mov     byte [digit2], 0
; ---- digit3 = score2
        mov     al, [score2]
        mov     [digit3], al                ; u8 -> u8, no widening
        jmp     .L110
.L109:
; ---- digit2 = 1
        mov     byte [digit2], 1
; ---- digit3 = score2 - 10
        mov     al, [score2]
        xor     ah, ah                      ; u8 -> u16
        sub     ax, 10
        mov     [digit3], al                ; narrowed to u8
.L110:
; ---- drawSprite( digit0, scoreX0, scoreY )
        mov     al, [digit0]
        mov     [drawSprite__index], al     ; u8 -> u8, no widening
        mov     byte [drawSprite__dx], 44
        mov     byte [drawSprite__dy], 85
        call    drawSprite
; ---- drawSprite( digit1, scoreX1, scoreY )
        mov     al, [digit1]
        mov     [drawSprite__index], al     ; u8 -> u8, no widening
        mov     byte [drawSprite__dx], 51
        mov     byte [drawSprite__dy], 85
        call    drawSprite
; ---- drawSprite( digit2, scoreX2, scoreY )
        mov     al, [digit2]
        mov     [drawSprite__index], al     ; u8 -> u8, no widening
        mov     byte [drawSprite__dx], 101
        mov     byte [drawSprite__dy], 85
        call    drawSprite
; ---- drawSprite( digit3, scoreX3, scoreY )
        mov     al, [digit3]
        mov     [drawSprite__index], al     ; u8 -> u8, no widening
        mov     byte [drawSprite__dx], 108
        mov     byte [drawSprite__dy], 85
        call    drawSprite
        ret

; ============================================== sub movePaddle ====

movePaddle:
; ---- if ( up || down ) {
        mov     al, [movePaddle__up]
        test    al, al
        jz      .L115
        jmp     .L114
.L115:
        mov     al, [movePaddle__down]
        test    al, al
        jnz     .L116
        jmp     .L112
.L116:
.L114:
; ---- if ( up ) player[ pi ].y -= player[ pi ].speed
        mov     al, [movePaddle__up]
        test    al, al
        jnz     .L119
        jmp     .L117
.L119:
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__speed + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        sub     ax, bx
        push    ax                          ; save value while computing the index
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [player__y + bx], ax
.L117:
; ---- if ( down ) player[ pi ].y += player[ pi ].speed
        mov     al, [movePaddle__down]
        test    al, al
        jnz     .L122
        jmp     .L120
.L122:
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__speed + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        push    ax                          ; save value while computing the index
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [player__y + bx], ax
.L120:
; ---- if ( player[ pi ].y < 0 ) player[ pi ].y = 0
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        test    ax, ax
        jl      .L125                       ; signed <
        jmp     .L123
.L125:
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [player__y + bx], 0
.L123:
; ---- if ( player[ pi ].y > paddleYMax ) player[ pi ].y = paddleYMax
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        cmp     ax, 244
        jg      .L128                       ; signed >
        jmp     .L126
.L128:
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [player__y + bx], 244
.L126:
; ---- if ( player[ pi ].speed < paddleSpeedMax ) {
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__speed + bx]
        cmp     al, 16                      ; byte operands, no widening
        jb      .L131                       ; unsigned <
        jmp     .L129
.L131:
; ---- player[ pi ].speed += paddleSpeedStep
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__speed + bx]
        xor     ah, ah                      ; u8 -> u16
        add     ax, 2
        push    ax                          ; save value while computing the index
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        mov     [player__speed + bx], al
.L129:
        jmp     .L113
.L112:
; ---- player[ pi ].speed = 0
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     byte [player__speed + bx], 0
.L113:
        ret

; ============================================== sub input ====

input:
; ---- pollKeyboard()
        call    pollKeyboard
; ---- if( wasEsc ){
        mov     al, [wasEsc]
        test    al, al
        jnz     .L134
        jmp     .L132
.L134:
; ---- isRunning = false
        mov     byte [isRunning], 0
; ---- return
        ret
.L132:
; ---- movePaddle( 0, isUp1, isDown1 )
        mov     byte [movePaddle__pi], 0
        mov     al, [isUp1]
        mov     [movePaddle__up], al        ; bool -> bool, no widening
        mov     al, [isDown1]
        mov     [movePaddle__down], al      ; bool -> bool, no widening
        call    movePaddle
; ---- movePaddle( 1, isUp2, isDown2 )
        mov     byte [movePaddle__pi], 1
        mov     al, [isUp2]
        mov     [movePaddle__up], al        ; bool -> bool, no widening
        mov     al, [isDown2]
        mov     [movePaddle__down], al      ; bool -> bool, no widening
        call    movePaddle
        ret

; ============================================== sub update ====

update:
; ---- ballX += ballSpeedX
        mov     ax, [ballX]
        mov     bx, [ballSpeedX]
        add     ax, bx
        mov     [ballX], ax
; ---- ballY += ballSpeedY
        mov     ax, [ballY]
        mov     bx, [ballSpeedY]
        add     ax, bx
        mov     [ballY], ax
; ---- drawScore()
        call    drawScore
        ret

; ============================================== sub waitMicros ====

waitMicros:
; ---- _ah = 0x86
        mov     byte [_ah], 134
; ---- _cx = high
        mov     ax, [waitMicros__high]
        mov     [_cx], ax
; ---- _dx = low
        mov     ax, [waitMicros__low]
        mov     [_dx], ax
; ---- int 0x15
        call    int15
        ret

; ============================================== sub doWait ====

doWait:
; ---- sub doWait => waitMicros( 0, frameMicros )
        mov     word [waitMicros__high], 0
        mov     word [waitMicros__low], 33333
        call    waitMicros
        ret

; ============================================== sub render ====

render:
; ---- clearBall()
        call    clearBall
; ---- clearPaddle( 0 )
        mov     byte [clearPaddle__pi], 0
        call    clearPaddle
; ---- clearPaddle( 1 )
        mov     byte [clearPaddle__pi], 1
        call    clearPaddle
; ---- drawNet()
        call    drawNet
; ---- drawBall()
        call    drawBall
; ---- drawPaddle( 0 )
        mov     byte [drawPaddle__pi], 0
        call    drawPaddle
; ---- drawPaddle( 1 )
        mov     byte [drawPaddle__pi], 1
        call    drawPaddle
; ---- player[ 0 ].oldY = player[ 0 ].y
        mov     ax, [player__y]
        mov     [player__oldY], ax
; ---- player[ 1 ].oldY = player[ 1 ].y
        mov     ax, [player__y + 2]
        mov     [player__oldY + 2], ax
; ---- oBallX = ballX
        mov     ax, [ballX]
        mov     [oBallX], ax
; ---- oBallY = ballY
        mov     ax, [ballY]
        mov     [oBallY], ax
        ret

; ============================================== sub tick ====

tick:
; ---- input()
        call    input
; ---- update()
        call    update
; ---- render()
        call    render
; ---- doWait()
        call    doWait
        ret

; ============================================== sub serve ====

serve:
; ---- ballSpeedY = 0
        mov     word [ballSpeedY], 0
; ---- volleyCount = 0
        mov     byte [volleyCount], 0
; ---- ballX = serveX[ ballPlayer ]
        mov     al, [ballPlayer]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [serveX + bx]
        mov     [ballX], ax
; ---- ballY = player[ ballPlayer ].y + ballServeOffset
        mov     al, [ballPlayer]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        add     ax, 12
        mov     [ballY], ax
; ---- ballSpeedX = serveSpeedX[ ballPlayer ]
        mov     al, [ballPlayer]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [serveSpeedX + bx]
        mov     [ballSpeedX], ax
; ---- ballColor = paddleColor[ ballPlayer ]
        mov     al, [ballPlayer]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [paddleColor + bx]
        mov     [ballColor], al             ; u8 -> u8, no widening
        ret

; ============================================== sub start ====

start:
; ---- seedRandom( ticks() )
        call    ticks
        mov     ax, [ticks__ret]
        mov     [seedRandom__s], ax
        call    seedRandom
; ---- isWinScreen = false
        mov     byte [isWinScreen], 0
; ---- score1 = 0
        mov     byte [score1], 0
; ---- score2 = 0
        mov     byte [score2], 0
; ---- player[ 0 ].speed = 0
        mov     byte [player__speed], 0
; ---- player[ 0 ].y = paddleYHome
        mov     word [player__y], 122
; ---- player[ 0 ].oldY = paddleYHome
        mov     word [player__oldY], 122
; ---- player[ 1 ].speed = 0
        mov     byte [player__speed + 1], 0
; ---- player[ 1 ].y = paddleYHome
        mov     word [player__y + 2], 122
; ---- player[ 1 ].oldY = paddleYHome
        mov     word [player__oldY + 2], 122
; ---- ballPlayer = randomBelow( len( player ) )
        mov     word [randomBelow__n], 2
        call    randomBelow
        mov     ax, [randomBelow__ret]
        mov     [ballPlayer], al            ; narrowed to u8
; ---- drawBackground()
        call    drawBackground
; ---- drawPlayfield()
        call    drawPlayfield
; ---- serve()
        call    serve
; ---- oBallX = ballX
        mov     ax, [ballX]
        mov     [oBallX], ax
; ---- oBallY = ballY
        mov     ax, [ballY]
        mov     [oBallY], ax
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int10:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x10
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

int15:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x15
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

int21:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax             dw      0
_al             equ     _ax
_ah             equ     _ax + 1
_bx             dw      0
_bl             equ     _bx
_bh             equ     _bx + 1
_cx             dw      0
_cl             equ     _cx
_ch             equ     _cx + 1
_dx             dw      0
_dl             equ     _dx
_dh             equ     _dx + 1
_si             dw      0
_di             dw      0

; ---- variables ----
rand__randomSeed dw      42        ; u16 = 42
seedRandom__s   dw      0        ; u16
nextRandom__ret dw      0        ; u16
randomBelow__n  dw      0        ; u16
randomBelow__ret dw      0        ; u16
ticks__ret      dw      0        ; u16
isUp1           db      0        ; bool
isDown1         db      0        ; bool
isLeft1         db      0        ; bool
isRight1        db      0        ; bool
isUp2           db      0        ; bool
isDown2         db      0        ; bool
isLeft2         db      0        ; bool
isRight2        db      0        ; bool
isEsc           db      0        ; bool
wasEsc          db      0        ; bool
tkbd__code      db      0        ; u8
tkbd__anyKeyDown__ret db      0        ; bool
tkbd__applyKey__key db      0        ; u8
tkbd__applyKey__pressed db      0        ; bool
tkbd__status    db      0        ; u8
tkbd__down      db      0        ; bool
tpal__setPaletteColor__index db      0        ; u8
tpal__setPaletteColor__r db      0        ; u8
tpal__setPaletteColor__g db      0        ; u8
tpal__setPaletteColor__b db      0        ; u8
tpal__i         db      0        ; u8
tpal__pIndex    db      0        ; u8
tscr__savedMode db      0        ; u8
tscr__at        dw      0        ; u16
setPixel__x     dw      0        ; u16
setPixel__y     dw      0        ; u16
setPixel__color db      0        ; u8
tscr__x         dw      0        ; u16
tscr__y         dw      0        ; u16
drawLineHorizontal__y db      0        ; u8
drawLineHorizontal__x1 db      0        ; u8
drawLineHorizontal__x2 db      0        ; u8
drawLineHorizontal__color db      0        ; u8
drawLineVertical__x db      0        ; u8
drawLineVertical__y1 db      0        ; u8
drawLineVertical__y2 db      0        ; u8
drawLineVertical__color db      0        ; u8
isWinScreen     db      0        ; bool
isRunning       db      1        ; bool = 1
score1          db      0        ; u8
score2          db      0        ; u8
ballX           dw      0        ; i16
ballY           dw      0        ; i16
oBallX          dw      0        ; i16
oBallY          dw      0        ; i16
ballSpeedX      dw      0        ; i16
ballSpeedY      dw      0        ; i16
ballPlayer      db      0        ; u8
ballColor       db      0        ; u8
volleyCount     db      0        ; u8
dy_             dw      0        ; u16
net             db      0        ; u8
netY            db      0        ; u8
subPxX          dw      0        ; i16
subPxY          dw      0        ; i16
subPxY2         dw      0        ; i16
drawPaddle__pi  db      0        ; u8
clearPaddle__pi db      0        ; u8
tile            dw      0        ; u16
i               db      0        ; u8
j               db      0        ; u8
drawSprite__index db      0        ; u8
drawSprite__dx  db      0        ; u8
drawSprite__dy  db      0        ; u8
digit0          db      0        ; u8
digit1          db      0        ; u8
digit2          db      0        ; u8
digit3          db      0        ; u8
movePaddle__pi  db      0        ; u8
movePaddle__up  db      0        ; bool
movePaddle__down db      0        ; bool
waitMicros__high dw      0        ; u16
waitMicros__low dw      0        ; u16

; ---- arrays ----
tpal__palette   db      224, 224, 244, 145, 255, 166, 206, 208, 255, 16, 16, 16, 255, '1S', 2, 204, ']K?', 243, 252, 252, 252        ; u8[24] const
textSprites     db      7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 3, 3, 3, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7        ; u8[250] const
player__y       times 2 dw 0        ; i16[2]
player__oldY    times 2 dw 0        ; i16[2]
player__speed   times 2 db 0        ; u8[2]
paddleX         db      '(v'        ; u8[2] const
paddleColor     db      4, 6        ; u8[2] const
serveX          dw      0, 296        ; u16[2] const
serveSpeedX     dw      3, -3        ; i16[2] const

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack         equ     270        ; 14 worst-case + 256 interrupt reserve
_htop           equ     0FFFEh - _hstack

_hsize          dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw          equ     _heap        ; same bytes, u16 view
