; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
screenW         equ     320
screenH         equ     200
playLeft        equ     40
playRight       equ     118
playTop         equ     9
playBottom      equ     80
playW           equ     79
playH           equ     72
centerX         equ     79
scoreTop        equ     84
scoreY          equ     85
paddleH         equ     9
ballW           equ     3
ballH           equ     3
subgridScale    equ     4
paddleSpeedStep equ     2
paddleSpeedMax  equ     16
serveSpeed      equ     3
paddleYMax      equ     244
ballXMax        equ     296
ballYMax        equ     268
paddleYHome     equ     122
ballServeOffset equ     12
hitLead         equ     11
hitWindow       equ     47
netBallXMin     equ     144
netBallXMax     equ     155
scoreTopWord    equ     26880
screenWord      equ     32000
angleZone       equ     6
angleZone1      equ     6
angleZone2      equ     12
angleZone3      equ     18
angleZone4      equ     29
angleZone5      equ     35
angleZone6      equ     41
ballSpeedStep   equ     3
ballSpeedY1     equ     3
ballSpeedY2     equ     6
ballSpeedY3     equ     9
ballSpeedXMax   equ     9
volleyTarget    equ     3
winScore        equ     11
t_kbd__picMask  equ     33
t_kbd__kbData   equ     96
t_kbd__kbStatus equ     100
t_kbd__kbFull   equ     1
t_kbd__irqKbd   equ     2
t_kbd__scEsc    equ     1
t_kbd__scW      equ     17
t_kbd__scA      equ     30
t_kbd__scS      equ     31
t_kbd__scD      equ     32
t_kbd__scUp     equ     72
t_kbd__scLeft   equ     75
t_kbd__scRight  equ     77
t_kbd__scDown   equ     80
t_pal__palSize  equ     8
lightGrey       equ     0
lightGreen      equ     1
lightBlue       equ     2
black           equ     3
red             equ     4
green           equ     5
blue            equ     6
white           equ     7
lightGreenW     equ     257
blackW          equ     771
redW            equ     1028
blueW           equ     1542
t_scr__vgaStatus equ     986
t_scr__vgaVRetrace equ     8
t_scr__screenWNext equ     321
spriteW         equ     5
spriteH         equ     5
spriteSize      equ     25
playerCount     equ     2
leftPlayer      equ     0
rightPlayer     equ     1

; =========================================================== entry ====

__entry:
; ---- saveMode()
        call    saveMode
; ---- mode13()
        call    mode13
; ---- initPal()
        call    initPal
; ---- keyboardBegin()
        call    keyboardBegin
; ---- start()
        call    start
; ---- while( isRunning ) tick()
.L1:
        mov     al, [isRunning]
        test    al, al
        jnz     .L4
        jmp     .L3
.L4:
        call    tick
.L2:
        jmp     .L1
.L3:
; ---- keyboardEnd()
        call    keyboardEnd
; ---- restoreMode()
        call    restoreMode

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub seedRandom ====

seedRandom:
; ---- sub seedRandom(u16 s) => randomSeed = s == 0 ? 1 : s
        mov     ax, [seedRandom__s]
        test    ax, ax
        je      .L7                         ; unsigned ==
        jmp     .L5
.L7:
        mov     ax, 1
        jmp     .L6
.L5:
        mov     ax, [seedRandom__s]
.L6:
        mov     [rand__randomSeed], ax
        ret

; ============================================== u16 nextRandom ====

nextRandom:
; ---- randomSeed = randomSeed ^ (randomSeed << 7)
        mov     ax, [rand__randomSeed]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [rand__randomSeed]
        mov     cl, 7                       ; 8086 has no shift-by-immediate
        shl     ax, cl
        mov     bx, ax
        pop     ax
        xor     ax, bx
        mov     [rand__randomSeed], ax
; ---- randomSeed = randomSeed ^ (randomSeed >> 9)
        mov     ax, [rand__randomSeed]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [rand__randomSeed]
        mov     cl, 9                       ; 8086 has no shift-by-immediate
        shr     ax, cl                      ; unsigned >>
        mov     bx, ax
        pop     ax
        xor     ax, bx
        mov     [rand__randomSeed], ax
; ---- randomSeed = randomSeed ^ (randomSeed << 8)
        mov     ax, [rand__randomSeed]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [rand__randomSeed]
        mov     cl, 8                       ; 8086 has no shift-by-immediate
        shl     ax, cl
        mov     bx, ax
        pop     ax
        xor     ax, bx
        mov     [rand__randomSeed], ax
; ---- return randomSeed
        mov     ax, [rand__randomSeed]
        mov     [nextRandom__ret], ax
        ret

; ============================================== u16 randomBelow ====

randomBelow:
; ---- u16 randomBelow(u16 n) => nextRandom() % n
        call    nextRandom
        mov     ax, [nextRandom__ret]
        mov     bx, [randomBelow__n]
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        mov     [randomBelow__ret], ax
        ret

; ============================================== u16 ticks ====

ticks:
; ---- u16 ticks() => tickLow[0]
        mov     dx, 0x40                    ; segment of tickLow
        mov     es, dx
        mov     ax, [es:108]
        mov     [ticks__ret], ax
        ret

; ============================================== sub keyboardBegin ====

keyboardBegin:
; ---- out8( picMask, in8( picMask ) | irqKbd )
        mov     dx, 33
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        or      ax, 2
        mov     dx, 33
        out     dx, al
; ---- while ( in8( kbStatus ) & kbFull ) {
.L8:
        mov     dx, 100
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        and     ax, 1
        test    ax, ax
        jnz     .L11
        jmp     .L10
.L11:
; ---- code = in8( kbData )
        mov     dx, 96
        in      al, dx
        mov     [t_kbd__code], al           ; u8 -> u8, no widening
.L9:
        jmp     .L8
.L10:
        ret

; ============================================== bool anyKeyDown ====

t_kbd__anyKeyDown:
; ---- local bool anyKeyDown() => (
; ---- isEsc ||
; ---- isUp1 || isDown1 || isLeft1 || isRight1 ||
; ---- isUp2 || isDown2 || isLeft2 || isRight2
; ---- )
        mov     al, [isEsc]
        test    al, al
        jz      .L15
        jmp     .L14
.L15:
        mov     al, [isUp1]
        test    al, al
        jz      .L16
        jmp     .L14
.L16:
        mov     al, [isDown1]
        test    al, al
        jz      .L17
        jmp     .L14
.L17:
        mov     al, [isLeft1]
        test    al, al
        jz      .L18
        jmp     .L14
.L18:
        mov     al, [isRight1]
        test    al, al
        jz      .L19
        jmp     .L14
.L19:
        mov     al, [isUp2]
        test    al, al
        jz      .L20
        jmp     .L14
.L20:
        mov     al, [isDown2]
        test    al, al
        jz      .L21
        jmp     .L14
.L21:
        mov     al, [isLeft2]
        test    al, al
        jz      .L22
        jmp     .L14
.L22:
        mov     al, [isRight2]
        test    al, al
        jnz     .L23
        jmp     .L12
.L23:
.L14:
        mov     ax, 1
        jmp     .L13
.L12:
        xor     ax, ax
.L13:
        mov     [t_kbd__anyKeyDown__ret], al; narrowed to bool
        ret

; ============================================== sub keyboardEnd ====

keyboardEnd:
; ---- while ( anyKeyDown() ) {
.L24:
        call    t_kbd__anyKeyDown
        mov     al, [t_kbd__anyKeyDown__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L27
        jmp     .L26
.L27:
; ---- pollKeyboard()
        call    pollKeyboard
.L25:
        jmp     .L24
.L26:
; ---- while ( in8( kbStatus ) & kbFull ) {
.L28:
        mov     dx, 100
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        and     ax, 1
        test    ax, ax
        jnz     .L31
        jmp     .L30
.L31:
; ---- code = in8( kbData )
        mov     dx, 96
        in      al, dx
        mov     [t_kbd__code], al           ; u8 -> u8, no widening
.L29:
        jmp     .L28
.L30:
; ---- out8( picMask, in8( picMask ) & ~irqKbd )
        mov     dx, 33
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        and     ax, -3
        mov     dx, 33
        out     dx, al
        ret

; ============================================== sub applyKey ====

t_kbd__applyKey:
; ---- if ( key == scW ) isUp1 = pressed
        mov     al, [t_kbd__applyKey__key]
        cmp     al, 17                      ; byte operands, no widening
        je      .L34                        ; unsigned ==
        jmp     .L32
.L34:
        mov     al, [t_kbd__applyKey__pressed]
        mov     [isUp1], al                 ; bool -> bool, no widening
        jmp     .L33
.L32:
; ---- else if ( key == scS ) isDown1 = pressed
        mov     al, [t_kbd__applyKey__key]
        cmp     al, 31                      ; byte operands, no widening
        je      .L37                        ; unsigned ==
        jmp     .L35
.L37:
        mov     al, [t_kbd__applyKey__pressed]
        mov     [isDown1], al               ; bool -> bool, no widening
        jmp     .L36
.L35:
; ---- else if ( key == scA ) isLeft1 = pressed
        mov     al, [t_kbd__applyKey__key]
        cmp     al, 30                      ; byte operands, no widening
        je      .L40                        ; unsigned ==
        jmp     .L38
.L40:
        mov     al, [t_kbd__applyKey__pressed]
        mov     [isLeft1], al               ; bool -> bool, no widening
        jmp     .L39
.L38:
; ---- else if ( key == scD ) isRight1 = pressed
        mov     al, [t_kbd__applyKey__key]
        cmp     al, 32                      ; byte operands, no widening
        je      .L43                        ; unsigned ==
        jmp     .L41
.L43:
        mov     al, [t_kbd__applyKey__pressed]
        mov     [isRight1], al              ; bool -> bool, no widening
        jmp     .L42
.L41:
; ---- else if ( key == scUp ) isUp2 = pressed
        mov     al, [t_kbd__applyKey__key]
        cmp     al, 72                      ; byte operands, no widening
        je      .L46                        ; unsigned ==
        jmp     .L44
.L46:
        mov     al, [t_kbd__applyKey__pressed]
        mov     [isUp2], al                 ; bool -> bool, no widening
        jmp     .L45
.L44:
; ---- else if ( key == scDown ) isDown2 = pressed
        mov     al, [t_kbd__applyKey__key]
        cmp     al, 80                      ; byte operands, no widening
        je      .L49                        ; unsigned ==
        jmp     .L47
.L49:
        mov     al, [t_kbd__applyKey__pressed]
        mov     [isDown2], al               ; bool -> bool, no widening
        jmp     .L48
.L47:
; ---- else if ( key == scLeft ) isLeft2 = pressed
        mov     al, [t_kbd__applyKey__key]
        cmp     al, 75                      ; byte operands, no widening
        je      .L52                        ; unsigned ==
        jmp     .L50
.L52:
        mov     al, [t_kbd__applyKey__pressed]
        mov     [isLeft2], al               ; bool -> bool, no widening
        jmp     .L51
.L50:
; ---- else if ( key == scRight ) isRight2 = pressed
        mov     al, [t_kbd__applyKey__key]
        cmp     al, 77                      ; byte operands, no widening
        je      .L55                        ; unsigned ==
        jmp     .L53
.L55:
        mov     al, [t_kbd__applyKey__pressed]
        mov     [isRight2], al              ; bool -> bool, no widening
        jmp     .L54
.L53:
; ---- else if ( key == scEsc ){
        mov     al, [t_kbd__applyKey__key]
        cmp     al, 1                       ; byte operands, no widening
        je      .L58                        ; unsigned ==
        jmp     .L56
.L58:
; ---- isEsc = pressed
        mov     al, [t_kbd__applyKey__pressed]
        mov     [isEsc], al                 ; bool -> bool, no widening
; ---- if( pressed ) wasEsc = true
        mov     al, [t_kbd__applyKey__pressed]
        test    al, al
        jnz     .L61
        jmp     .L59
.L61:
        mov     byte [wasEsc], 1
.L59:
.L56:
.L54:
.L51:
.L48:
.L45:
.L42:
.L39:
.L36:
.L33:
        ret

; ============================================== sub ioDelay ====

t_kbd__ioDelay:
; ---- local sub ioDelay => out8( 0x80, 0 )
        xor     ax, ax                      ; 0
        mov     dx, 128
        out     dx, al
        ret

; ============================================== sub pollKeyboard ====

pollKeyboard:
; ---- while ( true ) {
.L62:
; ---- status = in8( kbStatus )
        mov     dx, 100
        in      al, dx
        mov     [t_kbd__status], al         ; u8 -> u8, no widening
; ---- ioDelay()
        call    t_kbd__ioDelay
; ---- if ( ( status & kbFull ) == 0 ) break
        mov     al, [t_kbd__status]
        xor     ah, ah                      ; u8 -> u16
        and     ax, 1
        test    ax, ax
        je      .L67                        ; unsigned ==
        jmp     .L65
.L67:
        jmp     .L64
.L65:
; ---- code = in8( kbData )
        mov     dx, 96
        in      al, dx
        mov     [t_kbd__code], al           ; u8 -> u8, no widening
; ---- ioDelay()
        call    t_kbd__ioDelay
; ---- down = code < 0x80
        mov     al, [t_kbd__code]
        cmp     al, 128                     ; byte operands, no widening
        jb      .L70                        ; unsigned <
        jmp     .L68
.L70:
        mov     ax, 1
        jmp     .L69
.L68:
        xor     ax, ax
.L69:
        mov     [t_kbd__down], al           ; narrowed to bool
; ---- applyKey( code & 0x7F, down )
        mov     al, [t_kbd__code]
        xor     ah, ah                      ; u8 -> u16
        and     ax, 127
        mov     [t_kbd__applyKey__key], al  ; narrowed to u8
        mov     al, [t_kbd__down]
        mov     [t_kbd__applyKey__pressed], al; bool -> bool, no widening
        call    t_kbd__applyKey
.L63:
        jmp     .L62
.L64:
        ret

; ============================================== sub setPaletteColor ====

t_pal__setPaletteColor:
; ---- _ax = 0x1010
        mov     word [_ax], 4112
; ---- _bx = index
        mov     al, [t_pal__setPaletteColor__index]
        xor     ah, ah                      ; u8 -> u16
        mov     [_bx], ax
; ---- _dh = dac( r )
        mov     al, [t_pal__setPaletteColor__r]
        xor     ah, ah                      ; u8 -> u16
        shr     ax, 1                       ; unsigned >>
        shr     ax, 1
        xor     ah, ah                      ; cast to u8
        mov     [_dh], al                   ; narrowed to u8
; ---- _ch = dac( g )
        mov     al, [t_pal__setPaletteColor__g]
        xor     ah, ah                      ; u8 -> u16
        shr     ax, 1                       ; unsigned >>
        shr     ax, 1
        xor     ah, ah                      ; cast to u8
        mov     [_ch], al                   ; narrowed to u8
; ---- _cl = dac( b )
        mov     al, [t_pal__setPaletteColor__b]
        xor     ah, ah                      ; u8 -> u16
        shr     ax, 1                       ; unsigned >>
        shr     ax, 1
        xor     ah, ah                      ; cast to u8
        mov     [_cl], al                   ; narrowed to u8
; ---- int 0x10
        call    int10
        ret

; ============================================== sub initPal ====

initPal:
; ---- for( i = 0; i < palSize; i++ ){
        mov     byte [t_pal__i], 0
.L71:
        mov     al, [t_pal__i]
        cmp     al, 8                       ; byte operands, no widening
        jb      .L74                        ; unsigned <
        jmp     .L73
.L74:
; ---- pIndex = i * 3
        mov     al, [t_pal__i]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 3
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     [t_pal__pIndex], al         ; narrowed to u8
; ---- setPaletteColor(
; ---- i, palette[ pIndex ], palette[ pIndex + 1 ], palette[ pIndex + 2 ]
; ---- )
        mov     al, [t_pal__i]
        mov     [t_pal__setPaletteColor__index], al; u8 -> u8, no widening
        mov     al, [t_pal__pIndex]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [t_pal__palette + bx]
        mov     [t_pal__setPaletteColor__r], al; u8 -> u8, no widening
        mov     al, [t_pal__pIndex]
        xor     ah, ah                      ; u8 -> u16
        inc     ax
        mov     bx, ax
        mov     al, [t_pal__palette + bx]
        mov     [t_pal__setPaletteColor__g], al; u8 -> u8, no widening
        mov     al, [t_pal__pIndex]
        xor     ah, ah                      ; u8 -> u16
        add     ax, 2
        mov     bx, ax
        mov     al, [t_pal__palette + bx]
        mov     [t_pal__setPaletteColor__b], al; u8 -> u8, no widening
        call    t_pal__setPaletteColor
.L72:
        inc     byte [t_pal__i]
        jmp     .L71
.L73:
        ret

; ============================================== sub waitRetrace ====

t_scr__waitRetrace:
; ---- while ( in8( vgaStatus ) & vgaVRetrace ) { }
.L75:
        mov     dx, 986
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        and     ax, 8
        test    ax, ax
        jnz     .L78
        jmp     .L77
.L78:
.L76:
        jmp     .L75
.L77:
; ---- while ( ( in8( vgaStatus ) & vgaVRetrace ) == 0 ) { }
.L79:
        mov     dx, 986
        in      al, dx
        xor     ah, ah                      ; u8 -> u16
        and     ax, 8
        test    ax, ax
        je      .L82                        ; unsigned ==
        jmp     .L81
.L82:
.L80:
        jmp     .L79
.L81:
        ret

; ============================================== sub waitFrame ====

waitFrame:
; ---- waitRetrace()
        call    t_scr__waitRetrace
; ---- waitRetrace()
        call    t_scr__waitRetrace
        ret

; ============================================== sub saveMode ====

saveMode:
; ---- _ah = 0x0F
        mov     byte [_ah], 15
; ---- int 0x10
        call    int10
; ---- savedMode = _al & 0x7F
        mov     al, [_al]
        xor     ah, ah                      ; u8 -> u16
        and     ax, 127
        mov     [t_scr__savedMode], al      ; narrowed to u8
        ret

; ============================================== sub restoreMode ====

restoreMode:
; ---- _ah = 0x00
        mov     byte [_ah], 0
; ---- _al = savedMode
        mov     al, [t_scr__savedMode]
        mov     [_al], al                   ; u8 -> u8, no widening
; ---- int 0x10
        call    int10
        ret

; ============================================== sub mode13 ====

mode13:
; ---- _ax = 0x0013
        mov     word [_ax], 19
; ---- int 0x10
        call    int10
        ret

; ============================================== sub setPixel ====

setPixel:
; ---- at = pxIndex( x << 1, y << 1 )
        mov     ax, [setPixel__y]
        shl     ax, 1
        mov     bx, 320
        mul     bx                          ; low 16 bits are sign-agnostic
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [setPixel__x]
        shl     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [t_scr__at], ax
; ---- pixels[ at ] = color
        mov     al, [setPixel__color]
        push    ax                          ; save value while computing the index
        mov     ax, [t_scr__at]
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pixels
        mov     es, dx
        pop     ax
        mov     [es:bx], al
; ---- pixels[ at + 1 ] = color
        mov     al, [setPixel__color]
        push    ax                          ; save value while computing the index
        mov     ax, [t_scr__at]
        inc     ax
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pixels
        mov     es, dx
        pop     ax
        mov     [es:bx], al
; ---- pixels[ at + screenW ] = color
        mov     al, [setPixel__color]
        push    ax                          ; save value while computing the index
        mov     ax, [t_scr__at]
        add     ax, 320
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pixels
        mov     es, dx
        pop     ax
        mov     [es:bx], al
; ---- pixels[ at + screenWNext ] = color
        mov     al, [setPixel__color]
        push    ax                          ; save value while computing the index
        mov     ax, [t_scr__at]
        add     ax, 321
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pixels
        mov     es, dx
        pop     ax
        mov     [es:bx], al
        ret

; ============================================== sub drawLineHorizontal ====

drawLineHorizontal:
; ---- for( x = x1; x <= x2; x++ ){
        mov     al, [drawLineHorizontal__x1]
        xor     ah, ah                      ; u8 -> u16
        mov     [t_scr__x], ax
.L83:
        mov     ax, [t_scr__x]
        mov     bl, [drawLineHorizontal__x2]
        xor     bh, bh                      ; u8 -> u16
        cmp     ax, bx
        jbe     .L86                        ; unsigned <=
        jmp     .L85
.L86:
; ---- setPixel( x, y, color )
        mov     ax, [t_scr__x]
        mov     [setPixel__x], ax
        mov     al, [drawLineHorizontal__y]
        xor     ah, ah                      ; u8 -> u16
        mov     [setPixel__y], ax
        mov     al, [drawLineHorizontal__color]
        mov     [setPixel__color], al       ; u8 -> u8, no widening
        call    setPixel
.L84:
        inc     word [t_scr__x]
        jmp     .L83
.L85:
        ret

; ============================================== sub drawLineVertical ====

drawLineVertical:
; ---- for( y = y1; y <= y2; y++ ){
        mov     al, [drawLineVertical__y1]
        xor     ah, ah                      ; u8 -> u16
        mov     [t_scr__y], ax
.L87:
        mov     ax, [t_scr__y]
        mov     bl, [drawLineVertical__y2]
        xor     bh, bh                      ; u8 -> u16
        cmp     ax, bx
        jbe     .L90                        ; unsigned <=
        jmp     .L89
.L90:
; ---- setPixel( x, y, color )
        mov     al, [drawLineVertical__x]
        xor     ah, ah                      ; u8 -> u16
        mov     [setPixel__x], ax
        mov     ax, [t_scr__y]
        mov     [setPixel__y], ax
        mov     al, [drawLineVertical__color]
        mov     [setPixel__color], al       ; u8 -> u8, no widening
        call    setPixel
.L88:
        inc     word [t_scr__y]
        jmp     .L87
.L89:
        ret

; ============================================== sub drawBackground ====

drawBackground:
; ---- for( dy = 0; dy < scoreTopWord; dy++ ){
        mov     word [dy_], 0
.L91:
        mov     ax, [dy_]
        cmp     ax, 26880
        jb      .L94                        ; unsigned <
        jmp     .L93
.L94:
; ---- pxwords[ dy ] = color
        mov     ax, [drawBackground__color]
        push    ax                          ; save value while computing the index
        mov     ax, [dy_]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pxwords
        mov     es, dx
        pop     ax
        mov     [es:bx], ax
.L92:
        inc     word [dy_]
        jmp     .L91
.L93:
; ---- for( dy = scoreTopWord; dy < screenWord; dy++ ){
        mov     word [dy_], 26880
.L95:
        mov     ax, [dy_]
        cmp     ax, 32000
        jb      .L98                        ; unsigned <
        jmp     .L97
.L98:
; ---- pxwords[ dy ] = blackW
        mov     ax, [dy_]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     dx, 0xA000                  ; segment of pxwords
        mov     es, dx
        mov     word [es:bx], 771
.L96:
        inc     word [dy_]
        jmp     .L95
.L97:
        ret

; ============================================== sub drawPlayfield ====

drawPlayfield:
; ---- drawLineHorizontal( playTop, playLeft, playRight, green )
        mov     byte [drawLineHorizontal__y], 9
        mov     byte [drawLineHorizontal__x1], 40
        mov     byte [drawLineHorizontal__x2], 118
        mov     byte [drawLineHorizontal__color], 5
        call    drawLineHorizontal
; ---- drawLineHorizontal( playBottom, playLeft, playRight, green )
        mov     byte [drawLineHorizontal__y], 80
        mov     byte [drawLineHorizontal__x1], 40
        mov     byte [drawLineHorizontal__x2], 118
        mov     byte [drawLineHorizontal__color], 5
        call    drawLineHorizontal
; ---- drawNet()
        call    drawNet
        ret

; ============================================== sub drawNet ====

drawNet:
; ---- for( net = 0; net < 5; net++ ){
        mov     byte [net], 0
.L99:
        mov     al, [net]
        cmp     al, 5                       ; byte operands, no widening
        jb      .L102                       ; unsigned <
        jmp     .L101
.L102:
; ---- netY = playTop + 3 + net * 14
        mov     ax, 12
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [net]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 14
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [netY], al                  ; narrowed to u8
; ---- drawLineVertical( centerX, netY, netY + 8, green )
        mov     byte [drawLineVertical__x], 79
        mov     al, [netY]
        mov     [drawLineVertical__y1], al  ; u8 -> u8, no widening
        mov     al, [netY]
        xor     ah, ah                      ; u8 -> u16
        add     ax, 8
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     byte [drawLineVertical__color], 5
        call    drawLineVertical
.L100:
        inc     byte [net]
        jmp     .L99
.L101:
        ret

; ============================================== sub drawPaddle ====

drawPaddle:
; ---- subPxY = subgridToPx( playTop, player[ pi ].y )
        mov     ax, 10
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [drawPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxY], ax
; ---- subPxY2 = subPxY + paddleH - 1
        mov     ax, [subPxY]
        add     ax, 9
        dec     ax
        mov     [subPxY2], ax
; ---- drawLineVertical( paddleX[ pi ], subPxY, subPxY2, paddleColor[ pi ] )
        mov     al, [drawPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [paddleX + bx]
        mov     [drawLineVertical__x], al   ; u8 -> u8, no widening
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     al, [drawPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [paddleColor + bx]
        mov     [drawLineVertical__color], al; u8 -> u8, no widening
        call    drawLineVertical
        ret

; ============================================== sub clearPaddle ====

clearPaddle:
; ---- subPxY = subgridToPx( playTop, player[ pi ].oldY )
        mov     ax, 10
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [clearPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__oldY + bx]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxY], ax
; ---- subPxY2 = subPxY + paddleH - 1
        mov     ax, [subPxY]
        add     ax, 9
        dec     ax
        mov     [subPxY2], ax
; ---- drawLineVertical( paddleX[ pi ], subPxY, subPxY2, lightGreen )
        mov     al, [clearPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [paddleX + bx]
        mov     [drawLineVertical__x], al   ; u8 -> u8, no widening
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     byte [drawLineVertical__color], 1
        call    drawLineVertical
        ret

; ============================================== sub drawBall ====

drawBall:
; ---- subPxX = subgridToPx( playLeft, ballX )
        mov     ax, 41
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [ballX]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxX], ax
; ---- subPxY = subgridToPx( playTop, ballY )
        mov     ax, 10
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [ballY]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxY], ax
; ---- subPxY2 = subPxY + ballH - 1
        mov     ax, [subPxY]
        add     ax, 3
        dec     ax
        mov     [subPxY2], ax
; ---- drawLineVertical( subPxX, subPxY, subPxY2, ballColor )
        mov     ax, [subPxX]
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     al, [ballColor]
        mov     [drawLineVertical__color], al; u8 -> u8, no widening
        call    drawLineVertical
; ---- drawLineVertical( subPxX + 1, subPxY, subPxY2, ballColor )
        mov     ax, [subPxX]
        inc     ax
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     al, [ballColor]
        mov     [drawLineVertical__color], al; u8 -> u8, no widening
        call    drawLineVertical
; ---- drawLineVertical( subPxX + 2, subPxY, subPxY2, ballColor )
        mov     ax, [subPxX]
        add     ax, 2
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     al, [ballColor]
        mov     [drawLineVertical__color], al; u8 -> u8, no widening
        call    drawLineVertical
        ret

; ============================================== sub clearBall ====

clearBall:
; ---- subPxX = subgridToPx( playLeft, oBallX )
        mov     ax, 41
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [oBallX]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxX], ax
; ---- subPxY = subgridToPx( playTop, oBallY )
        mov     ax, 10
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [oBallY]
        sar     ax, 1                       ; signed >>
        sar     ax, 1
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [subPxY], ax
; ---- subPxY2 = subPxY + ballH - 1
        mov     ax, [subPxY]
        add     ax, 3
        dec     ax
        mov     [subPxY2], ax
; ---- drawLineVertical( subPxX, subPxY, subPxY2, lightGreen )
        mov     ax, [subPxX]
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     byte [drawLineVertical__color], 1
        call    drawLineVertical
; ---- drawLineVertical( subPxX + 1, subPxY, subPxY2, lightGreen )
        mov     ax, [subPxX]
        inc     ax
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     byte [drawLineVertical__color], 1
        call    drawLineVertical
; ---- drawLineVertical( subPxX + 2, subPxY, subPxY2, lightGreen )
        mov     ax, [subPxX]
        add     ax, 2
        mov     [drawLineVertical__x], al   ; narrowed to u8
        mov     ax, [subPxY]
        mov     [drawLineVertical__y1], al  ; narrowed to u8
        mov     ax, [subPxY2]
        mov     [drawLineVertical__y2], al  ; narrowed to u8
        mov     byte [drawLineVertical__color], 1
        call    drawLineVertical
        ret

; ============================================== sub drawSprite ====

drawSprite:
; ---- tile = index * spriteSize
        mov     al, [drawSprite__index]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 25
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     [tile], ax
; ---- for( j = 0; j < spriteH; j++ ){
        mov     byte [j], 0
.L103:
        mov     al, [j]
        cmp     al, 5                       ; byte operands, no widening
        jb      .L106                       ; unsigned <
        jmp     .L105
.L106:
; ---- for( i = 0; i < spriteW; i++ ){
        mov     byte [i], 0
.L107:
        mov     al, [i]
        cmp     al, 5                       ; byte operands, no widening
        jb      .L110                       ; unsigned <
        jmp     .L109
.L110:
; ---- setPixel( i + dx, j + dy, textSprites[ tile ] )
        mov     al, [i]
        xor     ah, ah                      ; u8 -> u16
        mov     bl, [drawSprite__dx]
        xor     bh, bh                      ; u8 -> u16
        add     ax, bx
        mov     [setPixel__x], ax
        mov     al, [j]
        xor     ah, ah                      ; u8 -> u16
        mov     bl, [drawSprite__dy]
        xor     bh, bh                      ; u8 -> u16
        add     ax, bx
        mov     [setPixel__y], ax
        mov     ax, [tile]
        mov     bx, ax
        mov     al, [textSprites + bx]
        mov     [setPixel__color], al       ; u8 -> u8, no widening
        call    setPixel
; ---- tile++
        inc     word [tile]
.L108:
        inc     byte [i]
        jmp     .L107
.L109:
.L104:
        inc     byte [j]
        jmp     .L103
.L105:
        ret

; ============================================== sub drawScore ====

drawScore:
; ---- if( player[ pi ].score < 10 ){
        mov     al, [drawScore__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__score + bx]
        cmp     al, 10                      ; byte operands, no widening
        jb      .L113                       ; unsigned <
        jmp     .L111
.L113:
; ---- digitTens = 0
        mov     byte [digitTens], 0
; ---- digitOnes = player[ pi ].score
        mov     al, [drawScore__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__score + bx]
        mov     [digitOnes], al             ; u8 -> u8, no widening
        jmp     .L112
.L111:
; ---- digitTens = 1
        mov     byte [digitTens], 1
; ---- digitOnes = player[ pi ].score - 10
        mov     al, [drawScore__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__score + bx]
        xor     ah, ah                      ; u8 -> u16
        sub     ax, 10
        mov     [digitOnes], al             ; narrowed to u8
.L112:
; ---- drawSprite( digitTens, scoreXTens[ pi ], scoreY )
        mov     al, [digitTens]
        mov     [drawSprite__index], al     ; u8 -> u8, no widening
        mov     al, [drawScore__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [scoreXTens + bx]
        mov     [drawSprite__dx], al        ; u8 -> u8, no widening
        mov     byte [drawSprite__dy], 85
        call    drawSprite
; ---- drawSprite( digitOnes, scoreXOnes[ pi ], scoreY )
        mov     al, [digitOnes]
        mov     [drawSprite__index], al     ; u8 -> u8, no widening
        mov     al, [drawScore__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [scoreXOnes + bx]
        mov     [drawSprite__dx], al        ; u8 -> u8, no widening
        mov     byte [drawSprite__dy], 85
        call    drawSprite
        ret

; ============================================== sub movePaddle ====

movePaddle:
; ---- if ( up || down ) {
        mov     al, [movePaddle__up]
        test    al, al
        jz      .L117
        jmp     .L116
.L117:
        mov     al, [movePaddle__down]
        test    al, al
        jnz     .L118
        jmp     .L114
.L118:
.L116:
; ---- if ( up ) player[ pi ].y -= player[ pi ].speed
        mov     al, [movePaddle__up]
        test    al, al
        jnz     .L121
        jmp     .L119
.L121:
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__speed + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        sub     ax, bx
        push    ax                          ; save value while computing the index
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [player__y + bx], ax
.L119:
; ---- if ( down ) player[ pi ].y += player[ pi ].speed
        mov     al, [movePaddle__down]
        test    al, al
        jnz     .L124
        jmp     .L122
.L124:
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__speed + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        push    ax                          ; save value while computing the index
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [player__y + bx], ax
.L122:
; ---- if ( player[ pi ].y < 0 ) player[ pi ].y = 0
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        test    ax, ax
        jl      .L127                       ; signed <
        jmp     .L125
.L127:
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [player__y + bx], 0
.L125:
; ---- if ( player[ pi ].y > paddleYMax ) player[ pi ].y = paddleYMax
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        cmp     ax, 244
        jg      .L130                       ; signed >
        jmp     .L128
.L130:
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [player__y + bx], 244
.L128:
; ---- if ( player[ pi ].speed < paddleSpeedMax ) {
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__speed + bx]
        cmp     al, 16                      ; byte operands, no widening
        jb      .L133                       ; unsigned <
        jmp     .L131
.L133:
; ---- player[ pi ].speed += paddleSpeedStep
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__speed + bx]
        xor     ah, ah                      ; u8 -> u16
        add     ax, 2
        push    ax                          ; save value while computing the index
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        mov     [player__speed + bx], al
.L131:
        jmp     .L115
.L114:
; ---- player[ pi ].speed = 0
        mov     al, [movePaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     byte [player__speed + bx], 0
.L115:
        ret

; ============================================== sub input ====

input:
; ---- pollKeyboard()
        call    pollKeyboard
; ---- if( wasEsc ){
        mov     al, [wasEsc]
        test    al, al
        jnz     .L136
        jmp     .L134
.L136:
; ---- isRunning = false
        mov     byte [isRunning], 0
; ---- return
        ret
.L134:
; ---- if( isWinScreen ){
        mov     al, [isWinScreen]
        test    al, al
        jnz     .L139
        jmp     .L137
.L139:
; ---- if( isLeft1 || isLeft2 || isRight1 || isRight2 ){
        mov     al, [isLeft1]
        test    al, al
        jz      .L143
        jmp     .L142
.L143:
        mov     al, [isLeft2]
        test    al, al
        jz      .L144
        jmp     .L142
.L144:
        mov     al, [isRight1]
        test    al, al
        jz      .L145
        jmp     .L142
.L145:
        mov     al, [isRight2]
        test    al, al
        jnz     .L146
        jmp     .L140
.L146:
.L142:
; ---- start()
        call    start
.L140:
; ---- return
        ret
.L137:
; ---- movePaddle( 0, isUp1, isDown1 )
        mov     byte [movePaddle__pi], 0
        mov     al, [isUp1]
        mov     [movePaddle__up], al        ; bool -> bool, no widening
        mov     al, [isDown1]
        mov     [movePaddle__down], al      ; bool -> bool, no widening
        call    movePaddle
; ---- movePaddle( 1, isUp2, isDown2 )
        mov     byte [movePaddle__pi], 1
        mov     al, [isUp2]
        mov     [movePaddle__up], al        ; bool -> bool, no widening
        mov     al, [isDown2]
        mov     [movePaddle__down], al      ; bool -> bool, no widening
        call    movePaddle
        ret

; ============================================== sub setBallSpeedY ====

setBallSpeedY:
; ---- if ( yOffset < angleZone1 ) ballSpeedY = -ballSpeedY3
        mov     ax, [setBallSpeedY__yOffset]
        cmp     ax, 6
        jl      .L149                       ; signed <
        jmp     .L147
.L149:
        mov     word [ballSpeedY], 65527
        jmp     .L148
.L147:
; ---- else if ( yOffset < angleZone2 ) ballSpeedY = -ballSpeedY2
        mov     ax, [setBallSpeedY__yOffset]
        cmp     ax, 12
        jl      .L152                       ; signed <
        jmp     .L150
.L152:
        mov     word [ballSpeedY], 65530
        jmp     .L151
.L150:
; ---- else if ( yOffset < angleZone3 ) ballSpeedY = -ballSpeedY1
        mov     ax, [setBallSpeedY__yOffset]
        cmp     ax, 18
        jl      .L155                       ; signed <
        jmp     .L153
.L155:
        mov     word [ballSpeedY], 65533
        jmp     .L154
.L153:
; ---- else if ( yOffset < angleZone4 ) ballSpeedY = 0
        mov     ax, [setBallSpeedY__yOffset]
        cmp     ax, 29
        jl      .L158                       ; signed <
        jmp     .L156
.L158:
        mov     word [ballSpeedY], 0
        jmp     .L157
.L156:
; ---- else if ( yOffset < angleZone5 ) ballSpeedY = ballSpeedY1
        mov     ax, [setBallSpeedY__yOffset]
        cmp     ax, 35
        jl      .L161                       ; signed <
        jmp     .L159
.L161:
        mov     word [ballSpeedY], 3
        jmp     .L160
.L159:
; ---- else if ( yOffset < angleZone6 ) ballSpeedY = ballSpeedY2
        mov     ax, [setBallSpeedY__yOffset]
        cmp     ax, 41
        jl      .L164                       ; signed <
        jmp     .L162
.L164:
        mov     word [ballSpeedY], 6
        jmp     .L163
.L162:
; ---- else ballSpeedY = ballSpeedY3
        mov     word [ballSpeedY], 9
.L163:
.L160:
.L157:
.L154:
.L151:
.L148:
        ret

; ============================================== sub scorePoint ====

scorePoint:
; ---- player[ pi ].score++
        mov     al, [scorePoint__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        inc     byte [player__score + bx]
; ---- drawScore( pi )
        mov     al, [scorePoint__pi]
        mov     [drawScore__pi], al         ; u8 -> u8, no widening
        call    drawScore
; ---- if ( player[ pi ].score == winScore ) {
        mov     al, [scorePoint__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [player__score + bx]
        cmp     al, 11                      ; byte operands, no widening
        je      .L167                       ; unsigned ==
        jmp     .L165
.L167:
; ---- win( pi )
        mov     al, [scorePoint__pi]
        mov     [win__pi], al               ; u8 -> u8, no widening
        call    win
        jmp     .L166
.L165:
; ---- ballPlayer = pi
        mov     al, [scorePoint__pi]
        mov     [ballPlayer], al            ; u8 -> u8, no widening
; ---- serve()
        call    serve
.L166:
        ret

; ============================================== sub hitPaddle ====

hitPaddle:
; ---- yOffset = ballY - player[ pi ].y + hitLead
        mov     ax, [ballY]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [hitPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        mov     bx, ax
        pop     ax
        sub     ax, bx
        add     ax, 11
        mov     [hitPaddle__yOffset], ax
; ---- if ( yOffset < 0 || yOffset >= hitWindow ) {
        mov     ax, [hitPaddle__yOffset]
        test    ax, ax
        jge     .L171                       ; signed <
        jmp     .L170
.L171:
        mov     ax, [hitPaddle__yOffset]
        cmp     ax, 47
        jge     .L172                       ; signed >=
        jmp     .L168
.L172:
.L170:
; ---- scorePoint( 1 - pi )
        mov     ax, 1
        mov     bl, [hitPaddle__pi]
        xor     bh, bh                      ; u8 -> u16
        sub     ax, bx
        mov     [scorePoint__pi], al        ; narrowed to u8
        call    scorePoint
; ---- return
        ret
.L168:
; ---- ballX = serveX[ pi ]
        mov     al, [hitPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [serveX + bx]
        mov     [ballX], ax
; ---- setBallSpeedY( yOffset )
        mov     ax, [hitPaddle__yOffset]
        mov     [setBallSpeedY__yOffset], ax
        call    setBallSpeedY
; ---- if ( iabs( ballSpeedX ) < ballSpeedXMax ) {
        mov     ax, [ballSpeedX]
        test    ax, ax
        jl      .L177                       ; signed <
        jmp     .L175
.L177:
        mov     ax, [ballSpeedX]
        neg     ax
        jmp     .L176
.L175:
        mov     ax, [ballSpeedX]
.L176:
        cmp     ax, 9
        jl      .L178                       ; signed <
        jmp     .L173
.L178:
; ---- volleyCount++
        inc     byte [volleyCount]
; ---- if ( volleyCount == volleyTarget ) {
        mov     al, [volleyCount]
        cmp     al, 3                       ; byte operands, no widening
        je      .L181                       ; unsigned ==
        jmp     .L179
.L181:
; ---- volleyCount = 0
        mov     byte [volleyCount], 0
; ---- if ( ballSpeedX > 0 ) ballSpeedX += ballSpeedStep
        mov     ax, [ballSpeedX]
        test    ax, ax
        jg      .L184                       ; signed >
        jmp     .L182
.L184:
        mov     ax, [ballSpeedX]
        add     ax, 3
        mov     [ballSpeedX], ax
        jmp     .L183
.L182:
; ---- else ballSpeedX -= ballSpeedStep
        mov     ax, [ballSpeedX]
        sub     ax, 3
        mov     [ballSpeedX], ax
.L183:
.L179:
.L173:
; ---- ballSpeedX = -ballSpeedX
        mov     ax, [ballSpeedX]
        neg     ax
        mov     [ballSpeedX], ax
; ---- ballPlayer = pi
        mov     al, [hitPaddle__pi]
        mov     [ballPlayer], al            ; u8 -> u8, no widening
; ---- ballColor = paddleColor[ pi ]
        mov     al, [hitPaddle__pi]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [paddleColor + bx]
        mov     [ballColor], al             ; u8 -> u8, no widening
        ret

; ============================================== sub update ====

update:
; ---- if( isWinScreen ) return
        mov     al, [isWinScreen]
        test    al, al
        jnz     .L187
        jmp     .L185
.L187:
        ret
.L185:
; ---- ballX += ballSpeedX
        mov     ax, [ballX]
        mov     bx, [ballSpeedX]
        add     ax, bx
        mov     [ballX], ax
; ---- ballY += ballSpeedY
        mov     ax, [ballY]
        mov     bx, [ballSpeedY]
        add     ax, bx
        mov     [ballY], ax
; ---- if( ballY < 0 ){
        mov     ax, [ballY]
        test    ax, ax
        jl      .L190                       ; signed <
        jmp     .L188
.L190:
; ---- ballY = 0
        mov     word [ballY], 0
; ---- ballSpeedY = -ballSpeedY
        mov     ax, [ballSpeedY]
        neg     ax
        mov     [ballSpeedY], ax
        jmp     .L189
.L188:
; ---- } else if( ballY > ballYMax ){
        mov     ax, [ballY]
        cmp     ax, 268
        jg      .L193                       ; signed >
        jmp     .L191
.L193:
; ---- ballY = ballYMax
        mov     word [ballY], 268
; ---- ballSpeedY = -ballSpeedY
        mov     ax, [ballSpeedY]
        neg     ax
        mov     [ballSpeedY], ax
.L191:
.L189:
; ---- if( ballSpeedX > 0 && ballX >= ballXMax ){
        mov     ax, [ballSpeedX]
        test    ax, ax
        jg      .L196                       ; signed >
        jmp     .L194
.L196:
        mov     ax, [ballX]
        cmp     ax, 296
        jge     .L197                       ; signed >=
        jmp     .L194
.L197:
; ---- hitPaddle( rightPlayer )
        mov     byte [hitPaddle__pi], 1
        call    hitPaddle
        jmp     .L195
.L194:
; ---- } else if ( ballSpeedX < 0 && ballX <= 0 ){
        mov     ax, [ballSpeedX]
        test    ax, ax
        jl      .L200                       ; signed <
        jmp     .L198
.L200:
        mov     ax, [ballX]
        test    ax, ax
        jle     .L201                       ; signed <=
        jmp     .L198
.L201:
; ---- hitPaddle( leftPlayer )
        mov     byte [hitPaddle__pi], 0
        call    hitPaddle
.L198:
.L195:
        ret

; ============================================== sub render ====

render:
; ---- if( isWinScreen ) return
        mov     al, [isWinScreen]
        test    al, al
        jnz     .L204
        jmp     .L202
.L204:
        ret
.L202:
; ---- clearBall()
        call    clearBall
; ---- clearPaddle( leftPlayer )
        mov     byte [clearPaddle__pi], 0
        call    clearPaddle
; ---- clearPaddle( rightPlayer )
        mov     byte [clearPaddle__pi], 1
        call    clearPaddle
; ---- if ( oBallX >= netBallXMin && oBallX <= netBallXMax ) drawNet()
        mov     ax, [oBallX]
        cmp     ax, 144
        jge     .L207                       ; signed >=
        jmp     .L205
.L207:
        mov     ax, [oBallX]
        cmp     ax, 155
        jle     .L208                       ; signed <=
        jmp     .L205
.L208:
        call    drawNet
.L205:
; ---- drawBall()
        call    drawBall
; ---- drawPaddle( leftPlayer )
        mov     byte [drawPaddle__pi], 0
        call    drawPaddle
; ---- drawPaddle( rightPlayer )
        mov     byte [drawPaddle__pi], 1
        call    drawPaddle
; ---- player[ leftPlayer ].oldY = player[ leftPlayer ].y
        mov     ax, [player__y]
        mov     [player__oldY], ax
; ---- player[ rightPlayer ].oldY = player[ rightPlayer ].y
        mov     ax, [player__y + 2]
        mov     [player__oldY + 2], ax
; ---- oBallX = ballX
        mov     ax, [ballX]
        mov     [oBallX], ax
; ---- oBallY = ballY
        mov     ax, [ballY]
        mov     [oBallY], ax
        ret

; ============================================== sub tick ====

tick:
; ---- input()
        call    input
; ---- update()
        call    update
; ---- waitFrame()
        call    waitFrame
; ---- render()
        call    render
        ret

; ============================================== sub win ====

win:
; ---- isWinScreen = true
        mov     byte [isWinScreen], 1
; ---- waitFrame()
        call    waitFrame
; ---- drawBackground( winColor[ pi ] )
        mov     al, [win__pi]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [winColor + bx]
        mov     [drawBackground__color], ax
        call    drawBackground
; ---- drawScore( leftPlayer )
        mov     byte [drawScore__pi], 0
        call    drawScore
; ---- drawScore( rightPlayer )
        mov     byte [drawScore__pi], 1
        call    drawScore
        ret

; ============================================== sub serve ====

serve:
; ---- ballSpeedY = 0
        mov     word [ballSpeedY], 0
; ---- volleyCount = 0
        mov     byte [volleyCount], 0
; ---- ballX = serveX[ ballPlayer ]
        mov     al, [ballPlayer]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [serveX + bx]
        mov     [ballX], ax
; ---- ballY = player[ ballPlayer ].y + ballServeOffset
        mov     al, [ballPlayer]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [player__y + bx]
        add     ax, 12
        mov     [ballY], ax
; ---- ballSpeedX = serveSpeedX[ ballPlayer ]
        mov     al, [ballPlayer]
        xor     ah, ah                      ; u8 -> u16
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [serveSpeedX + bx]
        mov     [ballSpeedX], ax
; ---- ballColor = paddleColor[ ballPlayer ]
        mov     al, [ballPlayer]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        mov     al, [paddleColor + bx]
        mov     [ballColor], al             ; u8 -> u8, no widening
        ret

; ============================================== sub start ====

start:
; ---- seedRandom( ticks() )
        call    ticks
        mov     ax, [ticks__ret]
        mov     [seedRandom__s], ax
        call    seedRandom
; ---- isWinScreen = false
        mov     byte [isWinScreen], 0
; ---- player[ leftPlayer ].speed = 0
        mov     byte [player__speed], 0
; ---- player[ leftPlayer ].score = 0
        mov     byte [player__score], 0
; ---- player[ leftPlayer ].y = paddleYHome
        mov     word [player__y], 122
; ---- player[ leftPlayer ].oldY = paddleYHome
        mov     word [player__oldY], 122
; ---- player[ rightPlayer ].speed = 0
        mov     byte [player__speed + 1], 0
; ---- player[ rightPlayer ].score = 0
        mov     byte [player__score + 1], 0
; ---- player[ rightPlayer ].y = paddleYHome
        mov     word [player__y + 2], 122
; ---- player[ rightPlayer ].oldY = paddleYHome
        mov     word [player__oldY + 2], 122
; ---- ballPlayer = randomBelow( len( player ) )
        mov     word [randomBelow__n], 2
        call    randomBelow
        mov     ax, [randomBelow__ret]
        mov     [ballPlayer], al            ; narrowed to u8
; ---- waitFrame()
        call    waitFrame
; ---- drawBackground( lightGreenW )
        mov     word [drawBackground__color], 257
        call    drawBackground
; ---- drawPlayfield()
        call    drawPlayfield
; ---- drawScore( leftPlayer )
        mov     byte [drawScore__pi], 0
        call    drawScore
; ---- drawScore( rightPlayer )
        mov     byte [drawScore__pi], 1
        call    drawScore
; ---- serve()
        call    serve
; ---- oBallX = ballX
        mov     ax, [ballX]
        mov     [oBallX], ax
; ---- oBallY = ballY
        mov     ax, [ballY]
        mov     [oBallY], ax
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int10:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x10
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

int21:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax             dw      0
_al             equ     _ax
_ah             equ     _ax + 1
_bx             dw      0
_bl             equ     _bx
_bh             equ     _bx + 1
_cx             dw      0
_cl             equ     _cx
_ch             equ     _cx + 1
_dx             dw      0
_dl             equ     _dx
_dh             equ     _dx + 1
_si             dw      0
_di             dw      0

; ---- variables ----
rand__randomSeed dw      42        ; u16 = 42
seedRandom__s   dw      0        ; u16
nextRandom__ret dw      0        ; u16
randomBelow__n  dw      0        ; u16
randomBelow__ret dw      0        ; u16
ticks__ret      dw      0        ; u16
isUp1           db      0        ; bool
isDown1         db      0        ; bool
isLeft1         db      0        ; bool
isRight1        db      0        ; bool
isUp2           db      0        ; bool
isDown2         db      0        ; bool
isLeft2         db      0        ; bool
isRight2        db      0        ; bool
isEsc           db      0        ; bool
wasEsc          db      0        ; bool
t_kbd__code     db      0        ; u8
t_kbd__anyKeyDown__ret db      0        ; bool
t_kbd__applyKey__key db      0        ; u8
t_kbd__applyKey__pressed db      0        ; bool
t_kbd__status   db      0        ; u8
t_kbd__down     db      0        ; bool
t_pal__setPaletteColor__index db      0        ; u8
t_pal__setPaletteColor__r db      0        ; u8
t_pal__setPaletteColor__g db      0        ; u8
t_pal__setPaletteColor__b db      0        ; u8
t_pal__i        db      0        ; u8
t_pal__pIndex   db      0        ; u8
t_scr__savedMode db      0        ; u8
t_scr__at       dw      0        ; u16
setPixel__x     dw      0        ; u16
setPixel__y     dw      0        ; u16
setPixel__color db      0        ; u8
t_scr__x        dw      0        ; u16
t_scr__y        dw      0        ; u16
drawLineHorizontal__y db      0        ; u8
drawLineHorizontal__x1 db      0        ; u8
drawLineHorizontal__x2 db      0        ; u8
drawLineHorizontal__color db      0        ; u8
drawLineVertical__x db      0        ; u8
drawLineVertical__y1 db      0        ; u8
drawLineVertical__y2 db      0        ; u8
drawLineVertical__color db      0        ; u8
isWinScreen     db      0        ; bool
isRunning       db      1        ; bool = 1
ballX           dw      0        ; i16
ballY           dw      0        ; i16
oBallX          dw      0        ; i16
oBallY          dw      0        ; i16
ballSpeedX      dw      0        ; i16
ballSpeedY      dw      0        ; i16
ballPlayer      db      0        ; u8
ballColor       db      0        ; u8
volleyCount     db      0        ; u8
dy_             dw      0        ; u16
drawBackground__color dw      0        ; u16
net             db      0        ; u8
netY            db      0        ; u8
subPxX          dw      0        ; i16
subPxY          dw      0        ; i16
subPxY2         dw      0        ; i16
drawPaddle__pi  db      0        ; u8
clearPaddle__pi db      0        ; u8
tile            dw      0        ; u16
i               db      0        ; u8
j               db      0        ; u8
drawSprite__index db      0        ; u8
drawSprite__dx  db      0        ; u8
drawSprite__dy  db      0        ; u8
digitTens       db      0        ; u8
digitOnes       db      0        ; u8
drawScore__pi   db      0        ; u8
movePaddle__pi  db      0        ; u8
movePaddle__up  db      0        ; bool
movePaddle__down db      0        ; bool
setBallSpeedY__yOffset dw      0        ; i16
scorePoint__pi  db      0        ; u8
hitPaddle__pi   db      0        ; u8
win__pi         db      0        ; u8
hitPaddle__yOffset dw      0        ; i16

; ---- arrays ----
scoreXTens      db      ',e'        ; u8[2] const
scoreXOnes      db      '3l'        ; u8[2] const
t_pal__palette  db      224, 224, 244, 145, 255, 166, 206, 208, 255, 16, 16, 16, 255, '1S', 2, 204, ']K?', 243, 252, 252, 252        ; u8[24] const
textSprites     db      7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 3, 3, 3, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7        ; u8[250] const
player__y       times 2 dw 0        ; i16[2]
player__oldY    times 2 dw 0        ; i16[2]
player__score   times 2 db 0        ; u8[2]
player__speed   times 2 db 0        ; u8[2]
paddleX         db      '(v'        ; u8[2] const
paddleColor     db      4, 6        ; u8[2] const
winColor        dw      1028, 1542        ; u16[2] const
serveX          dw      0, 296        ; i16[2] const
serveSpeedX     dw      3, -3        ; i16[2] const

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack         equ     276        ; 20 worst-case + 256 interrupt reserve
_htop           equ     0FFFEh - _hstack

_hsize          dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw          equ     _heap        ; same bytes, u16 view
