; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
ioBase          equ     10
ioZeroChar      equ     48
strEnd          equ     36
maxElements     equ     64
unbounded       equ     65535
alignStart      equ     0
alignCenter     equ     1
u               equ     1
lineHeight      equ     1
border          equ     1
bodyMinW        equ     7
squeezedMinW    equ     8

; =========================================================== entry ====

__entry:
; ---- begin( 72 * u, 24 * lineHeight )
        mov     word [begin__w], 72
        mov     word [begin__h], 24
        call    begin
; ---- buildShell()
        call    buildShell
; ---- closeBox()
        call    closeBox
; ---- dumpBoxes()
        call    dumpBoxes

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub putChar ====

putChar:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _dl = c
        mov     al, [putChar__c]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x21
        call    int21
        ret

; ============================================== sub newline ====

newline:
; ---- putChar(13)
        mov     byte [putChar__c], 13
        call    putChar
; ---- putChar(10)
        mov     byte [putChar__c], 10
        call    putChar
        ret

; ============================================== sub space ====

space:
; ---- sub space => putChar(32)
        mov     byte [putChar__c], 32
        call    putChar
        ret

; ============================================== sub putNumber ====

putNumber:
; ---- if (n == 0) {
        mov     ax, [putNumber__n]
        test    ax, ax
        je      .L3                         ; unsigned ==
        jmp     .L1
.L3:
; ---- putChar(ioZeroChar)
        mov     byte [putChar__c], 48
        call    putChar
; ---- return
        ret
.L1:
; ---- for (i = 0; n > 0; i++) {
        mov     byte [putNumber__i], 0
.L4:
        mov     ax, [putNumber__n]
        test    ax, ax
        ja      .L7                         ; unsigned >
        jmp     .L6
.L7:
; ---- digits[i] = u8(n % ioBase) + ioZeroChar
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        add     ax, 48
        push    ax                          ; save value while computing the index
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        mov     [putNumber__digits + bx], al
; ---- n /= ioBase
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     [putNumber__n], ax
.L5:
        inc     byte [putNumber__i]
        jmp     .L4
.L6:
; ---- for (; i > 0; i--) {
.L8:
        mov     al, [putNumber__i]
        test    al, al
        ja      .L11                        ; unsigned >
        jmp     .L10
.L11:
; ---- putChar(digits[i - 1])
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        dec     ax
        mov     bx, ax
        mov     al, [putNumber__digits + bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
.L9:
        dec     byte [putNumber__i]
        jmp     .L8
.L10:
        ret

; ============================================== u16 strLen ====

strLen:
; ---- n = 0
        mov     word [strLen__n], 0
; ---- while ( peek8( at + n ) != strEnd ) {
.L12:
        mov     ax, [strLen__at]
        mov     bx, [strLen__n]
        add     ax, bx
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        cmp     al, 36                      ; byte operands, no widening
        jne     .L15                        ; unsigned !=
        jmp     .L14
.L15:
; ---- n++
        inc     word [strLen__n]
.L13:
        jmp     .L12
.L14:
; ---- return n
        mov     ax, [strLen__n]
        mov     [strLen__ret], ax
        ret

; ============================================== sub fitSize ====

fitSize:
; ---- n = el[i].childCount
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__childCount + bx]
        mov     [fitSize__n], ax
; ---- insetX = el[i].insetL + el[i].insetR
        mov     ax, [fitSize__i]
        mov     bx, ax
        mov     al, [el__insetL + bx]
        xor     ah, ah                      ; u8 -> u16
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__i]
        mov     bx, ax
        mov     al, [el__insetR + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [fitSize__insetX], ax
; ---- insetY = el[i].insetT + el[i].insetB
        mov     ax, [fitSize__i]
        mov     bx, ax
        mov     al, [el__insetT + bx]
        xor     ah, ah                      ; u8 -> u16
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__i]
        mov     bx, ax
        mov     al, [el__insetB + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [fitSize__insetY], ax
; ---- gaps = n == 0 ? 0 : el[i].gap * ( n - 1 )
        mov     ax, [fitSize__n]
        test    ax, ax
        je      .L18                        ; unsigned ==
        jmp     .L16
.L18:
        xor     ax, ax                      ; 0
        jmp     .L17
.L16:
        mov     ax, [fitSize__i]
        mov     bx, ax
        mov     al, [el__gap + bx]
        xor     ah, ah                      ; u8 -> u16
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__n]
        dec     ax
        mov     bx, ax
        pop     ax
        mul     bx                          ; low 16 bits are sign-agnostic
.L17:
        mov     [fitSize__gaps], ax
; ---- contentW = 0
        mov     word [fitSize__contentW], 0
; ---- contentH = 0
        mov     word [fitSize__contentH], 0
; ---- minContentW = 0
        mov     word [fitSize__minContentW], 0
; ---- minContentH = 0
        mov     word [fitSize__minContentH], 0
; ---- if ( el[i].isCol ) {
        mov     ax, [fitSize__i]
        mov     bx, ax
        mov     al, [el__isCol + bx]
        test    al, al
        jnz     .L21
        jmp     .L19
.L21:
; ---- for ( k = 0; k < n; k++ ) {
        mov     word [fitSize__k], 0
.L22:
        mov     ax, [fitSize__k]
        mov     bx, [fitSize__n]
        cmp     ax, bx
        jb      .L25                        ; unsigned <
        jmp     .L24
.L25:
; ---- ci = childAt( i, k )
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__childStart + bx]
        mov     bx, [fitSize__k]
        add     ax, bx
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [childList + bx]
        mov     [fitSize__ci], ax
; ---- contentH += el[ci].h
        mov     ax, [fitSize__contentH]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__h + bx]
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [fitSize__contentH], ax
; ---- minContentH += el[ci].minH
        mov     ax, [fitSize__minContentH]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__minH + bx]
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [fitSize__minContentH], ax
; ---- contentW = max( contentW, el[ci].w )
        mov     ax, [fitSize__contentW]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__w + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L28                        ; unsigned >
        jmp     .L26
.L28:
        mov     ax, [fitSize__contentW]
        jmp     .L27
.L26:
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__w + bx]
.L27:
        mov     [fitSize__contentW], ax
; ---- minContentW = max( minContentW, el[ci].minW )
        mov     ax, [fitSize__minContentW]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__minW + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L31                        ; unsigned >
        jmp     .L29
.L31:
        mov     ax, [fitSize__minContentW]
        jmp     .L30
.L29:
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__minW + bx]
.L30:
        mov     [fitSize__minContentW], ax
.L23:
        inc     word [fitSize__k]
        jmp     .L22
.L24:
; ---- contentH += gaps
        mov     ax, [fitSize__contentH]
        mov     bx, [fitSize__gaps]
        add     ax, bx
        mov     [fitSize__contentH], ax
; ---- minContentH += gaps
        mov     ax, [fitSize__minContentH]
        mov     bx, [fitSize__gaps]
        add     ax, bx
        mov     [fitSize__minContentH], ax
        jmp     .L20
.L19:
; ---- for ( k = 0; k < n; k++ ) {
        mov     word [fitSize__k], 0
.L32:
        mov     ax, [fitSize__k]
        mov     bx, [fitSize__n]
        cmp     ax, bx
        jb      .L35                        ; unsigned <
        jmp     .L34
.L35:
; ---- ci = childAt( i, k )
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__childStart + bx]
        mov     bx, [fitSize__k]
        add     ax, bx
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [childList + bx]
        mov     [fitSize__ci], ax
; ---- contentW += el[ci].w
        mov     ax, [fitSize__contentW]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__w + bx]
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [fitSize__contentW], ax
; ---- minContentW += el[ci].minW
        mov     ax, [fitSize__minContentW]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__minW + bx]
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [fitSize__minContentW], ax
; ---- contentH = max( contentH, el[ci].h )
        mov     ax, [fitSize__contentH]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__h + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L38                        ; unsigned >
        jmp     .L36
.L38:
        mov     ax, [fitSize__contentH]
        jmp     .L37
.L36:
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__h + bx]
.L37:
        mov     [fitSize__contentH], ax
; ---- minContentH = max( minContentH, el[ci].minH )
        mov     ax, [fitSize__minContentH]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__minH + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L41                        ; unsigned >
        jmp     .L39
.L41:
        mov     ax, [fitSize__minContentH]
        jmp     .L40
.L39:
        mov     ax, [fitSize__ci]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__minH + bx]
.L40:
        mov     [fitSize__minContentH], ax
.L33:
        inc     word [fitSize__k]
        jmp     .L32
.L34:
; ---- contentW += gaps
        mov     ax, [fitSize__contentW]
        mov     bx, [fitSize__gaps]
        add     ax, bx
        mov     [fitSize__contentW], ax
; ---- minContentW += gaps
        mov     ax, [fitSize__minContentW]
        mov     bx, [fitSize__gaps]
        add     ax, bx
        mov     [fitSize__minContentW], ax
.L20:
; ---- el[i].w = clamp( insetX + contentW, el[i].wMin, el[i].wMax )
        mov     ax, [fitSize__insetX]
        mov     bx, [fitSize__contentW]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMin + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        jb      .L44                        ; unsigned <
        jmp     .L42
.L44:
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMin + bx]
        jmp     .L43
.L42:
        mov     ax, [fitSize__insetX]
        mov     bx, [fitSize__contentW]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMax + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L47                        ; unsigned >
        jmp     .L45
.L47:
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMax + bx]
        jmp     .L46
.L45:
        mov     ax, [fitSize__insetX]
        mov     bx, [fitSize__contentW]
        add     ax, bx
.L46:
.L43:
        push    ax                          ; save value while computing the index
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__w + bx], ax
; ---- el[i].h = clamp( insetY + contentH, el[i].hMin, el[i].hMax )
        mov     ax, [fitSize__insetY]
        mov     bx, [fitSize__contentH]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMin + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        jb      .L50                        ; unsigned <
        jmp     .L48
.L50:
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMin + bx]
        jmp     .L49
.L48:
        mov     ax, [fitSize__insetY]
        mov     bx, [fitSize__contentH]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMax + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L53                        ; unsigned >
        jmp     .L51
.L53:
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMax + bx]
        jmp     .L52
.L51:
        mov     ax, [fitSize__insetY]
        mov     bx, [fitSize__contentH]
        add     ax, bx
.L52:
.L49:
        push    ax                          ; save value while computing the index
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__h + bx], ax
; ---- el[i].minW = clamp( insetX + minContentW, el[i].wMin, el[i].wMax )
        mov     ax, [fitSize__insetX]
        mov     bx, [fitSize__minContentW]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMin + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        jb      .L56                        ; unsigned <
        jmp     .L54
.L56:
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMin + bx]
        jmp     .L55
.L54:
        mov     ax, [fitSize__insetX]
        mov     bx, [fitSize__minContentW]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMax + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L59                        ; unsigned >
        jmp     .L57
.L59:
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMax + bx]
        jmp     .L58
.L57:
        mov     ax, [fitSize__insetX]
        mov     bx, [fitSize__minContentW]
        add     ax, bx
.L58:
.L55:
        push    ax                          ; save value while computing the index
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__minW + bx], ax
; ---- el[i].minH = clamp( insetY + minContentH, el[i].hMin, el[i].hMax )
        mov     ax, [fitSize__insetY]
        mov     bx, [fitSize__minContentH]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMin + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        jb      .L62                        ; unsigned <
        jmp     .L60
.L62:
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMin + bx]
        jmp     .L61
.L60:
        mov     ax, [fitSize__insetY]
        mov     bx, [fitSize__minContentH]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMax + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L65                        ; unsigned >
        jmp     .L63
.L65:
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMax + bx]
        jmp     .L64
.L63:
        mov     ax, [fitSize__insetY]
        mov     bx, [fitSize__minContentH]
        add     ax, bx
.L64:
.L61:
        push    ax                          ; save value while computing the index
        mov     ax, [fitSize__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__minH + bx], ax
        ret

; ============================================== sub cfgReset ====

cfgReset:
; ---- cfg.isCol = false
        mov     byte [cfg__isCol], 0
; ---- cfg.insetL = 0
        mov     byte [cfg__insetL], 0
; ---- cfg.insetR = 0
        mov     byte [cfg__insetR], 0
; ---- cfg.insetT = 0
        mov     byte [cfg__insetT], 0
; ---- cfg.insetB = 0
        mov     byte [cfg__insetB], 0
; ---- cfg.gap = 0
        mov     byte [cfg__gap], 0
; ---- cfg.alignMain = alignStart
        mov     byte [cfg__alignMain], 0
; ---- cfg.alignCross = alignStart
        mov     byte [cfg__alignCross], 0
; ---- cfg.wGrow = false
        mov     byte [cfg__wGrow], 0
; ---- cfg.wMin = 0
        mov     word [cfg__wMin], 0
; ---- cfg.wMax = unbounded
        mov     word [cfg__wMax], 65535
; ---- cfg.hGrow = false
        mov     byte [cfg__hGrow], 0
; ---- cfg.hMin = 0
        mov     word [cfg__hMin], 0
; ---- cfg.hMax = unbounded
        mov     word [cfg__hMax], 65535
        ret

; ============================================== sub cfgCol ====

cfgCol:
; ---- sub cfgCol => cfg.isCol = true
        mov     byte [cfg__isCol], 1
        ret

; ============================================== sub cfgFixedW ====

cfgFixedW:
; ---- cfg.wGrow = false
        mov     byte [cfg__wGrow], 0
; ---- cfg.wMin = n
        mov     ax, [cfgFixedW__n]
        mov     [cfg__wMin], ax
; ---- cfg.wMax = n
        mov     ax, [cfgFixedW__n]
        mov     [cfg__wMax], ax
        ret

; ============================================== sub cfgFixedH ====

cfgFixedH:
; ---- cfg.hGrow = false
        mov     byte [cfg__hGrow], 0
; ---- cfg.hMin = n
        mov     ax, [cfgFixedH__n]
        mov     [cfg__hMin], ax
; ---- cfg.hMax = n
        mov     ax, [cfgFixedH__n]
        mov     [cfg__hMax], ax
        ret

; ============================================== sub cfgGrowW ====

cfgGrowW:
; ---- sub cfgGrowW => cfg.wGrow = true
        mov     byte [cfg__wGrow], 1
        ret

; ============================================== sub cfgGrowH ====

cfgGrowH:
; ---- sub cfgGrowH => cfg.hGrow = true
        mov     byte [cfg__hGrow], 1
        ret

; ============================================== sub cfgInset ====

cfgInset:
; ---- cfg.insetL = n
        mov     al, [cfgInset__n]
        mov     [cfg__insetL], al           ; u8 -> u8, no widening
; ---- cfg.insetR = n
        mov     al, [cfgInset__n]
        mov     [cfg__insetR], al           ; u8 -> u8, no widening
; ---- cfg.insetT = n
        mov     al, [cfgInset__n]
        mov     [cfg__insetT], al           ; u8 -> u8, no widening
; ---- cfg.insetB = n
        mov     al, [cfgInset__n]
        mov     [cfg__insetB], al           ; u8 -> u8, no widening
        ret

; ============================================== sub cfgInsetX ====

cfgInsetX:
; ---- cfg.insetL = n
        mov     al, [cfgInsetX__n]
        mov     [cfg__insetL], al           ; u8 -> u8, no widening
; ---- cfg.insetR = n
        mov     al, [cfgInsetX__n]
        mov     [cfg__insetR], al           ; u8 -> u8, no widening
        ret

; ============================================== u16 pushElement ====

m_bld__pushElement:
; ---- i = elCount
        mov     ax, [elCount]
        mov     [m_bld__pushElement__i], ax
; ---- el[i].isCol = cfg.isCol
        mov     al, [cfg__isCol]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        pop     ax
        mov     [el__isCol + bx], al
; ---- el[i].insetL = cfg.insetL
        mov     al, [cfg__insetL]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        pop     ax
        mov     [el__insetL + bx], al
; ---- el[i].insetR = cfg.insetR
        mov     al, [cfg__insetR]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        pop     ax
        mov     [el__insetR + bx], al
; ---- el[i].insetT = cfg.insetT
        mov     al, [cfg__insetT]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        pop     ax
        mov     [el__insetT + bx], al
; ---- el[i].insetB = cfg.insetB
        mov     al, [cfg__insetB]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        pop     ax
        mov     [el__insetB + bx], al
; ---- el[i].gap = cfg.gap
        mov     al, [cfg__gap]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        pop     ax
        mov     [el__gap + bx], al
; ---- el[i].alignMain = cfg.alignMain
        mov     al, [cfg__alignMain]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        pop     ax
        mov     [el__alignMain + bx], al
; ---- el[i].alignCross = cfg.alignCross
        mov     al, [cfg__alignCross]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        pop     ax
        mov     [el__alignCross + bx], al
; ---- el[i].wGrow = cfg.wGrow
        mov     al, [cfg__wGrow]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        pop     ax
        mov     [el__wGrow + bx], al
; ---- el[i].wMin = cfg.wMin
        mov     ax, [cfg__wMin]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__wMin + bx], ax
; ---- el[i].wMax = cfg.wMax
        mov     ax, [cfg__wMax]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__wMax + bx], ax
; ---- el[i].hGrow = cfg.hGrow
        mov     al, [cfg__hGrow]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        pop     ax
        mov     [el__hGrow + bx], al
; ---- el[i].hMin = cfg.hMin
        mov     ax, [cfg__hMin]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__hMin + bx], ax
; ---- el[i].hMax = cfg.hMax
        mov     ax, [cfg__hMax]
        push    ax                          ; save value while computing the index
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__hMax + bx], ax
; ---- el[i].childStart = 0
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [el__childStart + bx], 0
; ---- el[i].childCount = 0
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [el__childCount + bx], 0
; ---- el[i].w = 0
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [el__w + bx], 0
; ---- el[i].h = 0
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [el__h + bx], 0
; ---- el[i].minW = 0
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [el__minW + bx], 0
; ---- el[i].minH = 0
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [el__minH + bx], 0
; ---- el[i].x = 0
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [el__x + bx], 0
; ---- el[i].y = 0
        mov     ax, [m_bld__pushElement__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     word [el__y + bx], 0
; ---- el[i].overflowX = false
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        mov     byte [el__overflowX + bx], 0
; ---- el[i].overflowY = false
        mov     ax, [m_bld__pushElement__i]
        mov     bx, ax
        mov     byte [el__overflowY + bx], 0
; ---- elCount++
        inc     word [elCount]
; ---- cfgReset()
        call    cfgReset
; ---- return i
        mov     ax, [m_bld__pushElement__i]
        mov     [m_bld__pushElement__ret], ax
        ret

; ============================================== sub attachToParent ====

m_bld__attachToParent:
; ---- if ( openDepth == 0 ) return          // the root has no parent
        mov     ax, [openDepth]
        test    ax, ax
        je      .L68                        ; unsigned ==
        jmp     .L66
.L68:
        ret
.L66:
; ---- p = openStack[ openDepth - 1 ]
        mov     ax, [openDepth]
        dec     ax
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [openStack + bx]
        mov     [m_bld__attachToParent__p], ax
; ---- el[p].childCount++
        mov     ax, [m_bld__attachToParent__p]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        inc     word [el__childCount + bx]
; ---- childBuf[ childBufLen ] = i
        mov     ax, [m_bld__attachToParent__i]
        push    ax                          ; save value while computing the index
        mov     ax, [childBufLen]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [childBuf + bx], ax
; ---- childBufLen++
        inc     word [childBufLen]
        ret

; ============================================== u16 openBox ====

openBox:
; ---- i = pushElement()
        call    m_bld__pushElement
        mov     ax, [m_bld__pushElement__ret]
        mov     [openBox__i], ax
; ---- openStack[ openDepth ] = i
        mov     ax, [openBox__i]
        push    ax                          ; save value while computing the index
        mov     ax, [openDepth]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [openStack + bx], ax
; ---- openDepth++
        inc     word [openDepth]
; ---- return i
        mov     ax, [openBox__i]
        mov     [openBox__ret], ax
        ret

; ============================================== sub closeBox ====

closeBox:
; ---- if ( openDepth == 0 ) return
        mov     ax, [openDepth]
        test    ax, ax
        je      .L71                        ; unsigned ==
        jmp     .L69
.L71:
        ret
.L69:
; ---- openDepth--
        dec     word [openDepth]
; ---- i = openStack[ openDepth ]
        mov     ax, [openDepth]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [openStack + bx]
        mov     [closeBox__i], ax
; ---- n = el[i].childCount
        mov     ax, [closeBox__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__childCount + bx]
        mov     [closeBox__n], ax
; ---- el[i].childStart = childListLen
        mov     ax, [childListLen]
        push    ax                          ; save value while computing the index
        mov     ax, [closeBox__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__childStart + bx], ax
; ---- base = childBufLen - n
        mov     ax, [childBufLen]
        mov     bx, [closeBox__n]
        sub     ax, bx
        mov     [closeBox__base], ax
; ---- for ( k = 0; k < n; k++ ) {
        mov     word [closeBox__k], 0
.L72:
        mov     ax, [closeBox__k]
        mov     bx, [closeBox__n]
        cmp     ax, bx
        jb      .L75                        ; unsigned <
        jmp     .L74
.L75:
; ---- childList[ childListLen ] = childBuf[ base + k ]
        mov     ax, [closeBox__base]
        mov     bx, [closeBox__k]
        add     ax, bx
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [childBuf + bx]
        push    ax                          ; save value while computing the index
        mov     ax, [childListLen]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [childList + bx], ax
; ---- childListLen++
        inc     word [childListLen]
.L73:
        inc     word [closeBox__k]
        jmp     .L72
.L74:
; ---- childBufLen = base
        mov     ax, [closeBox__base]
        mov     [childBufLen], ax
; ---- fitSize( i )
        mov     ax, [closeBox__i]
        mov     [fitSize__i], ax
        call    fitSize
; ---- attachToParent( i )
        mov     ax, [closeBox__i]
        mov     [m_bld__attachToParent__i], ax
        call    m_bld__attachToParent
        ret

; ============================================== u16 leaf ====

leaf:
; ---- i = pushElement()
        call    m_bld__pushElement
        mov     ax, [m_bld__pushElement__ret]
        mov     [leaf__i], ax
; ---- insetX = el[i].insetL + el[i].insetR
        mov     ax, [leaf__i]
        mov     bx, ax
        mov     al, [el__insetL + bx]
        xor     ah, ah                      ; u8 -> u16
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [leaf__i]
        mov     bx, ax
        mov     al, [el__insetR + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [leaf__insetX], ax
; ---- insetY = el[i].insetT + el[i].insetB
        mov     ax, [leaf__i]
        mov     bx, ax
        mov     al, [el__insetT + bx]
        xor     ah, ah                      ; u8 -> u16
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [leaf__i]
        mov     bx, ax
        mov     al, [el__insetB + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [leaf__insetY], ax
; ---- mw = min( minW, w )
        mov     ax, [leaf__minW]
        mov     bx, [leaf__w]
        cmp     ax, bx
        jb      .L78                        ; unsigned <
        jmp     .L76
.L78:
        mov     ax, [leaf__minW]
        jmp     .L77
.L76:
        mov     ax, [leaf__w]
.L77:
        mov     [leaf__mw], ax
; ---- mh = min( minH, h )
        mov     ax, [leaf__minH]
        mov     bx, [leaf__h]
        cmp     ax, bx
        jb      .L81                        ; unsigned <
        jmp     .L79
.L81:
        mov     ax, [leaf__minH]
        jmp     .L80
.L79:
        mov     ax, [leaf__h]
.L80:
        mov     [leaf__mh], ax
; ---- el[i].w = clamp( insetX + w, el[i].wMin, el[i].wMax )
        mov     ax, [leaf__insetX]
        mov     bx, [leaf__w]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMin + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        jb      .L84                        ; unsigned <
        jmp     .L82
.L84:
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMin + bx]
        jmp     .L83
.L82:
        mov     ax, [leaf__insetX]
        mov     bx, [leaf__w]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMax + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L87                        ; unsigned >
        jmp     .L85
.L87:
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMax + bx]
        jmp     .L86
.L85:
        mov     ax, [leaf__insetX]
        mov     bx, [leaf__w]
        add     ax, bx
.L86:
.L83:
        push    ax                          ; save value while computing the index
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__w + bx], ax
; ---- el[i].h = clamp( insetY + h, el[i].hMin, el[i].hMax )
        mov     ax, [leaf__insetY]
        mov     bx, [leaf__h]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMin + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        jb      .L90                        ; unsigned <
        jmp     .L88
.L90:
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMin + bx]
        jmp     .L89
.L88:
        mov     ax, [leaf__insetY]
        mov     bx, [leaf__h]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMax + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L93                        ; unsigned >
        jmp     .L91
.L93:
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMax + bx]
        jmp     .L92
.L91:
        mov     ax, [leaf__insetY]
        mov     bx, [leaf__h]
        add     ax, bx
.L92:
.L89:
        push    ax                          ; save value while computing the index
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__h + bx], ax
; ---- el[i].minW = clamp( insetX + mw, el[i].wMin, el[i].wMax )
        mov     ax, [leaf__insetX]
        mov     bx, [leaf__mw]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMin + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        jb      .L96                        ; unsigned <
        jmp     .L94
.L96:
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMin + bx]
        jmp     .L95
.L94:
        mov     ax, [leaf__insetX]
        mov     bx, [leaf__mw]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMax + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L99                        ; unsigned >
        jmp     .L97
.L99:
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__wMax + bx]
        jmp     .L98
.L97:
        mov     ax, [leaf__insetX]
        mov     bx, [leaf__mw]
        add     ax, bx
.L98:
.L95:
        push    ax                          ; save value while computing the index
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__minW + bx], ax
; ---- el[i].minH = clamp( insetY + mh, el[i].hMin, el[i].hMax )
        mov     ax, [leaf__insetY]
        mov     bx, [leaf__mh]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMin + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        jb      .L102                       ; unsigned <
        jmp     .L100
.L102:
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMin + bx]
        jmp     .L101
.L100:
        mov     ax, [leaf__insetY]
        mov     bx, [leaf__mh]
        add     ax, bx
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMax + bx]
        mov     bx, ax
        pop     ax
        cmp     ax, bx
        ja      .L105                       ; unsigned >
        jmp     .L103
.L105:
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__hMax + bx]
        jmp     .L104
.L103:
        mov     ax, [leaf__insetY]
        mov     bx, [leaf__mh]
        add     ax, bx
.L104:
.L101:
        push    ax                          ; save value while computing the index
        mov     ax, [leaf__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        pop     ax
        mov     [el__minH + bx], ax
; ---- attachToParent( i )
        mov     ax, [leaf__i]
        mov     [m_bld__attachToParent__i], ax
        call    m_bld__attachToParent
; ---- return i
        mov     ax, [leaf__i]
        mov     [leaf__ret], ax
        ret

; ============================================== sub begin ====

begin:
; ---- elCount = 0
        mov     word [elCount], 0
; ---- openDepth = 0
        mov     word [openDepth], 0
; ---- childBufLen = 0
        mov     word [childBufLen], 0
; ---- childListLen = 0
        mov     word [childListLen], 0
; ---- cfgReset()
        call    cfgReset
; ---- cfgCol()
        call    cfgCol
; ---- cfgFixedW( w )
        mov     ax, [begin__w]
        mov     [cfgFixedW__n], ax
        call    cfgFixedW
; ---- cfgFixedH( h )
        mov     ax, [begin__h]
        mov     [cfgFixedH__n], ax
        call    cfgFixedH
; ---- openBox()
        call    openBox
        ret

; ============================================== u16 labelAt ====

labelAt:
; ---- n = strLen( at )
        mov     ax, [labelAt__at]
        mov     [strLen__at], ax
        call    strLen
        mov     ax, [strLen__ret]
        mov     [labelAt__n], ax
; ---- return leaf( n, lineHeight, n, lineHeight )
        mov     ax, [labelAt__n]
        mov     [leaf__w], ax
        mov     word [leaf__h], 1
        mov     ax, [labelAt__n]
        mov     [leaf__minW], ax
        mov     word [leaf__minH], 1
        call    leaf
        mov     ax, [leaf__ret]
        mov     [labelAt__ret], ax
        ret

; ============================================== u16 paraAt ====

paraAt:
; ---- n = strLen( at )
        mov     ax, [paraAt__at]
        mov     [strLen__at], ax
        call    strLen
        mov     ax, [strLen__ret]
        mov     [paraAt__n], ax
; ---- return leaf( n, lineHeight, minW, lineHeight )
        mov     ax, [paraAt__n]
        mov     [leaf__w], ax
        mov     word [leaf__h], 1
        mov     ax, [paraAt__minW]
        mov     [leaf__minW], ax
        mov     word [leaf__minH], 1
        call    leaf
        mov     ax, [leaf__ret]
        mov     [paraAt__ret], ax
        ret

; ============================================== sub putField ====

putField:
; ---- putNumber( n )
        mov     ax, [putField__n]
        mov     [putNumber__n], ax
        call    putNumber
; ---- space()
        call    space
        ret

; ============================================== sub dumpBoxes ====

dumpBoxes:
; ---- for ( i = 0; i < elCount; i++ ) {
        mov     word [dumpBoxes__i], 0
.L106:
        mov     ax, [dumpBoxes__i]
        mov     bx, [elCount]
        cmp     ax, bx
        jb      .L109                       ; unsigned <
        jmp     .L108
.L109:
; ---- putField( i )
        mov     ax, [dumpBoxes__i]
        mov     [putField__n], ax
        call    putField
; ---- putField( el[i].x )
        mov     ax, [dumpBoxes__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__x + bx]
        mov     [putField__n], ax
        call    putField
; ---- putField( el[i].y )
        mov     ax, [dumpBoxes__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__y + bx]
        mov     [putField__n], ax
        call    putField
; ---- putField( el[i].w )
        mov     ax, [dumpBoxes__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__w + bx]
        mov     [putField__n], ax
        call    putField
; ---- putField( el[i].h )
        mov     ax, [dumpBoxes__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__h + bx]
        mov     [putField__n], ax
        call    putField
; ---- putField( el[i].minW )
        mov     ax, [dumpBoxes__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__minW + bx]
        mov     [putField__n], ax
        call    putField
; ---- putNumber( el[i].minH )
        mov     ax, [dumpBoxes__i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     ax, [el__minH + bx]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
.L107:
        inc     word [dumpBoxes__i]
        jmp     .L106
.L108:
        ret

; ============================================== sub swatch ====

swatch:
; ---- cfgGrowW()
        call    cfgGrowW
; ---- cfgInsetX( u )
        mov     byte [cfgInsetX__n], 1
        call    cfgInsetX
; ---- cfg.alignMain = alignCenter
        mov     byte [cfg__alignMain], 1
; ---- openBox()
        call    openBox
; ---- labelAt( at )
        mov     ax, [swatch__at]
        mov     [labelAt__at], ax
        call    labelAt
; ---- closeBox()
        call    closeBox
        ret

; ============================================== sub buildShell ====

buildShell:
; ---- cfgCol()
        call    cfgCol
; ---- cfgGrowW()
        call    cfgGrowW
; ---- cfgGrowH()
        call    cfgGrowH
; ---- openBox()
        call    openBox
; ---- cfgGrowW()
        call    cfgGrowW
; ---- cfgFixedH( lineHeight )
        mov     word [cfgFixedH__n], 1
        call    cfgFixedH
; ---- cfgInsetX( u )
        mov     byte [cfgInsetX__n], 1
        call    cfgInsetX
; ---- openBox()
        call    openBox
; ---- labelAt( addr( sMomolo ) )
        mov     ax, sMomolo                 ; link-time constant
        mov     [labelAt__at], ax
        call    labelAt
; ---- cfgGrowW()
        call    cfgGrowW
; ---- openBox()
        call    openBox
; ---- closeBox()
        call    closeBox
; ---- labelAt( addr( sGeometry ) )
        mov     ax, sGeometry               ; link-time constant
        mov     [labelAt__at], ax
        call    labelAt
; ---- closeBox()
        call    closeBox
; ---- cfgGrowW()
        call    cfgGrowW
; ---- cfgGrowH()
        call    cfgGrowH
; ---- cfgInset( u )
        mov     byte [cfgInset__n], 1
        call    cfgInset
; ---- cfg.gap = u
        mov     byte [cfg__gap], 1
; ---- openBox()
        call    openBox
; ---- cfgCol()
        call    cfgCol
; ---- cfgFixedW( 16 * u )
        mov     word [cfgFixedW__n], 16
        call    cfgFixedW
; ---- cfgGrowH()
        call    cfgGrowH
; ---- cfgInset( u + border )
        mov     byte [cfgInset__n], 2
        call    cfgInset
; ---- openBox()
        call    openBox
; ---- labelAt( addr( sNew ) )
        mov     ax, sNew                    ; link-time constant
        mov     [labelAt__at], ax
        call    labelAt
; ---- labelAt( addr( sOpen ) )
        mov     ax, sOpen                   ; link-time constant
        mov     [labelAt__at], ax
        call    labelAt
; ---- labelAt( addr( sSave ) )
        mov     ax, sSave                   ; link-time constant
        mov     [labelAt__at], ax
        call    labelAt
; ---- labelAt( addr( sQuit ) )
        mov     ax, sQuit                   ; link-time constant
        mov     [labelAt__at], ax
        call    labelAt
; ---- cfgFixedH( lineHeight )
        mov     word [cfgFixedH__n], 1
        call    cfgFixedH
; ---- openBox()
        call    openBox
; ---- closeBox()
        call    closeBox
; ---- paraAt( addr( sBody ), bodyMinW )
        mov     ax, sBody                   ; link-time constant
        mov     [paraAt__at], ax
        mov     word [paraAt__minW], 7
        call    paraAt
; ---- closeBox()
        call    closeBox
; ---- cfgCol()
        call    cfgCol
; ---- cfgGrowW()
        call    cfgGrowW
; ---- cfgGrowH()
        call    cfgGrowH
; ---- cfgInset( u + border )
        mov     byte [cfgInset__n], 2
        call    cfgInset
; ---- cfg.gap = u
        mov     byte [cfg__gap], 1
; ---- cfg.alignMain = alignCenter
        mov     byte [cfg__alignMain], 1
; ---- cfg.alignCross = alignCenter
        mov     byte [cfg__alignCross], 1
; ---- openBox()
        call    openBox
; ---- labelAt( addr( sCentred ) )
        mov     ax, sCentred                ; link-time constant
        mov     [labelAt__at], ax
        call    labelAt
; ---- cfgGrowW()
        call    cfgGrowW
; ---- cfg.gap = u
        mov     byte [cfg__gap], 1
; ---- openBox()
        call    openBox
; ---- swatch( addr( sA ) )
        mov     ax, sA                      ; link-time constant
        mov     [swatch__at], ax
        call    swatch
; ---- swatch( addr( sB ) )
        mov     ax, sB                      ; link-time constant
        mov     [swatch__at], ax
        call    swatch
; ---- swatch( addr( sC ) )
        mov     ax, sC                      ; link-time constant
        mov     [swatch__at], ax
        call    swatch
; ---- closeBox()
        call    closeBox
; ---- cfgFixedW( 24 * u )
        mov     word [cfgFixedW__n], 24
        call    cfgFixedW
; ---- cfg.gap = u
        mov     byte [cfg__gap], 1
; ---- openBox()
        call    openBox
; ---- paraAt( addr( sLeft ), squeezedMinW )
        mov     ax, sLeft                   ; link-time constant
        mov     [paraAt__at], ax
        mov     word [paraAt__minW], 8
        call    paraAt
; ---- paraAt( addr( sRight ), squeezedMinW )
        mov     ax, sRight                  ; link-time constant
        mov     [paraAt__at], ax
        mov     word [paraAt__minW], 8
        call    paraAt
; ---- closeBox()
        call    closeBox
; ---- closeBox()
        call    closeBox
; ---- closeBox()
        call    closeBox
; ---- cfgGrowW()
        call    cfgGrowW
; ---- cfgFixedH( lineHeight )
        mov     word [cfgFixedH__n], 1
        call    cfgFixedH
; ---- cfgInsetX( u )
        mov     byte [cfgInsetX__n], 1
        call    cfgInsetX
; ---- openBox()
        call    openBox
; ---- labelAt( addr( sReady ) )
        mov     ax, sReady                  ; link-time constant
        mov     [labelAt__at], ax
        call    labelAt
; ---- closeBox()
        call    closeBox
; ---- closeBox()
        call    closeBox
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax             dw      0
_al             equ     _ax
_ah             equ     _ax + 1
_bx             dw      0
_bl             equ     _bx
_bh             equ     _bx + 1
_cx             dw      0
_cl             equ     _cx
_ch             equ     _cx + 1
_dx             dw      0
_dl             equ     _dx
_dh             equ     _dx + 1
_si             dw      0
_di             dw      0

; ---- variables ----
putChar__c      db      0        ; u8
putNumber__n    dw      0        ; u16
strLen__at      dw      0        ; u16
strLen__ret     dw      0        ; u16
elCount         dw      0        ; u16
openDepth       dw      0        ; u16
childBufLen     dw      0        ; u16
childListLen    dw      0        ; u16
fitSize__i      dw      0        ; u16
cfg__isCol      db      0        ; bool
cfg__insetL     db      0        ; u8
cfg__insetR     db      0        ; u8
cfg__insetT     db      0        ; u8
cfg__insetB     db      0        ; u8
cfg__gap        db      0        ; u8
cfg__alignMain  db      0        ; u8
cfg__alignCross db      0        ; u8
cfg__wGrow      db      0        ; bool
cfg__wMin       dw      0        ; u16
cfg__wMax       dw      0        ; u16
cfg__hGrow      db      0        ; bool
cfg__hMin       dw      0        ; u16
cfg__hMax       dw      0        ; u16
cfgFixedW__n    dw      0        ; u16
cfgFixedH__n    dw      0        ; u16
cfgInset__n     db      0        ; u8
cfgInsetX__n    db      0        ; u8
m_bld__pushElement__ret dw      0        ; u16
m_bld__attachToParent__i dw      0        ; u16
openBox__ret    dw      0        ; u16
leaf__w         dw      0        ; u16
leaf__h         dw      0        ; u16
leaf__minW      dw      0        ; u16
leaf__minH      dw      0        ; u16
leaf__ret       dw      0        ; u16
begin__w        dw      0        ; u16
begin__h        dw      0        ; u16
labelAt__at     dw      0        ; u16
labelAt__ret    dw      0        ; u16
paraAt__at      dw      0        ; u16
paraAt__minW    dw      0        ; u16
paraAt__ret     dw      0        ; u16
putField__n     dw      0        ; u16
swatch__at      dw      0        ; u16
putNumber__i    db      0        ; u8
strLen__n       dw      0        ; u16
fitSize__n      dw      0        ; u16
fitSize__insetX dw      0        ; u16
fitSize__insetY dw      0        ; u16
fitSize__gaps   dw      0        ; u16
fitSize__contentW dw      0        ; u16
fitSize__contentH dw      0        ; u16
fitSize__minContentW dw      0        ; u16
fitSize__minContentH dw      0        ; u16
fitSize__k      dw      0        ; u16
fitSize__ci     dw      0        ; u16
m_bld__pushElement__i dw      0        ; u16
m_bld__attachToParent__p dw      0        ; u16
openBox__i      dw      0        ; u16
closeBox__i     dw      0        ; u16
closeBox__n     dw      0        ; u16
closeBox__base  dw      0        ; u16
closeBox__k     dw      0        ; u16
leaf__i         dw      0        ; u16
leaf__insetX    dw      0        ; u16
leaf__insetY    dw      0        ; u16
leaf__mw        dw      0        ; u16
leaf__mh        dw      0        ; u16
labelAt__n      dw      0        ; u16
paraAt__n       dw      0        ; u16
dumpBoxes__i    dw      0        ; u16

; ---- arrays ----
el__isCol       times 64 db 0        ; bool[64]
el__insetL      times 64 db 0        ; u8[64]
el__insetR      times 64 db 0        ; u8[64]
el__insetT      times 64 db 0        ; u8[64]
el__insetB      times 64 db 0        ; u8[64]
el__gap         times 64 db 0        ; u8[64]
el__alignMain   times 64 db 0        ; u8[64]
el__alignCross  times 64 db 0        ; u8[64]
el__wGrow       times 64 db 0        ; bool[64]
el__wMin        times 64 dw 0        ; u16[64]
el__wMax        times 64 dw 0        ; u16[64]
el__hGrow       times 64 db 0        ; bool[64]
el__hMin        times 64 dw 0        ; u16[64]
el__hMax        times 64 dw 0        ; u16[64]
el__childStart  times 64 dw 0        ; u16[64]
el__childCount  times 64 dw 0        ; u16[64]
el__w           times 64 dw 0        ; u16[64]
el__h           times 64 dw 0        ; u16[64]
el__minW        times 64 dw 0        ; u16[64]
el__minH        times 64 dw 0        ; u16[64]
el__x           times 64 dw 0        ; u16[64]
el__y           times 64 dw 0        ; u16[64]
el__overflowX   times 64 db 0        ; bool[64]
el__overflowY   times 64 db 0        ; bool[64]
openStack       times 16 dw 0        ; u16[16]
childBuf        times 64 dw 0        ; u16[64]
childList       times 64 dw 0        ; u16[64]
sMomolo         db      'momolo$'        ; u8[7] const
sGeometry       db      'geometry$'        ; u8[9] const
sNew            db      'New$'        ; u8[4] const
sOpen           db      'Open$'        ; u8[5] const
sSave           db      'Save$'        ; u8[5] const
sQuit           db      'Quit$'        ; u8[5] const
sBody           db      'wrapped text in a narrow column$'        ; u8[32] const
sCentred        db      'centred on both axes$'        ; u8[21] const
sA              db      'a$'        ; u8[2] const
sB              db      'bbbb$'        ; u8[5] const
sC              db      'cc$'        ; u8[3] const
sLeft           db      'squeezed left column$'        ; u8[21] const
sRight          db      'squeezed right column$'        ; u8[22] const
sReady          db      'ready$'        ; u8[6] const
putNumber__digits times 5 db 0        ; u8[5]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack         equ     270        ; 14 worst-case + 256 interrupt reserve
_htop           equ     0FFFEh - _hstack

_hsize          dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw          equ     _heap        ; same bytes, u16 view
