; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
ioBase          equ     10
ioZeroChar      equ     48

; =========================================================== entry ====

__entry:
; ---- setTextMode()
        call    setTextMode
; ---- cells[0] = 0x0741                 // 'A', attribute 7
        mov     dx, 0xB800                  ; segment of cells
        mov     es, dx
        mov     word [es:0], 1857
; ---- cells[1] = 0x0742                 // 'B'
        mov     dx, 0xB800                  ; segment of cells
        mov     es, dx
        mov     word [es:2], 1858
; ---- cells[5] = 0x0745                 // 'E'
        mov     dx, 0xB800                  ; segment of cells
        mov     es, dx
        mov     word [es:10], 1861
; ---- i = 3
        mov     word [i], 3
; ---- cells[i] = 0x0744                 // 'D'
        mov     ax, [i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     dx, 0xB800                  ; segment of cells
        mov     es, dx
        mov     word [es:bx], 1860
; ---- word1 = cells[1]
        mov     dx, 0xB800                  ; segment of cells
        mov     es, dx
        mov     ax, [es:2]
        mov     [word1], ax
; ---- char1 = cellBytes[2]
        mov     dx, 0xB800                  ; segment of cellBytes
        mov     es, dx
        mov     al, [es:2]
        mov     [char1], al                 ; u8 -> u8, no widening
; ---- attr1 = cellBytes[3]
        mov     dx, 0xB800                  ; segment of cellBytes
        mov     es, dx
        mov     al, [es:3]
        mov     [attr1], al                 ; u8 -> u8, no widening
; ---- viaOffset = cellFive[0]
        mov     dx, 0xB800                  ; segment of cellFive
        mov     es, dx
        mov     ax, [es:10]
        mov     [viaOffset], ax
; ---- moveTo( 0, 2 )
        xor     ax, ax                      ; 0
        mov     [moveTo__col], al           ; narrowed to u8
        mov     ax, 2
        mov     [moveTo__row], al           ; narrowed to u8
        call    moveTo
; ---- putNumber( word1 )                // 0x0742 = 1858
        mov     ax, [word1]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- putNumber( char1 )                // 0x42 = 66, 'B'
        mov     al, [char1]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- putNumber( attr1 )                // 7
        mov     al, [attr1]
        xor     ah, ah                      ; u8 -> u16
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- putNumber( viaOffset )            // 0x0745 = 1861
        mov     ax, [viaOffset]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
; ---- putNumber( cells[i] )             // 0x0744 = 1860, read with a runtime index
        mov     ax, [i]
        shl     ax, 1                       ; word elements
        mov     bx, ax
        mov     dx, 0xB800                  ; segment of cells
        mov     es, dx
        mov     ax, [es:bx]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub putChar ====

putChar:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _dl = c
        mov     al, [putChar__c]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x21
        call    int21
        ret

; ============================================== sub newline ====

newline:
; ---- putChar(13)
        mov     ax, 13
        mov     [putChar__c], al            ; narrowed to u8
        call    putChar
; ---- putChar(10)
        mov     ax, 10
        mov     [putChar__c], al            ; narrowed to u8
        call    putChar
        ret

; ============================================== sub putNumber ====

putNumber:
; ---- if (n == 0) {
        mov     ax, [putNumber__n]
        test    ax, ax
        je      .L3                         ; unsigned ==
        jmp     .L1
.L3:
; ---- putChar(ioZeroChar)
        mov     ax, 48
        mov     [putChar__c], al            ; narrowed to u8
        call    putChar
; ---- return
        ret
.L1:
; ---- for (i = 0; n > 0; i++) {
        mov     byte [putNumber__i], 0
.L4:
        mov     ax, [putNumber__n]
        test    ax, ax
        ja      .L7                         ; unsigned >
        jmp     .L6
.L7:
; ---- digits[i] = u8(n % ioBase) + ioZeroChar
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        add     ax, 48
        push    ax                          ; save value while computing the index
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        mov     [putNumber__digits + bx], al
; ---- n /= ioBase
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     [putNumber__n], ax
.L5:
        inc     byte [putNumber__i]
        jmp     .L4
.L6:
; ---- for (; i > 0; i--) {
.L8:
        mov     al, [putNumber__i]
        test    al, al
        ja      .L11                        ; unsigned >
        jmp     .L10
.L11:
; ---- putChar(digits[i - 1])
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        dec     ax
        mov     bx, ax
        mov     al, [putNumber__digits + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [putChar__c], al            ; narrowed to u8
        call    putChar
.L9:
        dec     byte [putNumber__i]
        jmp     .L8
.L10:
        ret

; ============================================== sub setTextMode ====

setTextMode:
; ---- _ax = 0x0003
        mov     word [_ax], 3
; ---- int 0x10
        call    int10
        ret

; ============================================== sub moveTo ====

moveTo:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _bh = 0                       // page 0
        mov     byte [_bh], 0
; ---- _dh = row
        mov     al, [moveTo__row]
        mov     [_dh], al                   ; u8 -> u8, no widening
; ---- _dl = col
        mov     al, [moveTo__col]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x10
        call    int10
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int10:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x10
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

int21:
        push    es
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pop     es
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax             dw      0
_al             equ     _ax
_ah             equ     _ax + 1
_bx             dw      0
_bl             equ     _bx
_bh             equ     _bx + 1
_cx             dw      0
_cl             equ     _cx
_ch             equ     _cx + 1
_dx             dw      0
_dl             equ     _dx
_dh             equ     _dx + 1
_si             dw      0
_di             dw      0

; ---- variables ----
putChar__c      db      0        ; u8
putNumber__n    dw      0        ; u16
moveTo__col     db      0        ; u8
moveTo__row     db      0        ; u8
word1           dw      0        ; u16
char1           db      0        ; u8
attr1           db      0        ; u8
viaOffset       dw      0        ; u16
i               dw      0        ; u16
putNumber__i    db      0        ; u8

; ---- arrays ----
putNumber__digits times 5 db 0        ; u8[5]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack         equ     262        ; 6 worst-case + 256 interrupt reserve
_htop           equ     0FFFEh - _hstack

_hsize          dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw          equ     _heap        ; same bytes, u16 view
