; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
ioBase          equ     10
ioZeroChar      equ     48
limit           equ     100

; =========================================================== entry ====

__entry:
; ---- runSieve()
        call    runSieve
; ---- count = 0
        mov     word [count], 0
; ---- for (i = 2; i < limit; i++) {
        mov     word [i], 2
.L1:
        mov     ax, [i]
        cmp     ax, 100
        jb      .L4                         ; unsigned <
        jmp     .L3
.L4:
; ---- if (composite[i]) continue
        mov     ax, [i]
        mov     bx, ax
        mov     al, [composite + bx]
        test    al, al
        jnz     .L7
        jmp     .L5
.L7:
        jmp     .L2
.L5:
; ---- putNumber(i)
        mov     ax, [i]
        mov     [putNumber__n], ax
        call    putNumber
; ---- putChar(' ')
        mov     ax, 32
        mov     [putChar__c], al            ; narrowed to u8
        call    putChar
; ---- count++
        inc     word [count]
.L2:
        inc     word [i]
        jmp     .L1
.L3:
; ---- newline()
        call    newline
; ---- putNumber(count)
        mov     ax, [count]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub putChar ====

putChar:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _dl = c
        mov     al, [putChar__c]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x21
        call    int21
        ret

; ============================================== sub newline ====

newline:
; ---- putChar(13)
        mov     ax, 13
        mov     [putChar__c], al            ; narrowed to u8
        call    putChar
; ---- putChar(10)
        mov     ax, 10
        mov     [putChar__c], al            ; narrowed to u8
        call    putChar
        ret

; ============================================== sub putNumber ====

putNumber:
; ---- if (n == 0) {
        mov     ax, [putNumber__n]
        test    ax, ax
        je      .L10                        ; unsigned ==
        jmp     .L8
.L10:
; ---- putChar(ioZeroChar)
        mov     ax, 48
        mov     [putChar__c], al            ; narrowed to u8
        call    putChar
; ---- return
        ret
.L8:
; ---- for (i = 0; n > 0; i++) {
        mov     byte [putNumber__i], 0
.L11:
        mov     ax, [putNumber__n]
        test    ax, ax
        ja      .L14                        ; unsigned >
        jmp     .L13
.L14:
; ---- digits[i] = u8(n % ioBase) + ioZeroChar
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        add     ax, 48
        push    ax                          ; save value while computing the index
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        mov     [putNumber__digits + bx], al
; ---- n /= ioBase
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     [putNumber__n], ax
.L12:
        inc     byte [putNumber__i]
        jmp     .L11
.L13:
; ---- for (; i > 0; i--) {
.L15:
        mov     al, [putNumber__i]
        test    al, al
        ja      .L18                        ; unsigned >
        jmp     .L17
.L18:
; ---- putChar(digits[i - 1])
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        dec     ax
        mov     bx, ax
        mov     al, [putNumber__digits + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [putChar__c], al            ; narrowed to u8
        call    putChar
.L16:
        dec     byte [putNumber__i]
        jmp     .L15
.L17:
        ret

; ============================================== sub runSieve ====

runSieve:
; ---- for (i = 2; i * i < limit; i++) {
        mov     word [i], 2
.L19:
        mov     ax, [i]
        mov     bx, [i]
        mul     bx                          ; low 16 bits are sign-agnostic
        cmp     ax, 100
        jb      .L22                        ; unsigned <
        jmp     .L21
.L22:
; ---- if (composite[i]) continue
        mov     ax, [i]
        mov     bx, ax
        mov     al, [composite + bx]
        test    al, al
        jnz     .L25
        jmp     .L23
.L25:
        jmp     .L20
.L23:
; ---- for (j = i * i; j < limit; j += i) {
        mov     ax, [i]
        mov     bx, [i]
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     [j], ax
.L26:
        mov     ax, [j]
        cmp     ax, 100
        jb      .L29                        ; unsigned <
        jmp     .L28
.L29:
; ---- composite[j] = 1
        mov     ax, [j]
        mov     bx, ax
        mov     byte [composite + bx], 1
.L27:
        mov     ax, [j]
        mov     bx, [i]
        add     ax, bx
        mov     [j], ax
        jmp     .L26
.L28:
.L20:
        inc     word [i]
        jmp     .L19
.L21:
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax             dw      0
_al             equ     _ax
_ah             equ     _ax + 1
_bx             dw      0
_bl             equ     _bx
_bh             equ     _bx + 1
_cx             dw      0
_cl             equ     _cx
_ch             equ     _cx + 1
_dx             dw      0
_dl             equ     _dx
_dh             equ     _dx + 1
_si             dw      0
_di             dw      0

; ---- variables ----
putChar__c      db      0        ; u8
putNumber__n    dw      0        ; u16
i               dw      0        ; u16
j               dw      0        ; u16
count           dw      0        ; u16
putNumber__i    db      0        ; u8

; ---- arrays ----
composite       times 100 db 0        ; u8[100]
putNumber__digits times 5 db 0        ; u8[5]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack         equ     262        ; 6 worst-case + 256 interrupt reserve
_htop           equ     0FFFEh - _hstack

_hsize          dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw          equ     _heap        ; same bytes, u16 view
