; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
ioBase:         equ     10
ioZeroChar:     equ     48
fileReadOnly:   equ     0
fileFromStart:  equ     0
chunkPayHi:     equ     22
chunkPayLo:     equ     15328
chunkHeaderBytes: equ     32
chunkNameRoom:  equ     12
chunkMoM:       equ     77
chunkMoO:       equ     111
chunkMoS:       equ     83
chunkMoP:       equ     112
chunkAtSet:     equ     4
chunkAtSeq:     equ     6
chunkAtOf:      equ     8
chunkAtPay:     equ     10
chunkAtTotal:   equ     14
chunkAtSum:     equ     18
chunkAtName:    equ     20
chunkMaxOf:     equ     999
mosplit__pathRoom: equ     80
mosplit__bufBytes: equ     32768

; =========================================================== entry ====

__entry:
; ---- takeTail()
        call    mosplit__takeTail
; ---- takeBaseName()
        call    mosplit__takeBaseName
; ---- src = fileOpen( addr( srcPath ), fileReadOnly )
        mov     ax, mosplit__srcPath        ; link-time constant
        mov     [fileOpen__at], ax
        mov     byte [fileOpen__mode], 0
        call    fileOpen
        mov     ax, [fileOpen__ret]
        mov     [mosplit__src], ax
; ---- if ( fileFailed() ) refuse( addr( sNotOpened ) )
        call    fileFailed
        mov     al, [fileFailed__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jz      .L1
        mov     ax, sNotOpened              ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L1:
; ---- measure( src )
        mov     ax, [mosplit__src]
        mov     [mosplit__measure__h], ax
        call    mosplit__measure
; ---- if ( totalHi == 0 && totalLo == 0 ) refuse( addr( sEmpty ) )
        mov     ax, [mosplit__totalHi]
        test    ax, ax
        jne     .L4                         ; unsigned ==
        mov     ax, [mosplit__totalLo]
        test    ax, ax
        jne     .L4                         ; unsigned ==
        mov     ax, sEmpty                  ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L4:
; ---- if ( totalHi < payHi || ( totalHi == payHi && totalLo <= payLo ) ) refuse( addr( sFits ) )
        mov     ax, [mosplit__totalHi]
        mov     bx, [mosplit__payHi]
        cmp     ax, bx
        jb      .L10                        ; unsigned <
        mov     ax, [mosplit__totalHi]
        mov     bx, [mosplit__payHi]
        cmp     ax, bx
        jne     .L8                         ; unsigned ==
        mov     ax, [mosplit__totalLo]
        mov     bx, [mosplit__payLo]
        cmp     ax, bx
        ja      .L8                         ; unsigned <=
.L10:
        mov     ax, sFits                   ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L8:
; ---- sumSource()
        call    mosplit__sumSource
; ---- countChunks()
        call    mosplit__countChunks
; ---- if ( chunks > chunkMaxOf ) refuse( addr( sTooMany ) )
        mov     ax, [mosplit__chunks]
        cmp     ax, 999
        jbe     .L14                        ; unsigned >
        mov     ax, sTooMany                ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L14:
; ---- fileSeek( src, fileFromStart, 0, 0 )
        mov     ax, [mosplit__src]
        mov     [fileSeek__handle], ax
        mov     byte [fileSeek__whence], 0
        mov     word [fileSeek__high], 0
        mov     word [fileSeek__low], 0
        call    fileSeek
; ---- makeChunkName()
        call    mosplit__makeChunkName
; ---- leftHi = totalHi
        mov     ax, [mosplit__totalHi]
        mov     [mosplit__leftHi], ax
; ---- leftLo = totalLo
        mov     ax, [mosplit__totalLo]
        mov     [mosplit__leftLo], ax
; ---- for ( u16 n = 1; n <= chunks; n++ ) {
        mov     word [n], 1
.L17:
        mov     ax, [n]
        mov     bx, [mosplit__chunks]
        cmp     ax, bx
        ja      .L19                        ; unsigned <=
; ---- writeChunk( n )
        mov     ax, [n]
        mov     [mosplit__writeChunk__n], ax
        call    mosplit__writeChunk
.L18:
        inc     word [n]
        jmp     .L17
.L19:
; ---- fileClose( src )
        mov     ax, [mosplit__src]
        mov     [fileClose__handle], ax
        call    fileClose
; ---- putNumber( chunks )
        mov     ax, [mosplit__chunks]
        mov     [putNumber__n], ax
        call    putNumber
; ---- putStr( addr( sChunksOf ) )
        mov     ax, sChunksOf               ; link-time constant
        mov     [putStr__at], ax
        call    putStr
; ---- for ( u16 i = 0; i < baseLen; i++ ) {
        mov     word [i], 0
.L21:
        mov     ax, [i]
        mov     bx, [mosplit__baseLen]
        cmp     ax, bx
        jae     .L23                        ; unsigned <
; ---- putChar( baseName[i] )
        mov     ax, [i]
        mov     bx, ax
        mov     al, [mosplit__baseName + bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
.L22:
        inc     word [i]
        jmp     .L21
.L23:
; ---- putStr( addr( sDash ) )
        mov     ax, sDash                   ; link-time constant
        mov     [putStr__at], ax
        call    putStr
; ---- putSize( totalHi, totalLo )
        mov     ax, [mosplit__totalHi]
        mov     [mosplit__putSize__hi], ax
        mov     ax, [mosplit__totalLo]
        mov     [mosplit__putSize__lo], ax
        call    mosplit__putSize
; ---- putStr( addr( sSet ) )
        mov     ax, sSet                    ; link-time constant
        mov     [putStr__at], ax
        call    putStr
; ---- putNumber( setId )
        mov     ax, [mosplit__setId]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub putChar ====

putChar:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _dl = c
        mov     al, [putChar__c]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x21
        call    int21
        ret

; ============================================== sub putStr ====

putStr:
; ---- _ah = 0x09
        mov     byte [_ah], 9
; ---- _dx = at
        mov     ax, [putStr__at]
        mov     [_dx], ax
; ---- int 0x21
        call    int21
        ret

; ============================================== sub newline ====

newline:
; ---- putChar(13)
        mov     byte [putChar__c], 13
        call    putChar
; ---- putChar(10)
        mov     byte [putChar__c], 10
        call    putChar
        ret

; ============================================== sub space ====

space:
; ---- sub space => putChar(32)
        mov     byte [putChar__c], 32
        call    putChar
        ret

; ============================================== sub putNumber ====

putNumber:
; ---- if (n == 0) {
        mov     ax, [putNumber__n]
        test    ax, ax
        jne     .L25                        ; unsigned ==
; ---- putChar(ioZeroChar)
        mov     byte [putChar__c], 48
        call    putChar
; ---- return
        ret
.L25:
; ---- for (i = 0; n > 0; i++) {
        mov     byte [putNumber__i], 0
.L28:
        mov     ax, [putNumber__n]
        test    ax, ax
        jbe     .L30                        ; unsigned >
; ---- digits[i] = u8(n % ioBase) + ioZeroChar
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        add     ax, 48
        mov     bl, [putNumber__i]
        xor     bh, bh                      ; u8 -> u16
        mov     [putNumber__digits + bx], al
; ---- n /= ioBase
        mov     ax, [putNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     [putNumber__n], ax
.L29:
        inc     byte [putNumber__i]
        jmp     .L28
.L30:
; ---- for (; i > 0; i--) {
.L32:
        mov     al, [putNumber__i]
        test    al, al
        jbe     .L34                        ; unsigned >
; ---- putChar(digits[i - 1])
        mov     al, [putNumber__i]
        xor     ah, ah                      ; u8 -> u16
        dec     ax
        mov     bx, ax
        mov     al, [putNumber__digits + bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
.L33:
        dec     byte [putNumber__i]
        jmp     .L32
.L34:
        ret

; ============================================== sub file__fileCapture ====

file__fileCapture:
; ---- fileBad = _cf
        mov     al, [_cf]
        mov     [file__fileBad], al         ; bool -> bool, no widening
; ---- fileErr = fileBad ? _ax : 0
        test    al, al
        jz      .L36
        mov     ax, [_ax]
        jmp     .L37
.L36:
        xor     ax, ax                      ; 0
.L37:
        mov     [file__fileErr], ax
        ret

; ============================================== bool fileFailed ====

fileFailed:
; ---- bool fileFailed() => fileBad
        mov     al, [file__fileBad]
        mov     [fileFailed__ret], al       ; bool -> bool, no widening
        ret

; ============================================== u16 fileOpen ====

fileOpen:
; ---- _ah = 0x3D
        mov     byte [_ah], 61
; ---- _al = mode
        mov     al, [fileOpen__mode]
        mov     [_al], al                   ; u8 -> u8, no widening
; ---- _dx = at
        mov     ax, [fileOpen__at]
        mov     [_dx], ax
; ---- int 0x21
        call    int21
; ---- fileCapture()
        call    file__fileCapture
; ---- return fileBad ? 0 : _ax
        mov     al, [file__fileBad]
        test    al, al
        jz      .L39
        xor     ax, ax                      ; 0
        jmp     .L40
.L39:
        mov     ax, [_ax]
.L40:
        mov     [fileOpen__ret], ax
        ret

; ============================================== u16 fileCreate ====

fileCreate:
; ---- _ah = 0x3C
        mov     byte [_ah], 60
; ---- _cx = 0
        mov     word [_cx], 0
; ---- _dx = at
        mov     ax, [fileCreate__at]
        mov     [_dx], ax
; ---- int 0x21
        call    int21
; ---- fileCapture()
        call    file__fileCapture
; ---- return fileBad ? 0 : _ax
        mov     al, [file__fileBad]
        test    al, al
        jz      .L42
        xor     ax, ax                      ; 0
        jmp     .L43
.L42:
        mov     ax, [_ax]
.L43:
        mov     [fileCreate__ret], ax
        ret

; ============================================== sub fileClose ====

fileClose:
; ---- _ah = 0x3E
        mov     byte [_ah], 62
; ---- _bx = handle
        mov     ax, [fileClose__handle]
        mov     [_bx], ax
; ---- int 0x21
        call    int21
; ---- fileCapture()
        call    file__fileCapture
        ret

; ============================================== u16 fileRead ====

fileRead:
; ---- _ah = 0x3F
        mov     byte [_ah], 63
; ---- _bx = handle
        mov     ax, [fileRead__handle]
        mov     [_bx], ax
; ---- _cx = count
        mov     ax, [fileRead__count]
        mov     [_cx], ax
; ---- _dx = at
        mov     ax, [fileRead__at]
        mov     [_dx], ax
; ---- int 0x21
        call    int21
; ---- fileCapture()
        call    file__fileCapture
; ---- return fileBad ? 0 : _ax
        mov     al, [file__fileBad]
        test    al, al
        jz      .L45
        xor     ax, ax                      ; 0
        jmp     .L46
.L45:
        mov     ax, [_ax]
.L46:
        mov     [fileRead__ret], ax
        ret

; ============================================== u16 fileWrite ====

fileWrite:
; ---- _ah = 0x40
        mov     byte [_ah], 64
; ---- _bx = handle
        mov     ax, [fileWrite__handle]
        mov     [_bx], ax
; ---- _cx = count
        mov     ax, [fileWrite__count]
        mov     [_cx], ax
; ---- _dx = at
        mov     ax, [fileWrite__at]
        mov     [_dx], ax
; ---- int 0x21
        call    int21
; ---- fileCapture()
        call    file__fileCapture
; ---- return fileBad ? 0 : _ax
        mov     al, [file__fileBad]
        test    al, al
        jz      .L48
        xor     ax, ax                      ; 0
        jmp     .L49
.L48:
        mov     ax, [_ax]
.L49:
        mov     [fileWrite__ret], ax
        ret

; ============================================== u16 fileSeek ====

fileSeek:
; ---- _ah = 0x42
        mov     byte [_ah], 66
; ---- _al = whence
        mov     al, [fileSeek__whence]
        mov     [_al], al                   ; u8 -> u8, no widening
; ---- _bx = handle
        mov     ax, [fileSeek__handle]
        mov     [_bx], ax
; ---- _cx = high
        mov     ax, [fileSeek__high]
        mov     [_cx], ax
; ---- _dx = low
        mov     ax, [fileSeek__low]
        mov     [_dx], ax
; ---- int 0x21
        call    int21
; ---- fileCapture()
        call    file__fileCapture
; ---- return fileBad ? 0 : _ax
        mov     al, [file__fileBad]
        test    al, al
        jz      .L51
        xor     ax, ax                      ; 0
        jmp     .L52
.L51:
        mov     ax, [_ax]
.L52:
        mov     [fileSeek__ret], ax
        ret

; ============================================== u16 chunkSum ====

chunkSum:
; ---- s = carry
        mov     ax, [chunkSum__carry]
        mov     [chunkSum__s], ax
; ---- for ( u16 i = 0; i < count; i++ ) {
        mov     word [chunkSum__i], 0
.L54:
        mov     ax, [chunkSum__i]
        mov     bx, [chunkSum__count]
        cmp     ax, bx
        jae     .L56                        ; unsigned <
; ---- s = s + peek8( at + i )
        mov     ax, [chunkSum__s]
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [chunkSum__at]
        mov     bx, [chunkSum__i]
        add     ax, bx
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        xor     ah, ah                      ; u8 -> u16
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [chunkSum__s], ax
.L55:
        inc     word [chunkSum__i]
        jmp     .L54
.L56:
; ---- return s
        mov     ax, [chunkSum__s]
        mov     [chunkSum__ret], ax
        ret

; ============================================== sub chunkNumber ====

chunkNumber:
; ---- poke8( at, '0' + u8( n / 100 ) )
        mov     ax, [chunkNumber__at]
        push    ax                          ; save the address while the value is computed
        mov     ax, 48
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [chunkNumber__n]
        mov     bx, 100
        xor     dx, dx                      ; clear high half for div
        div     bx
        xor     ah, ah                      ; cast to u8
        mov     bx, ax
        pop     ax
        add     ax, bx
        pop     bx
        mov     [bx], al
; ---- poke8( at + 1, '0' + u8( n / 10 % 10 ) )
        mov     ax, [chunkNumber__at]
        inc     ax
        push    ax                          ; save the address while the value is computed
        mov     ax, 48
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [chunkNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        mov     bx, ax
        pop     ax
        add     ax, bx
        pop     bx
        mov     [bx], al
; ---- poke8( at + 2, '0' + u8( n % 10 ) )
        mov     ax, [chunkNumber__at]
        add     ax, 2
        push    ax                          ; save the address while the value is computed
        mov     ax, 48
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [chunkNumber__n]
        mov     bx, 10
        xor     dx, dx                      ; clear high half for div
        div     bx
        mov     ax, dx                      ; remainder
        xor     ah, ah                      ; cast to u8
        mov     bx, ax
        pop     ax
        add     ax, bx
        pop     bx
        mov     [bx], al
        ret

; ============================================== sub mosplit__refuse ====

mosplit__refuse:
; ---- putStr( addr( sTool ) )
        mov     ax, sTool                   ; link-time constant
        mov     [putStr__at], ax
        call    putStr
; ---- putStr( why )
        mov     ax, [mosplit__refuse__why]
        mov     [putStr__at], ax
        call    putStr
; ---- newline()
        call    newline
; ---- _ax = 0x4C01
        mov     word [_ax], 19457
; ---- int 0x21
        call    int21
        ret

; ============================================== sub mosplit__takeTail ====

mosplit__takeTail:
; ---- n = peek8( 0x80 )
        mov     ax, 128
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        xor     ah, ah                      ; u8 -> u16
        mov     [mosplit__takeTail__n], ax
; ---- at = 0x81
        mov     word [mosplit__takeTail__at], 129
; ---- while ( n > 0 ) {
.L58:
        mov     ax, [mosplit__takeTail__n]
        test    ax, ax
        ja      .L61                        ; unsigned >
        jmp     .L60
.L61:
; ---- while ( n > 0 && peek8( at ) == ' ' ) {
.L62:
        mov     ax, [mosplit__takeTail__n]
        test    ax, ax
        jbe     .L64                        ; unsigned >
        mov     ax, [mosplit__takeTail__at]
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        cmp     al, 32                      ; byte operands, no widening
        jne     .L64                        ; unsigned ==
; ---- at++
        inc     word [mosplit__takeTail__at]
; ---- n--
        dec     word [mosplit__takeTail__n]
.L63:
        jmp     .L62
.L64:
; ---- if ( n == 0 || peek8( at ) == 13 ) break
        mov     ax, [mosplit__takeTail__n]
        test    ax, ax
        je      .L69                        ; unsigned ==
        mov     ax, [mosplit__takeTail__at]
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        cmp     al, 13                      ; byte operands, no widening
        jne     .L67                        ; unsigned ==
.L69:
        jmp     .L60
.L67:
; ---- w = 0
        mov     word [mosplit__takeTail__w], 0
; ---- while ( w < n && peek8( at + w ) != ' ' && peek8( at + w ) != 13 ) {
.L72:
        mov     ax, [mosplit__takeTail__w]
        mov     bx, [mosplit__takeTail__n]
        cmp     ax, bx
        jae     .L74                        ; unsigned <
        mov     ax, [mosplit__takeTail__at]
        mov     bx, [mosplit__takeTail__w]
        add     ax, bx
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        cmp     al, 32                      ; byte operands, no widening
        je      .L74                        ; unsigned !=
        mov     ax, [mosplit__takeTail__at]
        mov     bx, [mosplit__takeTail__w]
        add     ax, bx
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        cmp     al, 13                      ; byte operands, no widening
        je      .L74                        ; unsigned !=
; ---- w++
        inc     word [mosplit__takeTail__w]
.L73:
        jmp     .L72
.L74:
; ---- if ( srcLen == 0 ) {
        mov     ax, [mosplit__srcLen]
        test    ax, ax
        je      .L80                        ; unsigned ==
        jmp     .L78
.L80:
; ---- if ( w >= pathRoom ) refuse( addr( sTwoWords ) )
        mov     ax, [mosplit__takeTail__w]
        cmp     ax, 80
        jb      .L81                        ; unsigned >=
        mov     ax, sTwoWords               ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L81:
; ---- for ( u16 k = 0; k < w; k++ ) {
        mov     word [mosplit__takeTail__k], 0
.L84:
        mov     ax, [mosplit__takeTail__k]
        mov     bx, [mosplit__takeTail__w]
        cmp     ax, bx
        jae     .L86                        ; unsigned <
; ---- srcPath[k] = peek8( at + k )
        mov     ax, [mosplit__takeTail__at]
        mov     bx, [mosplit__takeTail__k]
        add     ax, bx
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        mov     bx, [mosplit__takeTail__k]
        mov     [mosplit__srcPath + bx], al
.L85:
        inc     word [mosplit__takeTail__k]
        jmp     .L84
.L86:
; ---- srcPath[w] = 0
        mov     ax, [mosplit__takeTail__w]
        mov     bx, ax
        mov     byte [mosplit__srcPath + bx], 0
; ---- srcLen = w
        mov     ax, [mosplit__takeTail__w]
        mov     [mosplit__srcLen], ax
        jmp     .L79
.L78:
; ---- } else if ( !payGiven ) {
        mov     al, [mosplit__payGiven]
        test    al, al
        jz      .L90
        jmp     .L88
.L90:
; ---- digits = w > 0 && w <= 5
        mov     ax, [mosplit__takeTail__w]
        test    ax, ax
        jbe     .L91                        ; unsigned >
        mov     ax, [mosplit__takeTail__w]
        cmp     ax, 5
        ja      .L91                        ; unsigned <=
        mov     ax, 1
        jmp     .L92
.L91:
        xor     ax, ax
.L92:
        mov     [mosplit__takeTail__digits], al; narrowed to bool
; ---- value = 0
        mov     word [mosplit__takeTail__value], 0
; ---- for ( u16 k = 0; k < w; k++ ) {
        mov     word [mosplit__takeTail__k], 0
.L95:
        mov     ax, [mosplit__takeTail__k]
        mov     bx, [mosplit__takeTail__w]
        cmp     ax, bx
        jb      .L98                        ; unsigned <
        jmp     .L97
.L98:
; ---- ch = peek8( at + k )
        mov     ax, [mosplit__takeTail__at]
        mov     bx, [mosplit__takeTail__k]
        add     ax, bx
        mov     bx, ax
        mov     al, [bx]                    ; peek8 - unchecked, by design
        mov     [mosplit__takeTail__ch], al ; u8 -> u8, no widening
; ---- if ( ch < '0' || ch > '9' ) digits = false
        cmp     al, 48                      ; byte operands, no widening
        jb      .L101                       ; unsigned <
        mov     al, [mosplit__takeTail__ch]
        cmp     al, 57                      ; byte operands, no widening
        jbe     .L99                        ; unsigned >
.L101:
        mov     byte [mosplit__takeTail__digits], 0
.L99:
; ---- if ( digits ) value = value * 10 + ( ch - '0' )
        mov     al, [mosplit__takeTail__digits]
        test    al, al
        jz      .L104
        mov     ax, [mosplit__takeTail__value]
        mov     bx, 10
        mul     bx                          ; low 16 bits are sign-agnostic
        push    ax                          ; save lhs: rhs is not a leaf
        mov     al, [mosplit__takeTail__ch]
        xor     ah, ah                      ; u8 -> u16
        sub     ax, 48
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [mosplit__takeTail__value], ax
.L104:
.L96:
        inc     word [mosplit__takeTail__k]
        jmp     .L95
.L97:
; ---- if ( !digits || value < 64 ) refuse( addr( sBadPay ) )
        mov     al, [mosplit__takeTail__digits]
        test    al, al
        jz      .L109
        mov     ax, [mosplit__takeTail__value]
        cmp     ax, 64
        jae     .L107                       ; unsigned <
.L109:
        mov     ax, sBadPay                 ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L107:
; ---- payHi = 0
        mov     word [mosplit__payHi], 0
; ---- payLo = value
        mov     ax, [mosplit__takeTail__value]
        mov     [mosplit__payLo], ax
; ---- payGiven = true
        mov     byte [mosplit__payGiven], 1
        jmp     .L89
.L88:
; ---- refuse( addr( sTwoWords ) )
        mov     ax, sTwoWords               ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L89:
.L79:
; ---- at += w
        mov     ax, [mosplit__takeTail__at]
        mov     bx, [mosplit__takeTail__w]
        add     ax, bx
        mov     [mosplit__takeTail__at], ax
; ---- n -= w
        mov     ax, [mosplit__takeTail__n]
        mov     bx, [mosplit__takeTail__w]
        sub     ax, bx
        mov     [mosplit__takeTail__n], ax
.L59:
        jmp     .L58
.L60:
; ---- if ( srcLen == 0 ) {
        mov     ax, [mosplit__srcLen]
        test    ax, ax
        jne     .L112                       ; unsigned ==
; ---- putStr( addr( sUsage ) )
        mov     ax, sUsage                  ; link-time constant
        mov     [putStr__at], ax
        call    putStr
; ---- newline()
        call    newline
; ---- _ax = 0x4C01
        mov     word [_ax], 19457
; ---- int 0x21
        call    int21
.L112:
        ret

; ============================================== sub mosplit__takeBaseName ====

mosplit__takeBaseName:
; ---- from = 0
        mov     word [mosplit__takeBaseName__from], 0
; ---- for ( u16 i = 0; i < srcLen; i++ ) {
        mov     word [mosplit__takeBaseName__i], 0
.L115:
        mov     ax, [mosplit__takeBaseName__i]
        mov     bx, [mosplit__srcLen]
        cmp     ax, bx
        jae     .L117                       ; unsigned <
; ---- ch = srcPath[i]
        mov     ax, [mosplit__takeBaseName__i]
        mov     bx, ax
        mov     al, [mosplit__srcPath + bx]
        mov     [mosplit__takeBaseName__ch], al; u8 -> u8, no widening
; ---- if ( ch == '\\' || ch == ':' || ch == '/' ) from = i + 1
        cmp     al, 92                      ; byte operands, no widening
        je      .L121                       ; unsigned ==
        mov     al, [mosplit__takeBaseName__ch]
        cmp     al, 58                      ; byte operands, no widening
        je      .L121                       ; unsigned ==
        mov     al, [mosplit__takeBaseName__ch]
        cmp     al, 47                      ; byte operands, no widening
        jne     .L119                       ; unsigned ==
.L121:
        mov     ax, [mosplit__takeBaseName__i]
        inc     ax
        mov     [mosplit__takeBaseName__from], ax
.L119:
.L116:
        inc     word [mosplit__takeBaseName__i]
        jmp     .L115
.L117:
; ---- if ( srcLen - from > chunkNameRoom || srcLen == from ) refuse( addr( sLongName ) )
        mov     ax, [mosplit__srcLen]
        mov     bx, [mosplit__takeBaseName__from]
        sub     ax, bx
        cmp     ax, 12
        ja      .L127                       ; unsigned >
        mov     ax, [mosplit__srcLen]
        mov     bx, [mosplit__takeBaseName__from]
        cmp     ax, bx
        jne     .L125                       ; unsigned ==
.L127:
        mov     ax, sLongName               ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L125:
; ---- baseLen = 0
        mov     word [mosplit__baseLen], 0
; ---- for ( u16 i = from; i < srcLen; i++ ) {
        mov     ax, [mosplit__takeBaseName__from]
        mov     [mosplit__takeBaseName__i], ax
.L130:
        mov     ax, [mosplit__takeBaseName__i]
        mov     bx, [mosplit__srcLen]
        cmp     ax, bx
        jae     .L132                       ; unsigned <
; ---- baseName[baseLen] = srcPath[i]
        mov     ax, [mosplit__takeBaseName__i]
        mov     bx, ax
        mov     al, [mosplit__srcPath + bx]
        mov     bx, [mosplit__baseLen]
        mov     [mosplit__baseName + bx], al
; ---- baseLen++
        inc     word [mosplit__baseLen]
.L131:
        inc     word [mosplit__takeBaseName__i]
        jmp     .L130
.L132:
; ---- baseName[baseLen] = 0
        mov     ax, [mosplit__baseLen]
        mov     bx, ax
        mov     byte [mosplit__baseName + bx], 0
        ret

; ============================================== sub mosplit__makeChunkName ====

mosplit__makeChunkName:
; ---- stem = baseLen
        mov     ax, [mosplit__baseLen]
        mov     [mosplit__makeChunkName__stem], ax
; ---- for ( u16 i = 0; i < baseLen; i++ ) {
        mov     word [mosplit__makeChunkName__i], 0
.L134:
        mov     ax, [mosplit__makeChunkName__i]
        mov     bx, [mosplit__baseLen]
        cmp     ax, bx
        jae     .L136                       ; unsigned <
; ---- if ( baseName[i] == '.' ) stem = i
        mov     ax, [mosplit__makeChunkName__i]
        mov     bx, ax
        mov     al, [mosplit__baseName + bx]
        cmp     al, 46                      ; byte operands, no widening
        jne     .L138                       ; unsigned ==
        mov     ax, [mosplit__makeChunkName__i]
        mov     [mosplit__makeChunkName__stem], ax
.L138:
.L135:
        inc     word [mosplit__makeChunkName__i]
        jmp     .L134
.L136:
; ---- if ( stem > 8 ) refuse( addr( sLongName ) )
        mov     ax, [mosplit__makeChunkName__stem]
        cmp     ax, 8
        jbe     .L141                       ; unsigned >
        mov     ax, sLongName               ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L141:
; ---- for ( u16 i = 0; i < stem; i++ ) {
        mov     word [mosplit__makeChunkName__i], 0
.L144:
        mov     ax, [mosplit__makeChunkName__i]
        mov     bx, [mosplit__makeChunkName__stem]
        cmp     ax, bx
        jae     .L146                       ; unsigned <
; ---- chunkName[i] = baseName[i]
        mov     ax, [mosplit__makeChunkName__i]
        mov     bx, ax
        mov     al, [mosplit__baseName + bx]
        mov     bx, [mosplit__makeChunkName__i]
        mov     [mosplit__chunkName + bx], al
.L145:
        inc     word [mosplit__makeChunkName__i]
        jmp     .L144
.L146:
; ---- chunkName[stem] = '.'
        mov     ax, [mosplit__makeChunkName__stem]
        mov     bx, ax
        mov     byte [mosplit__chunkName + bx], 46
; ---- chunkExtAt = stem + 1
        mov     ax, [mosplit__makeChunkName__stem]
        inc     ax
        mov     [mosplit__chunkExtAt], ax
; ---- chunkName[chunkExtAt + 3] = 0
        add     ax, 3
        mov     bx, ax
        mov     byte [mosplit__chunkName + bx], 0
        ret

; ============================================== sub mosplit__putChunkName ====

mosplit__putChunkName:
; ---- for ( u16 i = 0; chunkName[i] != 0; i++ ) {
        mov     word [mosplit__putChunkName__i], 0
.L148:
        mov     ax, [mosplit__putChunkName__i]
        mov     bx, ax
        mov     al, [mosplit__chunkName + bx]
        test    al, al
        je      .L150                       ; unsigned !=
; ---- putChar( chunkName[i] )
        mov     ax, [mosplit__putChunkName__i]
        mov     bx, ax
        mov     al, [mosplit__chunkName + bx]
        mov     [putChar__c], al            ; u8 -> u8, no widening
        call    putChar
.L149:
        inc     word [mosplit__putChunkName__i]
        jmp     .L148
.L150:
        ret

; ============================================== sub mosplit__measure ====

mosplit__measure:
; ---- _ax = 0x4202
        mov     word [_ax], 16898
; ---- _bx = h
        mov     ax, [mosplit__measure__h]
        mov     [_bx], ax
; ---- _cx = 0
        mov     word [_cx], 0
; ---- _dx = 0
        mov     word [_dx], 0
; ---- int 0x21
        call    int21
; ---- totalLo = _ax
        mov     ax, [_ax]
        mov     [mosplit__totalLo], ax
; ---- totalHi = _dx
        mov     ax, [_dx]
        mov     [mosplit__totalHi], ax
; ---- fileSeek( h, fileFromStart, 0, 0 )
        mov     ax, [mosplit__measure__h]
        mov     [fileSeek__handle], ax
        mov     byte [fileSeek__whence], 0
        mov     word [fileSeek__high], 0
        mov     word [fileSeek__low], 0
        call    fileSeek
        ret

; ============================================== bool mosplit__wholePayloadLeft ====

mosplit__wholePayloadLeft:
; ---- if ( leftHi != payHi ) return leftHi > payHi
        mov     ax, [mosplit__leftHi]
        mov     bx, [mosplit__payHi]
        cmp     ax, bx
        je      .L152                       ; unsigned !=
        mov     ax, [mosplit__leftHi]
        mov     bx, [mosplit__payHi]
        cmp     ax, bx
        jbe     .L155                       ; unsigned >
        mov     ax, 1
        jmp     .L156
.L155:
        xor     ax, ax
.L156:
        mov     [mosplit__wholePayloadLeft__ret], al; narrowed to bool
        ret
.L152:
; ---- return leftLo > payLo
        mov     ax, [mosplit__leftLo]
        mov     bx, [mosplit__payLo]
        cmp     ax, bx
        jbe     .L158                       ; unsigned >
        mov     ax, 1
        jmp     .L159
.L158:
        xor     ax, ax
.L159:
        mov     [mosplit__wholePayloadLeft__ret], al; narrowed to bool
        ret

; ============================================== sub mosplit__takePiece ====

mosplit__takePiece:
; ---- if ( wholePayloadLeft() ) {
        call    mosplit__wholePayloadLeft
        mov     al, [mosplit__wholePayloadLeft__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jz      .L161
; ---- pieceHi = payHi
        mov     ax, [mosplit__payHi]
        mov     [mosplit__pieceHi], ax
; ---- pieceLo = payLo
        mov     ax, [mosplit__payLo]
        mov     [mosplit__pieceLo], ax
        jmp     .L162
.L161:
; ---- pieceHi = leftHi
        mov     ax, [mosplit__leftHi]
        mov     [mosplit__pieceHi], ax
; ---- pieceLo = leftLo
        mov     ax, [mosplit__leftLo]
        mov     [mosplit__pieceLo], ax
.L162:
; ---- if ( pieceLo > leftLo ) leftHi--
        mov     ax, [mosplit__pieceLo]
        mov     bx, [mosplit__leftLo]
        cmp     ax, bx
        jbe     .L164                       ; unsigned >
        dec     word [mosplit__leftHi]
.L164:
; ---- leftLo -= pieceLo
        mov     ax, [mosplit__leftLo]
        mov     bx, [mosplit__pieceLo]
        sub     ax, bx
        mov     [mosplit__leftLo], ax
; ---- leftHi -= pieceHi
        mov     ax, [mosplit__leftHi]
        mov     bx, [mosplit__pieceHi]
        sub     ax, bx
        mov     [mosplit__leftHi], ax
        ret

; ============================================== u16 mosplit__nextRead ====

mosplit__nextRead:
; ---- if ( pieceHi != 0 || pieceLo >= bufBytes ) return bufBytes
        mov     ax, [mosplit__pieceHi]
        test    ax, ax
        jne     .L169                       ; unsigned !=
        mov     ax, [mosplit__pieceLo]
        cmp     ax, 32768
        jb      .L167                       ; unsigned >=
.L169:
        mov     word [mosplit__nextRead__ret], 32768
        ret
.L167:
; ---- return pieceLo
        mov     ax, [mosplit__pieceLo]
        mov     [mosplit__nextRead__ret], ax
        ret

; ============================================== sub mosplit__shrinkPiece ====

mosplit__shrinkPiece:
; ---- if ( by > pieceLo ) pieceHi--
        mov     ax, [mosplit__shrinkPiece__by]
        mov     bx, [mosplit__pieceLo]
        cmp     ax, bx
        jbe     .L172                       ; unsigned >
        dec     word [mosplit__pieceHi]
.L172:
; ---- pieceLo -= by
        mov     ax, [mosplit__pieceLo]
        mov     bx, [mosplit__shrinkPiece__by]
        sub     ax, bx
        mov     [mosplit__pieceLo], ax
        ret

; ============================================== sub mosplit__fillHead ====

mosplit__fillHead:
; ---- for ( u16 i = 0; i < chunkHeaderBytes; i++ ) {
        mov     word [mosplit__fillHead__i], 0
.L175:
        mov     ax, [mosplit__fillHead__i]
        cmp     ax, 32
        jae     .L177                       ; unsigned <
; ---- head[i] = 0
        mov     ax, [mosplit__fillHead__i]
        mov     bx, ax
        mov     byte [mosplit__head + bx], 0
.L176:
        inc     word [mosplit__fillHead__i]
        jmp     .L175
.L177:
; ---- head[0] = chunkMoM
        mov     byte [mosplit__head], 77
; ---- head[1] = chunkMoO
        mov     byte [mosplit__head + 1], 111
; ---- head[2] = chunkMoS
        mov     byte [mosplit__head + 2], 83
; ---- head[3] = chunkMoP
        mov     byte [mosplit__head + 3], 112
; ---- poke16( addr( head ) + chunkAtSet, set )
        mov     ax, mosplit__head           ; link-time constant
        add     ax, 4
        push    ax                          ; save the address while the value is computed
        mov     ax, [mosplit__fillHead__set]
        pop     bx
        mov     [bx], ax
; ---- poke16( addr( head ) + chunkAtSeq, seq )
        mov     ax, mosplit__head           ; link-time constant
        add     ax, 6
        push    ax                          ; save the address while the value is computed
        mov     ax, [mosplit__fillHead__seq]
        pop     bx
        mov     [bx], ax
; ---- poke16( addr( head ) + chunkAtOf, of )
        mov     ax, mosplit__head           ; link-time constant
        add     ax, 8
        push    ax                          ; save the address while the value is computed
        mov     ax, [mosplit__fillHead__of]
        pop     bx
        mov     [bx], ax
; ---- poke16( addr( head ) + chunkAtPay, pieceHi )
        mov     ax, mosplit__head           ; link-time constant
        add     ax, 10
        push    ax                          ; save the address while the value is computed
        mov     ax, [mosplit__pieceHi]
        pop     bx
        mov     [bx], ax
; ---- poke16( addr( head ) + chunkAtPay + 2, pieceLo )
        mov     ax, mosplit__head           ; link-time constant
        add     ax, 10
        add     ax, 2
        push    ax                          ; save the address while the value is computed
        mov     ax, [mosplit__pieceLo]
        pop     bx
        mov     [bx], ax
; ---- poke16( addr( head ) + chunkAtTotal, totalHi )
        mov     ax, mosplit__head           ; link-time constant
        add     ax, 14
        push    ax                          ; save the address while the value is computed
        mov     ax, [mosplit__totalHi]
        pop     bx
        mov     [bx], ax
; ---- poke16( addr( head ) + chunkAtTotal + 2, totalLo )
        mov     ax, mosplit__head           ; link-time constant
        add     ax, 14
        add     ax, 2
        push    ax                          ; save the address while the value is computed
        mov     ax, [mosplit__totalLo]
        pop     bx
        mov     [bx], ax
; ---- for ( u16 i = 0; i < baseLen; i++ ) {
        mov     word [mosplit__fillHead__i], 0
.L179:
        mov     ax, [mosplit__fillHead__i]
        mov     bx, [mosplit__baseLen]
        cmp     ax, bx
        jae     .L181                       ; unsigned <
; ---- head[chunkAtName + i] = baseName[i]
        mov     ax, [mosplit__fillHead__i]
        mov     bx, ax
        mov     al, [mosplit__baseName + bx]
        push    ax                          ; save value while computing the index
        mov     ax, 20
        mov     bx, [mosplit__fillHead__i]
        add     ax, bx
        mov     bx, ax
        pop     ax
        mov     [mosplit__head + bx], al
.L180:
        inc     word [mosplit__fillHead__i]
        jmp     .L179
.L181:
        ret

; ============================================== sub mosplit__putSize ====

mosplit__putSize:
; ---- if ( hi == 0 && lo < 32768 ) {
        mov     ax, [mosplit__putSize__hi]
        test    ax, ax
        jne     .L183                       ; unsigned ==
        mov     ax, [mosplit__putSize__lo]
        cmp     ax, 32768
        jae     .L183                       ; unsigned <
; ---- putNumber( lo )
        mov     ax, [mosplit__putSize__lo]
        mov     [putNumber__n], ax
        call    putNumber
; ---- putStr( addr( sBytes ) )
        mov     ax, sBytes                  ; link-time constant
        mov     [putStr__at], ax
        call    putStr
        jmp     .L184
.L183:
; ---- putNumber( hi * 64 + lo / 1024 )
        mov     ax, [mosplit__putSize__hi]
        mov     cl, 6                       ; 8086 has no shift-by-immediate
        shl     ax, cl                      ; * 64 is << 6
        push    ax                          ; save lhs: rhs is not a leaf
        mov     ax, [mosplit__putSize__lo]
        mov     cl, 10                      ; 8086 has no shift-by-immediate
        shr     ax, cl                      ; / 1024 is >> 10
        mov     bx, ax
        pop     ax
        add     ax, bx
        mov     [putNumber__n], ax
        call    putNumber
; ---- putStr( addr( sKb ) )
        mov     ax, sKb                     ; link-time constant
        mov     [putStr__at], ax
        call    putStr
.L184:
        ret

; ============================================== sub mosplit__sumSource ====

mosplit__sumSource:
; ---- leftHi = totalHi
        mov     ax, [mosplit__totalHi]
        mov     [mosplit__leftHi], ax
; ---- leftLo = totalLo
        mov     ax, [mosplit__totalLo]
        mov     [mosplit__leftLo], ax
; ---- while ( leftHi != 0 || leftLo != 0 ) {
.L187:
        mov     ax, [mosplit__leftHi]
        test    ax, ax
        jne     .L190                       ; unsigned !=
        mov     ax, [mosplit__leftLo]
        test    ax, ax
        jne     .L192                       ; unsigned !=
        jmp     .L189
.L192:
.L190:
; ---- got = fileRead( src, addr( buf ), bufBytes )
        mov     ax, [mosplit__src]
        mov     [fileRead__handle], ax
        mov     ax, mosplit__buf            ; link-time constant
        mov     [fileRead__at], ax
        mov     word [fileRead__count], 32768
        call    fileRead
        mov     ax, [fileRead__ret]
        mov     [mosplit__sumSource__got], ax
; ---- if ( got == 0 ) refuse( addr( sShortRead ) )
        test    ax, ax
        jne     .L193                       ; unsigned ==
        mov     ax, sShortRead              ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L193:
; ---- setId = chunkSum( addr( buf ), got, setId )
        mov     ax, mosplit__buf            ; link-time constant
        mov     [chunkSum__at], ax
        mov     ax, [mosplit__sumSource__got]
        mov     [chunkSum__count], ax
        mov     ax, [mosplit__setId]
        mov     [chunkSum__carry], ax
        call    chunkSum
        mov     ax, [chunkSum__ret]
        mov     [mosplit__setId], ax
; ---- if ( got > leftLo ) leftHi--
        mov     ax, [mosplit__sumSource__got]
        mov     bx, [mosplit__leftLo]
        cmp     ax, bx
        jbe     .L196                       ; unsigned >
        dec     word [mosplit__leftHi]
.L196:
; ---- leftLo -= got
        mov     ax, [mosplit__leftLo]
        mov     bx, [mosplit__sumSource__got]
        sub     ax, bx
        mov     [mosplit__leftLo], ax
.L188:
        jmp     .L187
.L189:
        ret

; ============================================== sub mosplit__countChunks ====

mosplit__countChunks:
; ---- leftHi = totalHi
        mov     ax, [mosplit__totalHi]
        mov     [mosplit__leftHi], ax
; ---- leftLo = totalLo
        mov     ax, [mosplit__totalLo]
        mov     [mosplit__leftLo], ax
; ---- while ( leftHi != 0 || leftLo != 0 ) {
.L199:
        mov     ax, [mosplit__leftHi]
        test    ax, ax
        jne     .L202                       ; unsigned !=
        mov     ax, [mosplit__leftLo]
        test    ax, ax
        je      .L201                       ; unsigned !=
.L202:
; ---- takePiece()
        call    mosplit__takePiece
; ---- chunks++
        inc     word [mosplit__chunks]
.L200:
        jmp     .L199
.L201:
        ret

; ============================================== sub mosplit__writeChunk ====

mosplit__writeChunk:
; ---- takePiece()
        call    mosplit__takePiece
; ---- sizeHi = pieceHi
        mov     ax, [mosplit__pieceHi]
        mov     [mosplit__writeChunk__sizeHi], ax
; ---- sizeLo = pieceLo
        mov     ax, [mosplit__pieceLo]
        mov     [mosplit__writeChunk__sizeLo], ax
; ---- chunkNumber( addr( chunkName ) + chunkExtAt, n )
        mov     ax, mosplit__chunkName      ; link-time constant
        mov     bx, [mosplit__chunkExtAt]
        add     ax, bx
        mov     [chunkNumber__at], ax
        mov     ax, [mosplit__writeChunk__n]
        mov     [chunkNumber__n], ax
        call    chunkNumber
; ---- out = fileCreate( addr( chunkName ) )
        mov     ax, mosplit__chunkName      ; link-time constant
        mov     [fileCreate__at], ax
        call    fileCreate
        mov     ax, [fileCreate__ret]
        mov     [mosplit__writeChunk__out], ax
; ---- if ( fileFailed() ) refuse( addr( sNotMade ) )
        call    fileFailed
        mov     al, [fileFailed__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jz      .L205
        mov     ax, sNotMade                ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L205:
; ---- fillHead( setId, n, chunks )
        mov     ax, [mosplit__setId]
        mov     [mosplit__fillHead__set], ax
        mov     ax, [mosplit__writeChunk__n]
        mov     [mosplit__fillHead__seq], ax
        mov     ax, [mosplit__chunks]
        mov     [mosplit__fillHead__of], ax
        call    mosplit__fillHead
; ---- fileWrite( out, addr( head ), chunkHeaderBytes )
        mov     ax, [mosplit__writeChunk__out]
        mov     [fileWrite__handle], ax
        mov     ax, mosplit__head           ; link-time constant
        mov     [fileWrite__at], ax
        mov     word [fileWrite__count], 32
        call    fileWrite
; ---- if ( fileFailed() ) refuse( addr( sShort ) )
        call    fileFailed
        mov     al, [fileFailed__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jz      .L208
        mov     ax, sShort                  ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L208:
; ---- sum = 0
        mov     word [mosplit__writeChunk__sum], 0
; ---- while ( pieceHi != 0 || pieceLo != 0 ) {
.L211:
        mov     ax, [mosplit__pieceHi]
        test    ax, ax
        jne     .L214                       ; unsigned !=
        mov     ax, [mosplit__pieceLo]
        test    ax, ax
        jne     .L216                       ; unsigned !=
        jmp     .L213
.L216:
.L214:
; ---- want = nextRead()
        call    mosplit__nextRead
        mov     ax, [mosplit__nextRead__ret]
        mov     [mosplit__writeChunk__want], ax
; ---- got = fileRead( src, addr( buf ), want )
        mov     ax, [mosplit__src]
        mov     [fileRead__handle], ax
        mov     ax, mosplit__buf            ; link-time constant
        mov     [fileRead__at], ax
        mov     ax, [mosplit__writeChunk__want]
        mov     [fileRead__count], ax
        call    fileRead
        mov     ax, [fileRead__ret]
        mov     [mosplit__writeChunk__got], ax
; ---- if ( got == 0 ) refuse( addr( sShortRead ) )
        test    ax, ax
        jne     .L217                       ; unsigned ==
        mov     ax, sShortRead              ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L217:
; ---- sum = chunkSum( addr( buf ), got, sum )
        mov     ax, mosplit__buf            ; link-time constant
        mov     [chunkSum__at], ax
        mov     ax, [mosplit__writeChunk__got]
        mov     [chunkSum__count], ax
        mov     ax, [mosplit__writeChunk__sum]
        mov     [chunkSum__carry], ax
        call    chunkSum
        mov     ax, [chunkSum__ret]
        mov     [mosplit__writeChunk__sum], ax
; ---- if ( fileWrite( out, addr( buf ), got ) != got ) refuse( addr( sShort ) )
        mov     ax, [mosplit__writeChunk__out]
        mov     [fileWrite__handle], ax
        mov     ax, mosplit__buf            ; link-time constant
        mov     [fileWrite__at], ax
        mov     ax, [mosplit__writeChunk__got]
        mov     [fileWrite__count], ax
        call    fileWrite
        mov     ax, [fileWrite__ret]
        mov     bx, [mosplit__writeChunk__got]
        cmp     ax, bx
        je      .L220                       ; unsigned !=
        mov     ax, sShort                  ; link-time constant
        mov     [mosplit__refuse__why], ax
        call    mosplit__refuse
.L220:
; ---- shrinkPiece( got )
        mov     ax, [mosplit__writeChunk__got]
        mov     [mosplit__shrinkPiece__by], ax
        call    mosplit__shrinkPiece
.L212:
        jmp     .L211
.L213:
; ---- poke16( addr( head ), sum )
        mov     ax, mosplit__head           ; link-time constant
        push    ax                          ; save the address while the value is computed
        mov     ax, [mosplit__writeChunk__sum]
        pop     bx
        mov     [bx], ax
; ---- fileSeek( out, fileFromStart, 0, chunkAtSum )
        mov     ax, [mosplit__writeChunk__out]
        mov     [fileSeek__handle], ax
        mov     byte [fileSeek__whence], 0
        mov     word [fileSeek__high], 0
        mov     word [fileSeek__low], 18
        call    fileSeek
; ---- fileWrite( out, addr( head ), 2 )
        mov     ax, [mosplit__writeChunk__out]
        mov     [fileWrite__handle], ax
        mov     ax, mosplit__head           ; link-time constant
        mov     [fileWrite__at], ax
        mov     word [fileWrite__count], 2
        call    fileWrite
; ---- fileClose( out )
        mov     ax, [mosplit__writeChunk__out]
        mov     [fileClose__handle], ax
        call    fileClose
; ---- space()
        call    space
; ---- space()
        call    space
; ---- putChunkName()
        call    mosplit__putChunkName
; ---- space()
        call    space
; ---- space()
        call    space
; ---- putSize( sizeHi, sizeLo )
        mov     ax, [mosplit__writeChunk__sizeHi]
        mov     [mosplit__putSize__hi], ax
        mov     ax, [mosplit__writeChunk__sizeLo]
        mov     [mosplit__putSize__lo], ax
        call    mosplit__putSize
; ---- putStr( addr( sSum ) )
        mov     ax, sSum                    ; link-time constant
        mov     [putStr__at], ax
        call    putStr
; ---- putNumber( sum )
        mov     ax, [mosplit__writeChunk__sum]
        mov     [putNumber__n], ax
        call    putNumber
; ---- newline()
        call    newline
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        pushf
        pop     ax
        and     al, 1                       ; carry is bit 0
        mov     [_cf], al
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax:            dw      0
_al:            equ     _ax
_ah:            equ     _ax + 1
_bx:            dw      0
_bl:            equ     _bx
_bh:            equ     _bx + 1
_cx:            dw      0
_cl:            equ     _cx
_ch:            equ     _cx + 1
_dx:            dw      0
_dl:            equ     _dx
_dh:            equ     _dx + 1
_si:            dw      0
_di:            dw      0
_cf:            db      0

; ---- variables ----
n:              dw      0        ; u16
i:              dw      0        ; u16
putChar__c:     db      0        ; u8
putStr__at:     dw      0        ; u16
putNumber__n:   dw      0        ; u16
file__fileBad:  db      0        ; bool
file__fileErr:  dw      0        ; u16
fileFailed__ret: db      0        ; bool
fileOpen__at:   dw      0        ; u16
fileOpen__mode: db      0        ; u8
fileOpen__ret:  dw      0        ; u16
fileCreate__at: dw      0        ; u16
fileCreate__ret: dw      0        ; u16
fileClose__handle: dw      0        ; u16
fileRead__handle: dw      0        ; u16
fileRead__at:   dw      0        ; u16
fileRead__count: dw      0        ; u16
fileRead__ret:  dw      0        ; u16
fileWrite__handle: dw      0        ; u16
fileWrite__at:  dw      0        ; u16
fileWrite__count: dw      0        ; u16
fileWrite__ret: dw      0        ; u16
fileSeek__handle: dw      0        ; u16
fileSeek__whence: db      0        ; u8
fileSeek__high: dw      0        ; u16
fileSeek__low:  dw      0        ; u16
fileSeek__ret:  dw      0        ; u16
chunkSum__at:   dw      0        ; u16
chunkSum__count: dw      0        ; u16
chunkSum__carry: dw      0        ; u16
chunkSum__ret:  dw      0        ; u16
chunkNumber__at: dw      0        ; u16
chunkNumber__n: dw      0        ; u16
mosplit__refuse__why: dw      0        ; u16
mosplit__srcLen: dw      0        ; u16
mosplit__payHi: dw      22        ; u16 = 22
mosplit__payLo: dw      15328        ; u16 = 15328
mosplit__payGiven: db      0        ; bool
mosplit__baseLen: dw      0        ; u16
mosplit__chunkExtAt: dw      0        ; u16
mosplit__totalHi: dw      0        ; u16
mosplit__totalLo: dw      0        ; u16
mosplit__measure__h: dw      0        ; u16
mosplit__leftHi: dw      0        ; u16
mosplit__leftLo: dw      0        ; u16
mosplit__pieceHi: dw      0        ; u16
mosplit__pieceLo: dw      0        ; u16
mosplit__wholePayloadLeft__ret: db      0        ; bool
mosplit__nextRead__ret: dw      0        ; u16
mosplit__shrinkPiece__by: dw      0        ; u16
mosplit__fillHead__set: dw      0        ; u16
mosplit__fillHead__seq: dw      0        ; u16
mosplit__fillHead__of: dw      0        ; u16
mosplit__putSize__hi: dw      0        ; u16
mosplit__putSize__lo: dw      0        ; u16
mosplit__src:   dw      0        ; u16
mosplit__setId: dw      0        ; u16
mosplit__chunks: dw      0        ; u16
mosplit__writeChunk__n: dw      0        ; u16
putNumber__i:   db      0        ; u8
chunkSum__i:    dw      0        ; u16
chunkSum__s:    dw      0        ; u16
mosplit__takeTail__k: dw      0        ; u16
mosplit__takeTail__n: dw      0        ; u16
mosplit__takeTail__at: dw      0        ; u16
mosplit__takeTail__w: dw      0        ; u16
mosplit__takeTail__value: dw      0        ; u16
mosplit__takeTail__ch: db      0        ; u8
mosplit__takeTail__digits: db      0        ; bool
mosplit__takeBaseName__i: dw      0        ; u16
mosplit__takeBaseName__from: dw      0        ; u16
mosplit__takeBaseName__ch: db      0        ; u8
mosplit__makeChunkName__i: dw      0        ; u16
mosplit__makeChunkName__stem: dw      0        ; u16
mosplit__putChunkName__i: dw      0        ; u16
mosplit__fillHead__i: dw      0        ; u16
mosplit__sumSource__got: dw      0        ; u16
mosplit__writeChunk__out: dw      0        ; u16
mosplit__writeChunk__want: dw      0        ; u16
mosplit__writeChunk__got: dw      0        ; u16
mosplit__writeChunk__sum: dw      0        ; u16
mosplit__writeChunk__sizeHi: dw      0        ; u16
mosplit__writeChunk__sizeLo: dw      0        ; u16

; ---- arrays ----
sUsage:         db      'usage: mosplit SOURCE [PAYLOAD]$'        ; u8[32] const
sTool:          db      'mosplit: $'        ; u8[10] const
sTwoWords:      db      'one file and at most a payload - nothing else$'        ; u8[46] const
sBadPay:        db      'PAYLOAD is decimal bytes, 64 to 65535$'        ; u8[38] const
sLongName:      db      'the name does not fit 8.3 - split from a shorter one$'        ; u8[53] const
sNotOpened:     db      'not opened$'        ; u8[11] const
sEmpty:         db      'empty - nothing to split$'        ; u8[25] const
sFits:          db      'fits one disk already - copy it instead$'        ; u8[40] const
sTooMany:       db      'more than 999 chunks - raise PAYLOAD$'        ; u8[37] const
sNotMade:       db      'a chunk was not created$'        ; u8[24] const
sShort:         db      'a chunk wrote short - disk full?$'        ; u8[33] const
sShortRead:     db      'the source read short of its own length$'        ; u8[40] const
sBytes:         db      ' bytes$'        ; u8[7] const
sKb:            db      ' KB$'        ; u8[4] const
sSum:           db      '  sum $'        ; u8[7] const
sChunksOf:      db      ' chunks of $'        ; u8[12] const
sSet:           db      '  set $'        ; u8[7] const
sDash:          db      ' - $'        ; u8[4] const
mosplit__srcPath: times 80 db 0        ; u8[80]
mosplit__baseName: times 13 db 0        ; u8[13]
mosplit__chunkName: times 14 db 0        ; u8[14]
mosplit__head:  times 32 db 0        ; u8[32]
putNumber__digits: times 5 db 0        ; u8[5]

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack:        equ     268        ; 12 worst-case + 256 interrupt reserve
_htop:          equ     0FFFEh - _hstack

_hsize:         dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw:         equ     _heap        ; same bytes, u16 view

; =========================================================== views ====
; No storage: each is a name for an offset into something else.

mosplit__buf:   equ     _heap        ; u8[32768]
