; generated by momo - do not edit

        cpu     8086                        ; enforce the strict-8086 subset
        org     100h

; ---- constants: no storage, folded at assembly time ----
screenCols      equ     80
screenRows      equ     25
black           equ     0
lightGray       equ     7
yellow          equ     14
keyUp           equ     72
keyDown         equ     80
keyLeft         equ     75
keyRight        equ     77
keyEsc          equ     27
mapW            equ     20
mapH            equ     10
defAttr         equ     7
playerAttr      equ     14
solidBlock      equ     219

; =========================================================== entry ====

__entry:
; ---- setTextMode()
        call    setTextMode
; ---- hideCursor()
        call    hideCursor
; ---- draw()
        call    draw
; ---- writeAt( playerX, playerY, '@', playerAttr )
        mov     al, [playerX]
        xor     ah, ah                      ; u8 -> u16
        mov     [writeAt__col], al          ; narrowed to u8
        mov     al, [playerY]
        xor     ah, ah                      ; u8 -> u16
        mov     [writeAt__row], al          ; narrowed to u8
        mov     ax, 64
        mov     [writeAt__ch], al           ; narrowed to u8
        mov     ax, 14
        mov     [writeAt__attr], al         ; narrowed to u8
        call    writeAt
; ---- while( true ){
.L1:
        mov     ax, 1
        test    ax, ax
        jnz     .L4
        jmp     .L3
.L4:
; ---- lastKey = readKey()
        call    readKey
        mov     ax, [readKey__ret]
        mov     [lastKey], ax
; ---- if( lo( lastKey ) == keyEsc ) break
        mov     ax, [lastKey]
        xor     ah, ah                      ; cast to u8
        xor     ah, ah                      ; cast to u8
        cmp     ax, 27
        je      .L7                         ; unsigned ==
        jmp     .L5
.L7:
        jmp     .L3
.L5:
; ---- oldPx = playerX
        mov     al, [playerX]
        mov     [oldPx], al                 ; u8 -> u8, no widening
; ---- oldPy = playerY
        mov     al, [playerY]
        mov     [oldPy], al                 ; u8 -> u8, no widening
; ---- if( isMove( keyUp ) && playerY > 0 ){
        mov     ax, 72
        mov     [isMove__key], al           ; narrowed to u8
        call    isMove
        mov     al, [isMove__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L10
        jmp     .L8
.L10:
        mov     al, [playerY]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 0
        ja      .L11                        ; unsigned >
        jmp     .L8
.L11:
; ---- playerY--
        dec     byte [playerY]
        jmp     .L9
.L8:
; ---- } else if( isMove( keyDown ) && playerY < mapH - 1 ){
        mov     ax, 80
        mov     [isMove__key], al           ; narrowed to u8
        call    isMove
        mov     al, [isMove__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L14
        jmp     .L12
.L14:
        mov     al, [playerY]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 9
        jb      .L15                        ; unsigned <
        jmp     .L12
.L15:
; ---- playerY++
        inc     byte [playerY]
        jmp     .L13
.L12:
; ---- } else if( isMove( keyLeft ) && playerX > 0 ){
        mov     ax, 75
        mov     [isMove__key], al           ; narrowed to u8
        call    isMove
        mov     al, [isMove__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L18
        jmp     .L16
.L18:
        mov     al, [playerX]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 0
        ja      .L19                        ; unsigned >
        jmp     .L16
.L19:
; ---- playerX--
        dec     byte [playerX]
        jmp     .L17
.L16:
; ---- } else if( isMove( keyRight ) && playerX < mapW - 1 ){
        mov     ax, 77
        mov     [isMove__key], al           ; narrowed to u8
        call    isMove
        mov     al, [isMove__ret]
        xor     ah, ah                      ; bool -> u16
        test    ax, ax
        jnz     .L22
        jmp     .L20
.L22:
        mov     al, [playerX]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 19
        jb      .L23                        ; unsigned <
        jmp     .L20
.L23:
; ---- playerX++
        inc     byte [playerX]
.L20:
.L17:
.L13:
.L9:
; ---- if( tileAt( playerX, playerY ) == '#'){
        mov     al, [playerY]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 20
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     bl, [playerX]
        xor     bh, bh                      ; u8 -> u16
        add     ax, bx
        mov     bx, ax
        mov     al, [map + bx]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 35
        je      .L26                        ; unsigned ==
        jmp     .L24
.L26:
; ---- playerX = oldPx
        mov     al, [oldPx]
        mov     [playerX], al               ; u8 -> u8, no widening
; ---- playerY = oldPy
        mov     al, [oldPy]
        mov     [playerY], al               ; u8 -> u8, no widening
        jmp     .L25
.L24:
; ---- writeAt( oldPx, oldPy, tileAt( oldPx, oldPy ), defAttr )
        mov     al, [oldPx]
        xor     ah, ah                      ; u8 -> u16
        mov     [writeAt__col], al          ; narrowed to u8
        mov     al, [oldPy]
        xor     ah, ah                      ; u8 -> u16
        mov     [writeAt__row], al          ; narrowed to u8
        mov     al, [oldPy]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 20
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     bl, [oldPx]
        xor     bh, bh                      ; u8 -> u16
        add     ax, bx
        mov     bx, ax
        mov     al, [map + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [writeAt__ch], al           ; narrowed to u8
        mov     ax, 7
        mov     [writeAt__attr], al         ; narrowed to u8
        call    writeAt
; ---- writeAt( playerX, playerY, '@', playerAttr )
        mov     al, [playerX]
        xor     ah, ah                      ; u8 -> u16
        mov     [writeAt__col], al          ; narrowed to u8
        mov     al, [playerY]
        xor     ah, ah                      ; u8 -> u16
        mov     [writeAt__row], al          ; narrowed to u8
        mov     ax, 64
        mov     [writeAt__ch], al           ; narrowed to u8
        mov     ax, 14
        mov     [writeAt__attr], al         ; narrowed to u8
        call    writeAt
.L25:
.L2:
        jmp     .L1
.L3:
; ---- moveTo( 0, 0 )
        mov     ax, 0
        mov     [moveTo__col], al           ; narrowed to u8
        mov     ax, 0
        mov     [moveTo__row], al           ; narrowed to u8
        call    moveTo
; ---- showCursor()
        call    showCursor
; ---- cls()
        call    cls

; ---- implicit exit ----
        mov     word [_ax], 0x4C00          ; DOS terminate, exit code 0
        call    int21

; ============================================== sub setTextMode ====

setTextMode:
; ---- _ax = 0x0003
        mov     word [_ax], 3
; ---- int 0x10
        call    int10
        ret

; ============================================== sub clearScreen ====

clearScreen:
; ---- _ax = 0x0600
        mov     word [_ax], 1536
; ---- _bh = attr
        mov     al, [clearScreen__attr]
        mov     [_bh], al                   ; u8 -> u8, no widening
; ---- _cx = 0                       // top-left: row 0, column 0
        mov     word [_cx], 0
; ---- _dh = screenRows - 1
        mov     byte [_dh], 24
; ---- _dl = screenCols - 1
        mov     byte [_dl], 79
; ---- int 0x10
        call    int10
        ret

; ============================================== sub moveTo ====

moveTo:
; ---- _ah = 0x02
        mov     byte [_ah], 2
; ---- _bh = 0                       // page 0
        mov     byte [_bh], 0
; ---- _dh = row
        mov     al, [moveTo__row]
        mov     [_dh], al                   ; u8 -> u8, no widening
; ---- _dl = col
        mov     al, [moveTo__col]
        mov     [_dl], al                   ; u8 -> u8, no widening
; ---- int 0x10
        call    int10
        ret

; ============================================== sub putCell ====

putCell:
; ---- _ah = 0x09
        mov     byte [_ah], 9
; ---- _al = ch
        mov     al, [putCell__ch]
        mov     [_al], al                   ; u8 -> u8, no widening
; ---- _bh = 0
        mov     byte [_bh], 0
; ---- _bl = attr
        mov     al, [putCell__attr]
        mov     [_bl], al                   ; u8 -> u8, no widening
; ---- _cx = 1
        mov     word [_cx], 1
; ---- int 0x10
        call    int10
        ret

; ============================================== sub writeAt ====

writeAt:
; ---- moveTo(col, row)
        mov     al, [writeAt__col]
        xor     ah, ah                      ; u8 -> u16
        mov     [moveTo__col], al           ; narrowed to u8
        mov     al, [writeAt__row]
        xor     ah, ah                      ; u8 -> u16
        mov     [moveTo__row], al           ; narrowed to u8
        call    moveTo
; ---- putCell(ch, attr)
        mov     al, [writeAt__ch]
        xor     ah, ah                      ; u8 -> u16
        mov     [putCell__ch], al           ; narrowed to u8
        mov     al, [writeAt__attr]
        xor     ah, ah                      ; u8 -> u16
        mov     [putCell__attr], al         ; narrowed to u8
        call    putCell
        ret

; ============================================== sub hideCursor ====

hideCursor:
; ---- _ah = 0x01
        mov     byte [_ah], 1
; ---- _cx = 0x2000                  // bit 5 of CH hides the cursor
        mov     word [_cx], 8192
; ---- int 0x10
        call    int10
        ret

; ============================================== sub showCursor ====

showCursor:
; ---- _ah = 0x01
        mov     byte [_ah], 1
; ---- _cx = 0x0607                  // a small underline
        mov     word [_cx], 1543
; ---- int 0x10
        call    int10
        ret

; ============================================== u16 readKey ====

readKey:
; ---- _ah = 0x00
        mov     byte [_ah], 0
; ---- int 0x16
        call    int16
; ---- return _ax
        mov     ax, [_ax]
        mov     [readKey__ret], ax
        ret

; ============================================== sub cls ====

cls:
; ---- sub cls => clearScreen( defAttr )
        mov     ax, 7
        mov     [clearScreen__attr], al     ; narrowed to u8
        call    clearScreen
        ret

; ============================================== bool isMove ====

isMove:
; ---- bool isMove( u8 key ) => lo( lastKey ) == 0 && hi( lastKey ) == key
        mov     ax, [lastKey]
        xor     ah, ah                      ; cast to u8
        xor     ah, ah                      ; cast to u8
        cmp     ax, 0
        je      .L29                        ; unsigned ==
        jmp     .L27
.L29:
        mov     ax, [lastKey]
        mov     cl, 8                       ; 8086 has no shift-by-immediate
        shr     ax, cl                      ; unsigned >>
        xor     ah, ah                      ; cast to u8
        xor     ah, ah                      ; cast to u8
        mov     bl, [isMove__key]
        xor     bh, bh                      ; u8 -> u16
        cmp     ax, bx
        je      .L30                        ; unsigned ==
        jmp     .L27
.L30:
        mov     ax, 1
        jmp     .L28
.L27:
        xor     ax, ax
.L28:
        mov     [isMove__ret], al           ; narrowed to bool
        ret

; ============================================== sub draw ====

draw:
; ---- for( y = 0; y < mapH; y++ ){
        mov     byte [y], 0
.L31:
        mov     al, [y]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 10
        jb      .L34                        ; unsigned <
        jmp     .L33
.L34:
; ---- for( x = 0; x < mapW; x++ ){
        mov     byte [x], 0
.L35:
        mov     al, [x]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 20
        jb      .L38                        ; unsigned <
        jmp     .L37
.L38:
; ---- ch = tileAt( x, y )
        mov     al, [y]
        xor     ah, ah                      ; u8 -> u16
        mov     bx, 20
        mul     bx                          ; low 16 bits are sign-agnostic
        mov     bl, [x]
        xor     bh, bh                      ; u8 -> u16
        add     ax, bx
        mov     bx, ax
        mov     al, [map + bx]
        xor     ah, ah                      ; u8 -> u16
        mov     [ch_], al                   ; narrowed to u8
; ---- if( ch == '#') ch = solidBlock
        mov     al, [ch_]
        xor     ah, ah                      ; u8 -> u16
        cmp     ax, 35
        je      .L41                        ; unsigned ==
        jmp     .L39
.L41:
        mov     byte [ch_], 219
.L39:
; ---- writeAt( x, y, ch, defAttr )
        mov     al, [x]
        xor     ah, ah                      ; u8 -> u16
        mov     [writeAt__col], al          ; narrowed to u8
        mov     al, [y]
        xor     ah, ah                      ; u8 -> u16
        mov     [writeAt__row], al          ; narrowed to u8
        mov     al, [ch_]
        xor     ah, ah                      ; u8 -> u16
        mov     [writeAt__ch], al           ; narrowed to u8
        mov     ax, 7
        mov     [writeAt__attr], al         ; narrowed to u8
        call    writeAt
.L36:
        inc     byte [x]
        jmp     .L35
.L37:
.L32:
        inc     byte [y]
        jmp     .L31
.L33:
        ret

; ==================================================== int helpers ====
; One per distinct interrupt: the literal is baked in, so the register
; sync is emitted once rather than at every call site.

int10:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x10
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

int16:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x16
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

int21:
        mov     ax, [_ax]
        mov     bx, [_bx]
        mov     cx, [_cx]
        mov     dx, [_dx]
        mov     si, [_si]
        mov     di, [_di]
        int     0x21
        mov     [_ax], ax
        mov     [_bx], bx
        mov     [_cx], cx
        mov     [_dx], dx
        mov     [_si], si
        mov     [_di], di
        ret

; ============================================================ data ====

; ---- reserved globals: the machine registers ----
_ax             dw      0
_al             equ     _ax
_ah             equ     _ax + 1
_bx             dw      0
_bl             equ     _bx
_bh             equ     _bx + 1
_cx             dw      0
_cl             equ     _cx
_ch             equ     _cx + 1
_dx             dw      0
_dl             equ     _dx
_dh             equ     _dx + 1
_si             dw      0
_di             dw      0

; ---- variables ----
clearScreen__attr db      0        ; u8
moveTo__col     db      0        ; u8
moveTo__row     db      0        ; u8
putCell__ch     db      0        ; u8
putCell__attr   db      0        ; u8
writeAt__col    db      0        ; u8
writeAt__row    db      0        ; u8
writeAt__ch     db      0        ; u8
writeAt__attr   db      0        ; u8
readKey__ret    dw      0        ; u16
playerX         db      9        ; u8 = 9
playerY         db      4        ; u8 = 4
y               db      0        ; u8
x               db      0        ; u8
oldPx           db      0        ; u8
oldPy           db      0        ; u8
ch_             db      0        ; u8
lastKey         dw      0        ; u16
isMove__key     db      0        ; u8
isMove__ret     db      0        ; bool

; ---- arrays ----
map             db      '########    ##########....########....####................######............####  ##............##    ##............##  ####............######................####....########....##########    ########'        ; u8[200] const

; ============================================================ heap ====
; No storage is emitted - a .COM owns everything past its image, so
; these are addresses and NASM does the arithmetic.

_hstack         equ     262        ; 6 worst-case + 256 interrupt reserve
_htop           equ     0FFFEh - _hstack

_hsize          dw      _htop - _heap        ; NASM computes this
        align   2                           ; keep the u16 view aligned
_heap:
_heapw          equ     _heap        ; same bytes, u16 view
